namespace MahapatraArts.Services;

public static class ContentWorks
{
    private static LStr S(string en, string fr, string de, string ja) => new(en, fr, de, ja);

    public static readonly IReadOnlyList<Work> Works =
    [
        new("nataraj-patchwork", "rare",
            S("Nataraja, multicoloured stone patchwork", "Nataraja, patchwork de pierres multicolores", "Nataraja, mehrfarbiges Steinpatchwork", "ナタラージャ、多色石のパッチワーク"),
            S("Six feet high. The atelier names this Nataraja as Ramakanta’s own innovation: multicoloured stone patchwork, with the body, the flame ring and the attendants each held in a different stone.",
              "Six pieds. L’atelier présente ce Nataraja comme l’innovation de Ramakanta : un patchwork de pierres multicolores, le corps, le cercle de flammes et les assistants tenus chacun dans une pierre différente.",
              "Sechs Fuß. Das Atelier nennt diesen Nataraja Ramakantas eigene Neuerung: mehrfarbiges Steinpatchwork, Körper, Flammenring und Begleitfiguren jeweils in einem anderen Stein.",
              "高さ6フィート。工房はこのナタラージャを、ラマカンタ自身の工夫と記します。多色石のパッチワークで、身体、炎の円光、脇侍をそれぞれ別の石で保ちます。"),
            S("Multicoloured stone patchwork", "Patchwork de pierres multicolores", "Mehrfarbiges Steinpatchwork", "多色石のパッチワーク"),
            "Patchwork stone",
            S("6 ft", "6 pieds", "6 Fuß", "6フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "peacock", "—", "tall"),
        new("ganapati-multicolour", "idols",
            S("Lord Ganapati", "Seigneur Ganapati", "Herr Ganapati", "ガナパティ"),
            S("Seven feet high, in multicoloured stone. Ganapati sits in a shrine-like surround, the yellow and russet stones set together as one image.",
              "Sept pieds, en pierre multicolore. Ganapati siège dans un entourage de sanctuaire, les pierres jaunes et rousses assemblées en une seule image.",
              "Sieben Fuß, in mehrfarbigem Stein. Ganapati sitzt in einer schreinartigen Rahmung, gelbe und rostrote Steine zu einem Bild gefügt.",
              "高さ7フィート、多色石。ガナパティは祠のような囲みに坐し、黄と赤褐の石が一つの像になります。"),
            S("Multicoloured stone", "Pierre multicolore", "Mehrfarbiger Stein", "多色石"),
            "Patchwork stone",
            S("7 ft", "7 pieds", "7 Fuß", "7フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("mixed-onyx-ganesha", "idols",
            S("Mixed onyx Ganesha", "Ganesha en onyx mêlé", "Ganesha aus gemischtem Onyx", "混成オニックスのガネーシャ"),
            S("Eight feet high. A mixed onyx Ganesha by Ramakanta, the green and red of the stone left visible in the leaves, the trunk and the crown.",
              "Huit pieds. Un Ganesha en onyx mêlé de Ramakanta : le vert et le rouge de la pierre restent lisibles dans les feuilles, la trompe et la couronne.",
              "Acht Fuß. Ein Ganesha aus gemischtem Onyx von Ramakanta. Grün und Rot des Steins bleiben in Blättern, Rüssel und Krone sichtbar.",
              "高さ8フィート。ラマカンタによる混成オニックスのガネーシャ。葉、鼻、冠に石の緑と赤が残ります。"),
            S("Mixed onyx", "Onyx mêlé", "Gemischter Onyx", "混成オニックス"),
            "Onyx",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("saranath-buddha", "idols",
            S("Sarnath Buddha", "Bouddha de Sarnath", "Sarnath-Buddha", "サールナートの仏陀"),
            S("Nine feet high. A black granite Buddha in the Sarnath type, described by the atelier as a unique creation by Ramakanta: the wheel-turning hands, the lion throne and the flying figures above the halo.",
              "Neuf pieds. Un Bouddha de granit noir du type de Sarnath, que l’atelier décrit comme une création unique de Ramakanta : les mains qui tournent la roue, le trône aux lions et les figures volantes au-dessus du halo.",
              "Neun Fuß. Ein Buddha aus schwarzem Granit vom Sarnath-Typus, vom Atelier als einzigartige Schöpfung Ramakantas beschrieben: die raddrehenden Hände, der Löwenthron und die fliegenden Figuren über dem Nimbus.",
              "高さ9フィート。サールナート型の黒御影石の仏陀。工房はラマカンタの独自の作と記します。転法輪の印、獅子座、光背の上の飛天。"),
            S("Black granite", "Granit noir", "Schwarzer Granit", "黒御影石"),
            "Black granite",
            S("9 ft", "9 pieds", "9 Fuß", "9フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "kalasha", "—", "tall"),
        new("buddha-meditation", "idols",
            S("Buddha in meditation", "Bouddha en méditation", "Buddha in Meditation", "瞑想の仏陀"),
            S("Eight feet high. Lord Buddha seated in meditation, with smaller Buddhas set in the niches of the throne behind him.",
              "Huit pieds. Le Bouddha assis en méditation, de plus petits Bouddhas placés dans les niches du trône derrière lui.",
              "Acht Fuß. Der Buddha sitzt in Meditation, kleinere Buddhas in den Nischen des Throns hinter ihm.",
              "高さ8フィート。瞑想する仏陀。背後の座の龕に、小さな仏陀が並びます。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "temple", "—", "tall"),
        new("buddha-russian-museum", "international",
            S("Buddha for the Russian Museum", "Bouddha pour le musée russe", "Buddha für das Russische Museum", "ロシアの美術館のための仏陀"),
            S("A stele of the seated Buddha carved by Ramakanta for the Russian Museum, with attendants in the side niches and lions at the base.",
              "Une stèle du Bouddha assis, taillée par Ramakanta pour le musée russe, avec des assistants dans les niches latérales et des lions au socle.",
              "Eine Stele des sitzenden Buddha, von Ramakanta für das Russische Museum gehauen, mit Begleitern in den Seitennischen und Löwen am Sockel.",
              "ロシアの美術館のためにラマカンタが刻んだ坐仏の石碑。脇の龕に脇侍、基壇に獅子。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Stele", "Stèle", "Stele", "石碑"),
            S("Russian Museum", "Musée russe", "Russisches Museum", "ロシアの美術館"),
            "kalasha", "—", "tall"),
        new("buddha-heads", "idols",
            S("Buddha heads", "Têtes de Bouddha", "Buddhaköpfe", "仏頭"),
            S("Two stone heads of the Buddha carved by Ramakanta, one in grey stone and one in warm sandstone, the hair and the ushnisha built curl by curl.",
              "Deux têtes de Bouddha en pierre, taillées par Ramakanta, l’une en pierre grise, l’autre en grès chaud, les cheveux et l’ushnisha boucle par boucle.",
              "Zwei steinerne Buddhaköpfe von Ramakanta, einer in grauem Stein, einer in warmem Sandstein. Haar und Ushnisha Locke für Locke.",
              "ラマカンタが刻んだ二つの仏頭。一つは灰色の石、一つは温かい砂岩。髪と肉髻を巻ごとに造ります。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Heads", "Têtes", "Köpfe", "頭部"),
            S("Workshop", "Atelier", "Werkstatt", "工房"),
            "murti", "—", "regular"),
        new("mukteswar-gate-delhi", "architecture",
            S("Mukteswar pattern gate, Delhi", "Porte au modèle de Mukteswar, Delhi", "Tor im Mukteswar-Muster, Delhi", "ムクテーシュワル型の門、デリー"),
            S("Thirteen feet. A gate in the Mukteswar pattern, installed in Delhi by Ramakanta. The same record shows him passing the carving of pillars on to a younger generation.",
              "Treize pieds. Une porte au modèle de Mukteswar, installée à Delhi par Ramakanta. Le même dossier le montre transmettant la taille des piliers à une génération plus jeune.",
              "Dreizehn Fuß. Ein Tor im Mukteswar-Muster, von Ramakanta in Delhi aufgestellt. Dieselbe Aufzeichnung zeigt, wie er die Pfeilerarbeit an eine jüngere Generation weitergibt.",
              "13フィート。ムクテーシュワル型の門を、ラマカンタがデリーに設置しました。同じ記録に、柱の彫りを若い世代へ渡す姿があります。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("13 ft", "13 pieds", "13 Fuß", "13フィート"),
            S("Delhi, India", "Delhi, Inde", "Delhi, Indien", "インド、デリー"),
            "gate", "—", "wide"),
        new("jaypee-marble", "idols",
            S("White marble figures, Jaypee University", "Figures de marbre blanc, université Jaypee", "Figuren aus weißem Marmor, Jaypee-Universität", "白大理石の像、ジャイピー大学"),
            S("Seven feet high. A set of white marble figures installed at Jaypee University, Uttar Pradesh: Hanuman, Shiva, Durga, Lakshmi, and standing deities including a divine pair.",
              "Sept pieds. Un ensemble de figures en marbre blanc installé à l’université Jaypee, Uttar Pradesh : Hanuman, Shiva, Durga, Lakshmi, et des divinités debout, dont un couple divin.",
              "Sieben Fuß. Eine Folge von Figuren aus weißem Marmor an der Jaypee-Universität, Uttar Pradesh: Hanuman, Shiva, Durga, Lakshmi und stehende Gottheiten, darunter ein göttliches Paar.",
              "高さ7フィート。ウッタル・プラデーシュのジャイピー大学に設置した白大理石の像。ハヌマーン、シヴァ、ドゥルガー、ラクシュミー、そして神の対を含む立像。"),
            S("White marble", "Marbre blanc", "Weißer Marmor", "白大理石"),
            "White marble",
            S("7 ft", "7 pieds", "7 Fuß", "7フィート"),
            S("Jaypee University, Uttar Pradesh, India", "Université Jaypee, Uttar Pradesh, Inde", "Jaypee-Universität, Uttar Pradesh, Indien", "インド、ウッタル・プラデーシュ、ジャイピー大学"),
            "murti", "—", "tall"),
        new("prashanti-nilayam", "architecture",
            S("Work for Prashanti Nilayam", "Œuvre pour Prashanti Nilayam", "Arbeit für Prashanti Nilayam", "プラシャンティ・ニラヤムのための仕事"),
            S("Architectural stone for Shri Satya Sai Prashanti Nilayam in Andhra Pradesh: a chariot-wheel panel, a carved mandapam, and figures prepared for the site.",
              "Pierre d’architecture pour Shri Satya Sai Prashanti Nilayam, en Andhra Pradesh : un panneau à roue de char, un mandapam sculpté, et des figures préparées pour le lieu.",
              "Architekturstein für Shri Satya Sai Prashanti Nilayam in Andhra Pradesh: eine Wagenradtafel, ein geschnitztes Mandapam und Figuren für den Ort.",
              "アンドラ・プラデーシュのシュリー・サティヤ・サイ・プラシャンティ・ニラヤムのための建築の石。戦車の車輪のパネル、刻まれたマンダパム、その場のための像。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Architectural ensemble", "Ensemble architectural", "Architektonisches Ensemble", "建築の一組"),
            S("Prashanti Nilayam, Andhra Pradesh, India", "Prashanti Nilayam, Andhra Pradesh, Inde", "Prashanti Nilayam, Andhra Pradesh, Indien", "インド、アンドラ・プラデーシュ、プラシャンティ・ニラヤム"),
            "wheel", "—", "wide"),
        new("temple-drawing", "architecture",
            S("Temple drawings", "Dessins de temple", "Tempelzeichnungen", "寺院の図面"),
            S("Measured drawings from the atelier. The sheets set out the elevation of a temple, bay by bay, before the stone is cut.",
              "Dessins cotés de l’atelier. Les feuilles établissent l’élévation d’un temple, travée par travée, avant que la pierre ne soit coupée.",
              "Bemaßte Zeichnungen des Ateliers. Die Blätter legen die Ansicht eines Tempels Feld für Feld fest, bevor der Stein geschnitten wird.",
              "工房の寸法図。石を切る前に、寺院の立面を間ごとに定めます。"),
            S("Drawing on paper", "Dessin sur papier", "Zeichnung auf Papier", "紙の図面"),
            "Paper",
            S("Sheets", "Feuilles", "Blätter", "図面"),
            S("Atelier", "Atelier", "Atelier", "工房"),
            "pillar", "—", "wide"),
        new("semiprecious-stone", "idols",
            S("Semi-precious stone", "Pierre semi-précieuse", "Halbedelstein", "半貴石"),
            S("Guru Ramakanta carving semi-precious stone at his workshop, with finished heads in gold-toned and green stone beside the bench.",
              "Guru Ramakanta taille la pierre semi-précieuse dans son atelier, des têtes achevées en pierre dorée et verte à côté de l’établi.",
              "Guru Ramakanta arbeitet in seiner Werkstatt an Halbedelstein. Fertige Köpfe in goldtonigem und grünem Stein stehen neben der Bank.",
              "グル・ラマカンタが工房で半貴石を刻みます。作業台の傍らに、金色と緑の石の頭部があります。"),
            S("Semi-precious stone", "Pierre semi-précieuse", "Halbedelstein", "半貴石"),
            "Semi-precious stone",
            S("Workshop pieces", "Pièces d’atelier", "Werkstattstücke", "工房の作"),
            S("Workshop", "Atelier", "Werkstatt", "工房"),
            "murti", "—", "tall"),
        new("viswaroop-darsan", "rare",
            S("Viswaroop Darsan", "Viswaroop Darsan", "Viswaroop Darsan", "ヴィシュワループ・ダルシャン"),
            S("A vision of the cosmic form: many attributes held in one body of stone. The atelier approaches Viswaroop as a test of order — the terror and the grace must be legible at once, and the block must not break into anecdote. Multi-coloured patchwork is used where colour itself is part of the theology of the image.",
              "Une vision de la forme cosmique : de nombreux attributs tenus dans un seul corps de pierre. L’atelier traite le Viswaroop comme une épreuve d’ordre — la terreur et la grâce doivent être lisibles ensemble. Le patchwork multicolore intervient lorsque la couleur appartient à la théologie de l’image.",
              "Eine Vision der kosmischen Form: viele Attribute in einem Körper aus Stein. Das Atelier behandelt Viswaroop als eine Probe der Ordnung — Schrecken und Gnade müssen zugleich lesbar sein. Mehrfarbiges Patchwork tritt ein, wo Farbe selbst zur Theologie des Bildes gehört.",
              "宇宙の姿の顕現。多くの持物を、一つの石の身体に保つ。工房はヴィシュワループを、秩序の試練として扱います。畏れと慈悲が同時に読め、石が逸話に崩れないこと。色そのものが像の神学に属するとき、多色のパッチワークを用います。"),
            S("Sandstone with multi-coloured stone patchwork", "Grès et patchwork de pierres multicolores", "Sandstein mit mehrfarbigem Steinpatchwork", "砂岩と多色石のパッチワーク"),
            "Khandolite",
            S("Monumental relief, architectural scale", "Relief monumental, échelle d’architecture", "Monumentales Relief, architektonischer Maßstab", "記念碑的な浮彫、建築の規模"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "peacock", "—", "tall"),
        new("dasavatara", "temple",
            S("Dasavatara Sculpture", "Sculpture du Dasavatara", "Dasavatara-Skulptur", "ダシャーヴァターラ"),
            S("Eight feet, in a posture the atelier calls unique. The Dasa Avatar is carved as one standing image, with the face, the crown and the attributes held in pale stone.",
              "Huit pieds, dans une posture que l’atelier dit unique. Le Dasa Avatar est taillé comme une seule figure debout, le visage, la couronne et les attributs tenus dans une pierre pâle.",
              "Acht Fuß, in einer Haltung, die das Atelier einzigartig nennt. Der Dasa Avatar ist als eine stehende Figur gehauen, Gesicht, Krone und Attribute in hellem Stein.",
              "高さ8フィート。工房が独自の姿と記すダシャーヴァターラ。淡い石に、顔、冠、持物を一つの立像として刻みます。"),
            S("Pale stone", "Pierre pâle", "Heller Stein", "淡い石"),
            "Stone",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "wheel", "—", "tall"),
        new("seven-temple-shrines-singapore", "international",
            S("Seven Temple Shrines, Singapore", "Sept sanctuaires, Singapour", "Sieben Tempelschreine, Singapur", "シンガポールの七つの祠堂"),
            S("An ensemble of seven shrines prepared in the Odishan temple tradition and installed in Singapore. The work had to travel: each shrine cut so that it could be crated, read on arrival, and still belong to one ritual family.",
              "Un ensemble de sept sanctuaires préparé dans la tradition des temples de l’Odisha et installé à Singapour. L’œuvre devait voyager : chaque sanctuaire taillé pour la caisse, lisible à l’arrivée, et toujours d’une même famille rituelle.",
              "Ein Ensemble von sieben Schreinen in der odishanischen Tempeltradition, aufgestellt in Singapur. Die Arbeit musste reisen: jeder Schrein so gehauen, dass er verpackt werden konnte und bei der Ankunft noch zu einer rituellen Familie gehörte.",
              "オディシャの寺院伝統で準備し、シンガポールに設置した七つの祠堂。仕事は旅をしなければなりません。それぞれを梱包でき、着いたときに読め、なお一つの祭祀の家族に属するように刻みます。"),
            S("Granite and sandstone", "Granit et grès", "Granit und Sandstein", "花崗岩と砂岩"),
            "Granite",
            S("Seven-shrine ensemble", "Ensemble de sept sanctuaires", "Ensemble von sieben Schreinen", "七祠堂の一組"),
            S("Singapore", "Singapour", "Singapur", "シンガポール"),
            "temple", "—", "wide"),
        new("perumal-mandapam", "architecture",
            S("Perumal Mandapam", "Perumal Mandapam", "Perumal Mandapam", "ペルマル・マンダパム"),
            S("A mandapam is a pillared hall, not an ornament applied afterwards. Perumal Mandapam is approached as architecture: load, rhythm of columns, and the sculpture that the hall is strong enough to carry.",
              "Un mandapam est une salle à piliers, non un ornement ajouté ensuite. Perumal Mandapam est abordé comme architecture : la charge, le rythme des colonnes, et la sculpture que la salle est assez forte pour porter.",
              "Ein Mandapam ist eine Pfeilerhalle, kein nachträglich aufgesetzter Schmuck. Perumal Mandapam wird als Architektur behandelt: Last, Rhythmus der Stützen und die Skulptur, die die Halle zu tragen vermag.",
              "マンダパムは柱の間であり、後から足す装飾ではありません。ペルマル・マンダパムは建築として扱います。荷重、柱のリズム、そしてその間が担える彫刻。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Pillared hall, architectural", "Salle à piliers, architecture", "Pfeilerhalle, architektonisch", "柱間、建築"),
            S("India", "Inde", "Indien", "インド"),
            "pillar", "—", "wide"),
        new("ashokan-pillar-japan", "international",
            S("Ashokan Pillar, Japan", "Pilier d’Ashoka, Japon", "Ashoka-Säule, Japan", "日本のアショーカ石柱"),
            S("Installed in 1995. The Ashokan pillar is a memory of the Mauryan column — a shaft, a capital, an animal of state — translated by an Odishan hand for a site in Japan. It is the work that first made the atelier’s journey abroad a fact rather than an ambition.",
              "Installé en 1995. Le pilier d’Ashoka est une mémoire de la colonne maurya — un fût, un chapiteau, un animal d’État — traduit par une main d’Odisha pour un site au Japon. C’est l’œuvre qui fit du voyage de l’atelier un fait.",
              "Aufgestellt 1995. Die Ashoka-Säule ist eine Erinnerung an die mauryanische Säule — Schaft, Kapitell, ein Tier des Staates — von einer odishanischen Hand für einen Ort in Japan übertragen. Mit diesem Werk wurde die Reise des Ateliers Tatsache.",
              "1995年に設置。アショーカの石柱は、マウリヤの円柱の記憶です。軸、柱頭、国家の獣を、オディシャの手が日本の敷地のために訳しました。工房の海外への旅を、志ではなく事実にした仕事です。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Pillar and capital", "Pilier et chapiteau", "Säule und Kapitell", "石柱と柱頭"),
            S("Japan", "Japon", "Japan", "日本"),
            "pillar", "1995", "tall"),
        new("heritage-gate-odisha", "architecture",
            S("Largest Stone Heritage Gate, Odisha", "La plus grande porte patrimoniale en pierre, Odisha", "Größtes steinernes Erbe-Tor, Odisha", "オディシャ最大の石の遺産門"),
            S("A heritage gateway associated with the atelier’s Odishan practice, described here as the largest stone heritage gate of that body of work. A gate is a threshold: it has to carry sculpture and still be a door that a town can pass.",
              "Un portail patrimonial lié à la pratique odishan de l’atelier, décrit ici comme la plus grande porte patrimoniale en pierre de cet ensemble. Une porte est un seuil : elle doit porter la sculpture et rester un passage.",
              "Ein Erbe-Tor aus der odishanischen Praxis des Ateliers, hier als das größte steinerne Erbe-Tor dieses Werkzusammenhangs beschrieben. Ein Tor ist eine Schwelle: es muss Skulptur tragen und doch eine Tür bleiben.",
              "工房のオディシャでの実践に連なる遺産の門。この一連の仕事のなかで最大の石の遺産門として記します。門は閾です。彫刻を担い、なお町が通れる扉でなければなりません。"),
            S("Dressed sandstone", "Grès appareillé", "Bearbeiteter Sandstein", "化粧砂岩"),
            "Khandolite",
            S("Monumental gateway", "Portail monumental", "Monumentales Tor", "記念碑的な門"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "gate", "—", "wide"),
        new("jagannath-panel", "idols",
            S("Jagannath Panel", "Panneau de Jagannath", "Jagannath-Tafel", "ジャガンナートのパネル"),
            S("A devotional panel of Jagannath, carved in the visual language of Puri rather than as a generic icon. The face is a discipline of a few essential marks.",
              "Un panneau de dévotion de Jagannath, taillé dans le langage visuel de Puri, non comme une icône générique. Le visage est une discipline de quelques signes essentiels.",
              "Eine Andachtstafel Jagannaths, gehauen in der Bildsprache Puris, nicht als allgemeine Ikone. Das Gesicht ist eine Disziplin weniger wesentlicher Zeichen.",
              "プリーの視覚言語で刻むジャガンナートの礼拝パネル。一般的な偶像ではありません。顔は、わずかな本質の印の修練です。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Devotional panel", "Panneau de dévotion", "Andachtstafel", "礼拝パネル"),
            S("Puri tradition, Odisha", "Tradition de Puri, Odisha", "Puri-Tradition, Odisha", "プリーの伝統、オディシャ"),
            "lotus", "—", "regular"),
        new("ganesha-murti", "idols",
            S("Ganesha Murti", "Murti de Ganesha", "Ganesha-Murti", "ガネーシャ像"),
            S("Ganesha carved to be circumambulated: trunk, bowl, and the calm of the remover of obstacles, readable from more than one side.",
              "Un Ganesha taillé pour être circumambulé : trompe, bol, et le calme de celui qui ôte les obstacles, lisible de plus d’un côté.",
              "Ein Ganesha zum Umwandeln gehauen: Rüssel, Schale und die Ruhe dessen, der Hindernisse nimmt, von mehr als einer Seite lesbar.",
              "右繞できるように刻むガネーシャ。鼻、鉢、障害を除く者の静けさが、一面からだけでは読めません。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Image in the round", "Image en ronde-bosse", "Rundbild", "丸彫り"),
            S("Atelier, Odisha", "Atelier, Odisha", "Atelier, Odisha", "工房、オディシャ"),
            "murti", "—", "regular"),
        new("ramayana-mural", "murals",
            S("Ramayana Mural", "Murale du Ramayana", "Ramayana-Wandbild", "ラーマーヤナの壁画"),
            S("A narrative wall: episodes set in a frieze so that a visitor reads the epic as a walk, not as a caption.",
              "Un mur narratif : des épisodes en frise, pour que le visiteur lise l’épopée en marchant, non dans une légende.",
              "Eine erzählende Wand: Episoden im Fries, sodass der Besucher das Epos im Gehen liest, nicht in einer Bildunterschrift.",
              "物語の壁。フリーズに場面を置き、訪れる人が叙事詩を歩きながら読みます。"),
            S("Sandstone relief", "Relief de grès", "Sandsteinrelief", "砂岩の浮彫"),
            "Sandstone",
            S("Narrative frieze", "Frise narrative", "Erzählfries", "物語のフリーズ"),
            S("Temple wall, India", "Mur de temple, Inde", "Tempelwand, Indien", "インドの寺院の壁"),
            "frieze", "—", "wide"),
        new("govardhana", "idols",
            S("Krishna Govardhana", "Krishna Govardhana", "Krishna Govardhana", "ゴーヴァルダナのクリシュナ"),
            S("Krishna lifting the mountain: a problem of weight made visible. The mountain has to feel held, and the body has to remain a dancer’s body.",
              "Krishna soulevant la montagne : un problème de poids rendu visible. La montagne doit sembler portée, et le corps rester celui d’un danseur.",
              "Krishna hebt den Berg: ein Problem des Gewichts, sichtbar gemacht. Der Berg muss gehalten wirken, der Körper der eines Tänzers bleiben.",
              "山を掲げるクリシュナ。重さを目に見える問題にします。山は支えられ、身体は踊る者の身体のままです。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Figural sculpture", "Sculpture figurée", "Figürliche Skulptur", "人物彫刻"),
            S("Atelier, Odisha", "Atelier, Odisha", "Atelier, Odisha", "工房、オディシャ"),
            "kalasha", "—", "tall"),
        new("konark-wheel-relief", "temple",
            S("Konark Wheel Relief", "Relief de roue de Konark", "Konark-Rad-Relief", "コナーラクの車輪"),
            S("A study in the Konark tradition: the wheel as cosmos and as architecture, carved with the patience of a spoke-by-spoke geometry.",
              "Une étude dans la tradition de Konark : la roue comme cosmos et comme architecture, taillée avec la patience d’une géométrie rayon par rayon.",
              "Eine Studie in der Konark-Tradition: das Rad als Kosmos und als Architektur, gehauen mit der Geduld einer Speiche-für-Speiche-Geometrie.",
              "コナーラクの伝統による習作。車輪は宇宙であり建築です。輻一本ずつの幾何を、忍耐で刻みます。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Khandolite",
            S("Architectural relief", "Relief d’architecture", "Architekturrelief", "建築浮彫"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "wheel", "—", "regular"),
        new("narrative-capital", "architecture",
            S("Narrative Pillar Capital", "Chapiteau narratif", "Erzählendes Kapitell", "物語の柱頭"),
            S("A capital that carries a story as well as a load. The carving stops where the structure would be weakened.",
              "Un chapiteau qui porte un récit autant qu’une charge. La taille s’arrête là où la structure serait affaiblie.",
              "Ein Kapitell, das eine Geschichte trägt und eine Last. Die Arbeit endet, wo die Struktur geschwächt würde.",
              "物語と荷重を同時に担う柱頭。構造が弱るところでは、彫りを止めます。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Architectural member", "Élément d’architecture", "Architekturglied", "建築部材"),
            S("Temple project, India", "Projet de temple, Inde", "Tempelprojekt, Indien", "インドの寺院"),
            "pillar", "—", "regular")
    ];

    public static readonly IReadOnlyList<Award> Awards =
    [
        new("odisha-state-1990", "1990",
            S("Odisha State Award", "Prix de l’État d’Odisha", "Staatspreis Odisha", "オディシャ州賞"),
            S("State Best Designing Award, 1990. The first major public recognition of design as well as carving.",
              "State Best Designing Award, 1990. Première grande reconnaissance publique du dessin autant que de la taille.",
              "State Best Designing Award, 1990. Die erste große öffentliche Anerkennung von Entwurf und Steinarbeit.",
              "1990年、州最優秀デザイン賞。彫りとともに、設計が公に認められた最初の大きな顕彰。"),
            "lotus"),
        new("lalit-kala-1997", "1997",
            S("Lalit Kala Academy Award", "Prix de la Lalit Kala Academy", "Lalit-Kala-Academy-Preis", "ラリット・カラ・アカデミー賞"),
            S("Awarded in 1997, in association with the Lalit Kala Akademi.",
              "Décerné en 1997, en lien avec la Lalit Kala Akademi.",
              "Verliehen 1997, in Verbindung mit der Lalit Kala Akademi.",
              "1997年。ラリット・カラ・アカデミーに連なる賞。"),
            "kalasha"),
        new("national-award-2005", "2005",
            S("National Award for Master Craftsperson", "Prix national du maître artisan", "Nationalpreis für Meisterhandwerk", "マスター・クラフツパーソン国家賞"),
            S("Conferred in 2005 by the Government of India. This is the honour named when the atelier says National Awardee.",
              "Conféré en 2005 par le gouvernement de l’Inde. C’est l’honneur nommé lorsque l’atelier dit lauréat national.",
              "2005 von der Regierung Indiens verliehen. Diese Ehrung ist gemeint, wenn das Atelier Nationalpreisträger sagt.",
              "2005年、インド政府が授与。工房がナショナル・アワーディーと言うとき、この栄誉を指します。"),
            "temple"),
        new("stona", "—",
            S("STONA Awards", "Prix STONA", "STONA Awards", "ストーナ賞"),
            S("Recognition within the stone industry’s own gathering, STONA.",
              "Reconnaissance dans le rassemblement de l’industrie de la pierre, STONA.",
              "Anerkennung im eigenen Treffen der Steinindustrie, STONA.",
              "石材産業の集い、ストーナにおける顕彰。"),
            "pillar"),
        new("guru-samrat", "—",
            S("Guru Samrat Award", "Prix Guru Samrat", "Guru-Samrat-Preis", "グル・サムラート賞"),
            S("An honour that names the teacher, not only the carver.",
              "Un honneur qui nomme le professeur, non seulement le tailleur.",
              "Eine Ehrung, die den Lehrer nennt, nicht nur den Steinmetz.",
              "彫り手だけでなく、師を名指す栄誉。"),
            "conch"),
        new("nitya-nutan", "—",
            S("Nitya Nutan Samman", "Nitya Nutan Samman", "Nitya Nutan Samman", "ニティヤ・ヌタン・サンマン"),
            S("A samman recognising a practice that stays both rooted and renewed.",
              "Un samman pour une pratique à la fois enracinée et renouvelée.",
              "Ein Samman für eine Praxis, die verwurzelt und erneuert zugleich bleibt.",
              "根を保ちながら新たにあり続ける実践へのサンマン。"),
            "peacock"),
        new("singapore", "—",
            S("International recognition, Singapore", "Reconnaissance internationale, Singapour", "Internationale Anerkennung, Singapur", "シンガポールでの国際的評価"),
            S("Recognition connected with the atelier’s work for temple shrines in Singapore.",
              "Reconnaissance liée au travail de l’atelier pour les sanctuaires de Singapour.",
              "Anerkennung im Zusammenhang mit der Arbeit des Ateliers für Tempelschreine in Singapur.",
              "シンガポールの寺院祠堂に関わる仕事への評価。"),
            "gate"),
        new("certificates", "—",
            S("Certificates of appreciation", "Certificats d’appréciation", "Anerkennungsurkunden", "感謝状"),
            S("A body of appreciation certificates from institutions and patrons, held in the emporium archive.",
              "Un ensemble de certificats d’appréciation d’institutions et de commanditaires, conservé aux archives de l’emporium.",
              "Eine Reihe von Anerkennungsurkunden von Institutionen und Auftraggebern, im Archiv des Emporiums.",
              "機関とパトロンからの感謝状。エンポリアムのアーカイブに保管。"),
            "frieze")
    ];
}
