namespace MahapatraArts.Services;

public static class ContentWorks
{
    private static LStr S(string en, string fr, string de, string ja) => new(en, fr, de, ja);

    public static readonly IReadOnlyList<Work> Works =
    [
        new("viswaroop-darsan", "rare",
            S("Viswaroop Darsan", "Viswaroop Darsan", "Viswaroop Darsan", "ヴィシュワループ・ダルシャン"),
            S("A vision of the cosmic form: many attributes held in one body of stone. The atelier approaches Viswaroop as a test of order — the terror and the grace must be legible at once, and the block must not break into anecdote. Multi-coloured patchwork is used where colour itself is part of the theology of the image.",
              "Une vision de la forme cosmique : de nombreux attributs tenus dans un seul corps de pierre. L’atelier traite le Viswaroop comme une épreuve d’ordre — la terreur et la grâce doivent être lisibles ensemble. Le patchwork multicolore intervient lorsque la couleur appartient à la théologie de l’image.",
              "Eine Vision der kosmischen Form: viele Attribute in einem Körper aus Stein. Das Atelier behandelt Viswaroop als eine Probe der Ordnung — Schrecken und Gnade müssen zugleich lesbar sein. Mehrfarbiges Patchwork tritt ein, wo Farbe selbst zur Theologie des Bildes gehört.",
              "宇宙の姿の顕現。多くの持物を、一つの石の身体に保つ。工房はヴィシュワループを、秩序の試練として扱います。畏れと慈悲が同時に読め、石が逸話に崩れないこと。色そのものが像の神学に属するとき、多色のパッチワークを用います。"),
            S("Sandstone with multi-coloured stone patchwork", "Grès et patchwork de pierres multicolores", "Sandstein mit mehrfarbigem Steinpatchwork", "砂岩と多色石のパッチワーク"),
            "Khandolite",
            S("Monumental relief, architectural scale", "Relief monumental, échelle d’architecture", "Monumentales Relief, architektonischer Maßstab", "記念碑的な浮彫、建築の規模"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "peacock", "—", "tall"),
        new("dasavatara", "temple",
            S("Dasavatara Sculpture", "Sculpture du Dasavatara", "Dasavatara-Skulptur", "ダシャーヴァターラ"),
            S("The ten avatars told as a single sculptural argument rather than ten disconnected icons. The sequence has to be read by a devotee walking, so the rhythm of the stone matters as much as any one figure.",
              "Les dix avatars racontés comme un seul argument sculpté, non comme dix icônes séparées. La séquence se lit en marchant : le rythme de la pierre compte autant que chaque figure.",
              "Die zehn Avatare als ein einziges skulpturales Argument, nicht als zehn getrennte Ikonen. Die Folge wird im Gehen gelesen: der Rhythmus des Steins zählt so viel wie jede Figur.",
              "十の化身を、ばらばらの偶像ではなく、一つの彫刻の論として語る。歩いて読む順であるため、どの像よりも石のリズムが大切です。"),
            S("Dressed sandstone", "Grès appareillé", "Bearbeiteter Sandstein", "化粧砂岩"),
            "Sandstone",
            S("Narrative sculpture, temple scale", "Sculpture narrative, échelle de temple", "Erzählende Skulptur, Tempelmaß", "物語彫刻、寺院の規模"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "wheel", "—", "tall"),
        new("seven-temple-shrines-singapore", "international",
            S("Seven Temple Shrines, Singapore", "Sept sanctuaires, Singapour", "Sieben Tempelschreine, Singapur", "シンガポールの七つの祠堂"),
            S("An ensemble of seven shrines prepared in the Odishan temple tradition and installed in Singapore. The work had to travel: each shrine cut so that it could be crated, read on arrival, and still belong to one ritual family.",
              "Un ensemble de sept sanctuaires préparé dans la tradition des temples de l’Odisha et installé à Singapour. L’œuvre devait voyager : chaque sanctuaire taillé pour la caisse, lisible à l’arrivée, et toujours d’une même famille rituelle.",
              "Ein Ensemble von sieben Schreinen in der odishanischen Tempeltradition, aufgestellt in Singapur. Die Arbeit musste reisen: jeder Schrein so gehauen, dass er verpackt werden konnte und bei der Ankunft noch zu einer rituellen Familie gehörte.",
              "オディシャの寺院伝統で準備し、シンガポールに設置した七つの祠堂。仕事は旅をしなければなりません。それぞれを梱包でき、着いたときに読め、なお一つの祭祀の家族に属するように刻みます。"),
            S("Granite and sandstone", "Granit et grès", "Granit und Sandstein", "花崗岩と砂岩"),
            "Granite",
            S("Seven-shrine ensemble", "Ensemble de sept sanctuaires", "Ensemble von sieben Schreinen", "七祠堂の一組"),
            S("Singapore", "Singapour", "Singapur", "シンガポール"),
            "temple", "—", "wide"),
        new("perumal-mandapam", "architecture",
            S("Perumal Mandapam", "Perumal Mandapam", "Perumal Mandapam", "ペルマル・マンダパム"),
            S("A mandapam is a pillared hall, not an ornament applied afterwards. Perumal Mandapam is approached as architecture: load, rhythm of columns, and the sculpture that the hall is strong enough to carry.",
              "Un mandapam est une salle à piliers, non un ornement ajouté ensuite. Perumal Mandapam est abordé comme architecture : la charge, le rythme des colonnes, et la sculpture que la salle est assez forte pour porter.",
              "Ein Mandapam ist eine Pfeilerhalle, kein nachträglich aufgesetzter Schmuck. Perumal Mandapam wird als Architektur behandelt: Last, Rhythmus der Stützen und die Skulptur, die die Halle zu tragen vermag.",
              "マンダパムは柱の間であり、後から足す装飾ではありません。ペルマル・マンダパムは建築として扱います。荷重、柱のリズム、そしてその間が担える彫刻。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Pillared hall, architectural", "Salle à piliers, architecture", "Pfeilerhalle, architektonisch", "柱間、建築"),
            S("India", "Inde", "Indien", "インド"),
            "pillar", "—", "wide"),
        new("ashokan-pillar-japan", "international",
            S("Ashokan Pillar, Japan", "Pilier d’Ashoka, Japon", "Ashoka-Säule, Japan", "日本のアショーカ石柱"),
            S("Installed in 1995. The Ashokan pillar is a memory of the Mauryan column — a shaft, a capital, an animal of state — translated by an Odishan hand for a site in Japan. It is the work that first made the atelier’s journey abroad a fact rather than an ambition.",
              "Installé en 1995. Le pilier d’Ashoka est une mémoire de la colonne maurya — un fût, un chapiteau, un animal d’État — traduit par une main d’Odisha pour un site au Japon. C’est l’œuvre qui fit du voyage de l’atelier un fait.",
              "Aufgestellt 1995. Die Ashoka-Säule ist eine Erinnerung an die mauryanische Säule — Schaft, Kapitell, ein Tier des Staates — von einer odishanischen Hand für einen Ort in Japan übertragen. Mit diesem Werk wurde die Reise des Ateliers Tatsache.",
              "1995年に設置。アショーカの石柱は、マウリヤの円柱の記憶です。軸、柱頭、国家の獣を、オディシャの手が日本の敷地のために訳しました。工房の海外への旅を、志ではなく事実にした仕事です。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Pillar and capital", "Pilier et chapiteau", "Säule und Kapitell", "石柱と柱頭"),
            S("Japan", "Japon", "Japan", "日本"),
            "pillar", "1995", "tall"),
        new("heritage-gate-odisha", "architecture",
            S("Largest Stone Heritage Gate, Odisha", "La plus grande porte patrimoniale en pierre, Odisha", "Größtes steinernes Erbe-Tor, Odisha", "オディシャ最大の石の遺産門"),
            S("A heritage gateway associated with the atelier’s Odishan practice, described here as the largest stone heritage gate of that body of work. A gate is a threshold: it has to carry sculpture and still be a door that a town can pass.",
              "Un portail patrimonial lié à la pratique odishan de l’atelier, décrit ici comme la plus grande porte patrimoniale en pierre de cet ensemble. Une porte est un seuil : elle doit porter la sculpture et rester un passage.",
              "Ein Erbe-Tor aus der odishanischen Praxis des Ateliers, hier als das größte steinerne Erbe-Tor dieses Werkzusammenhangs beschrieben. Ein Tor ist eine Schwelle: es muss Skulptur tragen und doch eine Tür bleiben.",
              "工房のオディシャでの実践に連なる遺産の門。この一連の仕事のなかで最大の石の遺産門として記します。門は閾です。彫刻を担い、なお町が通れる扉でなければなりません。"),
            S("Dressed sandstone", "Grès appareillé", "Bearbeiteter Sandstein", "化粧砂岩"),
            "Khandolite",
            S("Monumental gateway", "Portail monumental", "Monumentales Tor", "記念碑的な門"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "gate", "—", "wide"),
        new("jagannath-panel", "idols",
            S("Jagannath Panel", "Panneau de Jagannath", "Jagannath-Tafel", "ジャガンナートのパネル"),
            S("A devotional panel of Jagannath, carved in the visual language of Puri rather than as a generic icon. The face is a discipline of a few essential marks.",
              "Un panneau de dévotion de Jagannath, taillé dans le langage visuel de Puri, non comme une icône générique. Le visage est une discipline de quelques signes essentiels.",
              "Eine Andachtstafel Jagannaths, gehauen in der Bildsprache Puris, nicht als allgemeine Ikone. Das Gesicht ist eine Disziplin weniger wesentlicher Zeichen.",
              "プリーの視覚言語で刻むジャガンナートの礼拝パネル。一般的な偶像ではありません。顔は、わずかな本質の印の修練です。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Devotional panel", "Panneau de dévotion", "Andachtstafel", "礼拝パネル"),
            S("Puri tradition, Odisha", "Tradition de Puri, Odisha", "Puri-Tradition, Odisha", "プリーの伝統、オディシャ"),
            "lotus", "—", "regular"),
        new("ganesha-murti", "idols",
            S("Ganesha Murti", "Murti de Ganesha", "Ganesha-Murti", "ガネーシャ像"),
            S("Ganesha carved to be circumambulated: trunk, bowl, and the calm of the remover of obstacles, readable from more than one side.",
              "Un Ganesha taillé pour être circumambulé : trompe, bol, et le calme de celui qui ôte les obstacles, lisible de plus d’un côté.",
              "Ein Ganesha zum Umwandeln gehauen: Rüssel, Schale und die Ruhe dessen, der Hindernisse nimmt, von mehr als einer Seite lesbar.",
              "右繞できるように刻むガネーシャ。鼻、鉢、障害を除く者の静けさが、一面からだけでは読めません。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Image in the round", "Image en ronde-bosse", "Rundbild", "丸彫り"),
            S("Atelier, Odisha", "Atelier, Odisha", "Atelier, Odisha", "工房、オディシャ"),
            "murti", "—", "regular"),
        new("ramayana-mural", "murals",
            S("Ramayana Mural", "Murale du Ramayana", "Ramayana-Wandbild", "ラーマーヤナの壁画"),
            S("A narrative wall: episodes set in a frieze so that a visitor reads the epic as a walk, not as a caption.",
              "Un mur narratif : des épisodes en frise, pour que le visiteur lise l’épopée en marchant, non dans une légende.",
              "Eine erzählende Wand: Episoden im Fries, sodass der Besucher das Epos im Gehen liest, nicht in einer Bildunterschrift.",
              "物語の壁。フリーズに場面を置き、訪れる人が叙事詩を歩きながら読みます。"),
            S("Sandstone relief", "Relief de grès", "Sandsteinrelief", "砂岩の浮彫"),
            "Sandstone",
            S("Narrative frieze", "Frise narrative", "Erzählfries", "物語のフリーズ"),
            S("Temple wall, India", "Mur de temple, Inde", "Tempelwand, Indien", "インドの寺院の壁"),
            "frieze", "—", "wide"),
        new("govardhana", "idols",
            S("Krishna Govardhana", "Krishna Govardhana", "Krishna Govardhana", "ゴーヴァルダナのクリシュナ"),
            S("Krishna lifting the mountain: a problem of weight made visible. The mountain has to feel held, and the body has to remain a dancer’s body.",
              "Krishna soulevant la montagne : un problème de poids rendu visible. La montagne doit sembler portée, et le corps rester celui d’un danseur.",
              "Krishna hebt den Berg: ein Problem des Gewichts, sichtbar gemacht. Der Berg muss gehalten wirken, der Körper der eines Tänzers bleiben.",
              "山を掲げるクリシュナ。重さを目に見える問題にします。山は支えられ、身体は踊る者の身体のままです。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Figural sculpture", "Sculpture figurée", "Figürliche Skulptur", "人物彫刻"),
            S("Atelier, Odisha", "Atelier, Odisha", "Atelier, Odisha", "工房、オディシャ"),
            "kalasha", "—", "tall"),
        new("konark-wheel-relief", "temple",
            S("Konark Wheel Relief", "Relief de roue de Konark", "Konark-Rad-Relief", "コナーラクの車輪"),
            S("A study in the Konark tradition: the wheel as cosmos and as architecture, carved with the patience of a spoke-by-spoke geometry.",
              "Une étude dans la tradition de Konark : la roue comme cosmos et comme architecture, taillée avec la patience d’une géométrie rayon par rayon.",
              "Eine Studie in der Konark-Tradition: das Rad als Kosmos und als Architektur, gehauen mit der Geduld einer Speiche-für-Speiche-Geometrie.",
              "コナーラクの伝統による習作。車輪は宇宙であり建築です。輻一本ずつの幾何を、忍耐で刻みます。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Khandolite",
            S("Architectural relief", "Relief d’architecture", "Architekturrelief", "建築浮彫"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "wheel", "—", "regular"),
        new("narrative-capital", "architecture",
            S("Narrative Pillar Capital", "Chapiteau narratif", "Erzählendes Kapitell", "物語の柱頭"),
            S("A capital that carries a story as well as a load. The carving stops where the structure would be weakened.",
              "Un chapiteau qui porte un récit autant qu’une charge. La taille s’arrête là où la structure serait affaiblie.",
              "Ein Kapitell, das eine Geschichte trägt und eine Last. Die Arbeit endet, wo die Struktur geschwächt würde.",
              "物語と荷重を同時に担う柱頭。構造が弱るところでは、彫りを止めます。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Architectural member", "Élément d’architecture", "Architekturglied", "建築部材"),
            S("Temple project, India", "Projet de temple, Inde", "Tempelprojekt, Indien", "インドの寺院"),
            "pillar", "—", "regular")
    ];

    public static readonly IReadOnlyList<Award> Awards =
    [
        new("odisha-state-1990", "1990",
            S("Odisha State Award", "Prix de l’État d’Odisha", "Staatspreis Odisha", "オディシャ州賞"),
            S("State Best Designing Award, 1990. The first major public recognition of design as well as carving.",
              "State Best Designing Award, 1990. Première grande reconnaissance publique du dessin autant que de la taille.",
              "State Best Designing Award, 1990. Die erste große öffentliche Anerkennung von Entwurf und Steinarbeit.",
              "1990年、州最優秀デザイン賞。彫りとともに、設計が公に認められた最初の大きな顕彰。"),
            "lotus"),
        new("lalit-kala-1997", "1997",
            S("Lalit Kala Academy Award", "Prix de la Lalit Kala Academy", "Lalit-Kala-Academy-Preis", "ラリット・カラ・アカデミー賞"),
            S("Awarded in 1997, in association with the Lalit Kala Akademi.",
              "Décerné en 1997, en lien avec la Lalit Kala Akademi.",
              "Verliehen 1997, in Verbindung mit der Lalit Kala Akademi.",
              "1997年。ラリット・カラ・アカデミーに連なる賞。"),
            "kalasha"),
        new("national-award-2005", "2005",
            S("National Award for Master Craftsperson", "Prix national du maître artisan", "Nationalpreis für Meisterhandwerk", "マスター・クラフツパーソン国家賞"),
            S("Conferred in 2005 by the Government of India. This is the honour named when the atelier says National Awardee.",
              "Conféré en 2005 par le gouvernement de l’Inde. C’est l’honneur nommé lorsque l’atelier dit lauréat national.",
              "2005 von der Regierung Indiens verliehen. Diese Ehrung ist gemeint, wenn das Atelier Nationalpreisträger sagt.",
              "2005年、インド政府が授与。工房がナショナル・アワーディーと言うとき、この栄誉を指します。"),
            "temple"),
        new("stona", "—",
            S("STONA Awards", "Prix STONA", "STONA Awards", "ストーナ賞"),
            S("Recognition within the stone industry’s own gathering, STONA.",
              "Reconnaissance dans le rassemblement de l’industrie de la pierre, STONA.",
              "Anerkennung im eigenen Treffen der Steinindustrie, STONA.",
              "石材産業の集い、ストーナにおける顕彰。"),
            "pillar"),
        new("guru-samrat", "—",
            S("Guru Samrat Award", "Prix Guru Samrat", "Guru-Samrat-Preis", "グル・サムラート賞"),
            S("An honour that names the teacher, not only the carver.",
              "Un honneur qui nomme le professeur, non seulement le tailleur.",
              "Eine Ehrung, die den Lehrer nennt, nicht nur den Steinmetz.",
              "彫り手だけでなく、師を名指す栄誉。"),
            "conch"),
        new("nitya-nutan", "—",
            S("Nitya Nutan Samman", "Nitya Nutan Samman", "Nitya Nutan Samman", "ニティヤ・ヌタン・サンマン"),
            S("A samman recognising a practice that stays both rooted and renewed.",
              "Un samman pour une pratique à la fois enracinée et renouvelée.",
              "Ein Samman für eine Praxis, die verwurzelt und erneuert zugleich bleibt.",
              "根を保ちながら新たにあり続ける実践へのサンマン。"),
            "peacock"),
        new("singapore", "—",
            S("International recognition, Singapore", "Reconnaissance internationale, Singapour", "Internationale Anerkennung, Singapur", "シンガポールでの国際的評価"),
            S("Recognition connected with the atelier’s work for temple shrines in Singapore.",
              "Reconnaissance liée au travail de l’atelier pour les sanctuaires de Singapour.",
              "Anerkennung im Zusammenhang mit der Arbeit des Ateliers für Tempelschreine in Singapur.",
              "シンガポールの寺院祠堂に関わる仕事への評価。"),
            "gate"),
        new("certificates", "—",
            S("Certificates of appreciation", "Certificats d’appréciation", "Anerkennungsurkunden", "感謝状"),
            S("A body of appreciation certificates from institutions and patrons, held in the emporium archive.",
              "Un ensemble de certificats d’appréciation d’institutions et de commanditaires, conservé aux archives de l’emporium.",
              "Eine Reihe von Anerkennungsurkunden von Institutionen und Auftraggebern, im Archiv des Emporiums.",
              "機関とパトロンからの感謝状。エンポリアムのアーカイブに保管。"),
            "frieze")
    ];
}
