namespace MahapatraArts.Services;

public static class ContentWorks
{
    private static LStr S(string en, string fr, string de, string ja) => new(en, fr, de, ja);

    public static readonly IReadOnlyList<Work> Works =
    [
        new("saraswati-sastra", "idols",
            S("Saraswati, Sastra University", "Saraswati, université Sastra", "Saraswati, Sastra-Universität", "サストラ大学のサラスヴァティー"),
            S("Ten feet high. A white Saraswati installed at Sastra University, Tamil Nadu, by Guru Ramakanta. The goddess sits with the veena inside a red stone shrine, garlanded on the day of installation.",
              "Dix pieds. Une Saraswati blanche installée à l’université Sastra, au Tamil Nadu, par Guru Ramakanta. La déesse est assise avec la vînâ dans un sanctuaire de pierre rouge, enguirlandée le jour de l’installation.",
              "Zehn Fuß. Eine weiße Saraswati, von Guru Ramakanta an der Sastra-Universität in Tamil Nadu aufgestellt. Die Göttin sitzt mit der Vina in einem Schrein aus rotem Stein, am Tag der Aufstellung bekränzt.",
              "高さ10フィート。タミル・ナードゥのサストラ大学にグル・ラマカンタが設置した白いサラスヴァティー。赤い石の祠のなかでヴィーナーを抱え、設置の日に花綱がかけられています。"),
            S("White stone and red stone", "Pierre blanche et pierre rouge", "Weißer und roter Stein", "白と赤の石"),
            "Stone",
            S("10 ft", "10 pieds", "10 Fuß", "10フィート"),
            S("Sastra University, Tamil Nadu, India", "Université Sastra, Tamil Nadu, Inde", "Sastra-Universität, Tamil Nadu, Indien", "インド、タミル・ナードゥ、サストラ大学"),
            "murti", "—", "tall"),
        new("shiva-buddha", "idols",
            S("Shiva and Buddha", "Shiva et Bouddha", "Shiva und Buddha", "シヴァと仏陀"),
            S("A Shiva and a Buddha made by Guru Ramakanta Mahapatra. Shiva is shown seated with the trident, still in the clay of the model, and the Buddha sits in a stone niche of horizontal courses.",
              "Un Shiva et un Bouddha de Guru Ramakanta Mahapatra. Shiva est assis avec le trident, encore dans l’argile du modèle, et le Bouddha siège dans une niche de pierre aux assises horizontales.",
              "Ein Shiva und ein Buddha von Guru Ramakanta Mahapatra. Shiva sitzt mit dem Dreizack, noch im Ton des Modells, und der Buddha sitzt in einer Steinnische aus waagerechten Schichten.",
              "グル・ラマカンタ・マハパトラのシヴァと仏陀。シヴァは三叉戟を持ち、まだ原型の粘土のまま坐し、仏陀は横目地の石の龕に坐します。"),
            S("Clay model and stone", "Modèle d’argile et pierre", "Tonmodell und Stein", "粘土の原型と石"),
            "Stone",
            S("Ensemble", "Ensemble", "Ensemble", "一組"),
            S("Made by Guru Ramakanta Mahapatra", "Œuvre de Guru Ramakanta Mahapatra", "Von Guru Ramakanta Mahapatra", "グル・ラマカンタ・マハパトラの作"),
            "murti", "—", "tall"),
        new("vedabyasa-rourkela", "idols",
            S("Rishi Vedabyasa and Ganesh, Rourkela", "Rishi Vedabyasa et Ganesh, Rourkela", "Rishi Vedabyasa und Ganesh, Rourkela", "ルールケラのリシ・ヴェーダヴィヤーサとガネーシャ"),
            S("A 10-foot Rishi Vedabyasa and a 7-foot-6-inch Lord Ganesh, made by Guru Ramakanta for Vedabyasa Park, Rourkela, Odisha. The sage sits in meditation beside the elephant-headed lord.",
              "Un Rishi Vedabyasa de 10 pieds et un Seigneur Ganesh de 7 pieds 6 pouces, faits par Guru Ramakanta pour le parc Vedabyasa, à Rourkela, Odisha. Le sage est assis en méditation auprès du seigneur à tête d’éléphant.",
              "Ein 10 Fuß hoher Rishi Vedabyasa und ein 7 Fuß 6 Zoll hoher Herr Ganesh, von Guru Ramakanta für den Vedabyasa-Park in Rourkela, Odisha. Der Weise sitzt in Meditation neben dem elefantenköpfigen Herrn.",
              "オディシャ州ルールケラのヴェーダヴィヤーサ公園のために、グル・ラマカンタが作った高さ10フィートのリシ・ヴェーダヴィヤーサと、7フィート6インチのガネーシャ。聖者は象頭の主の傍らで瞑想に坐します。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("10 ft and 7 ft 6 in", "10 pieds et 7 pieds 6 pouces", "10 Fuß und 7 Fuß 6 Zoll", "10フィートと7フィート6インチ"),
            S("Vedabyasa Park, Rourkela, Odisha, India", "Parc Vedabyasa, Rourkela, Odisha, Inde", "Vedabyasa-Park, Rourkela, Odisha, Indien", "インド、オディシャ、ルールケラ、ヴェーダヴィヤーサ公園"),
            "murti", "—", "wide"),
        new("konark-wheel-station", "temple",
            S("Konark wheel, Bhubaneswar station", "Roue de Konark, gare de Bhubaneswar", "Konark-Rad, Bahnhof Bhubaneswar", "ブバネーシュワル駅のコナーラクの車輪"),
            S("A Konark wheel installed at Bhubaneswar Railway Station. Guru Ramakanta stands with the finished wheel at night, and the earlier photographs show the carving and the raising of the stone.",
              "Une roue de Konark installée à la gare de Bhubaneswar. Guru Ramakanta se tient auprès de la roue achevée, la nuit, et les photographies précédentes montrent la taille et le levage de la pierre.",
              "Ein Konark-Rad, am Bahnhof Bhubaneswar aufgestellt. Guru Ramakanta steht nachts am fertigen Rad, und die früheren Aufnahmen zeigen das Behauen und das Aufrichten des Steins.",
              "ブバネーシュワル駅に設置したコナーラクの車輪。夜、完成した車輪の傍らにグル・ラマカンタが立ち、先の写真は石の彫りと立ち上げを示します。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Monumental wheel", "Roue monumentale", "Monumentales Rad", "記念碑的な車輪"),
            S("Bhubaneswar Railway Station, Odisha, India", "Gare de Bhubaneswar, Odisha, Inde", "Bahnhof Bhubaneswar, Odisha, Indien", "インド、オディシャ、ブバネーシュワル駅"),
            "wheel", "—", "wide"),
        new("canara-bank-bhubaneswar", "idols",
            S("Canara Bank, Bhubaneswar", "Canara Bank, Bhubaneswar", "Canara Bank, Bhubaneswar", "ブバネーシュワルのカナラ銀行"),
            S("Statues installed by Guru Ramakanta at the Canara Bank Regional Office, Bhubaneswar: a standing goddess with folded hands, a seated Ganesh, and the figures set along the office steps.",
              "Des statues installées par Guru Ramakanta au bureau régional de la Canara Bank, à Bhubaneswar : une déesse debout aux mains jointes, un Ganesh assis, et les figures le long des marches du bureau.",
              "Statuen, die Guru Ramakanta im Regionalbüro der Canara Bank in Bhubaneswar aufgestellt hat: eine stehende Göttin mit gefalteten Händen, ein sitzender Ganesh und die Figuren an den Stufen des Büros.",
              "ブバネーシュワルのカナラ銀行地域事務所にグル・ラマカンタが設置した像。合掌して立つ女神、坐すガネーシャ、事務所の階段に並ぶ像。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Office installation", "Installation de bureau", "Aufstellung im Büro", "事務所への設置"),
            S("Canara Bank Regional Office, Bhubaneswar, India", "Bureau régional de la Canara Bank, Bhubaneswar, Inde", "Regionalbüro der Canara Bank, Bhubaneswar, Indien", "インド、ブバネーシュワル、カナラ銀行地域事務所"),
            "murti", "—", "tall"),
        new("siddhi-vinayak-delhi", "idols",
            S("Siddhi Vinayak, Delhi", "Siddhi Vinayak, Delhi", "Siddhi Vinayak, Delhi", "デリーのシッディ・ヴィナーヤカ"),
            S("Fifteen feet high. Siddhi Vinayak, carved at Delhi by Ramakanta with his students. The brochure calls it one of the marvellous stone-carving works: a deep shrine of Ganesh, with the disciples on the scaffolding beside it.",
              "Quinze pieds. Siddhi Vinayak, taillé à Delhi par Ramakanta et ses élèves. La brochure le nomme parmi les travaux de taille les plus admirables : un profond sanctuaire de Ganesh, les disciples sur l’échafaudage à côté.",
              "Fünfzehn Fuß. Siddhi Vinayak, in Delhi von Ramakanta mit seinen Schülern gehauen. Die Broschüre nennt es eine der bewundernswerten Steinmetzarbeiten: ein tiefer Ganesha-Schrein, die Schüler auf dem Gerüst daneben.",
              "高さ15フィート。デリーでラマカンタが弟子たちと刻んだシッディ・ヴィナーヤカ。案内は見事な石彫の一つと記します。深いガネーシャの祠と、その脇の足場にいる弟子たち。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("15 ft", "15 pieds", "15 Fuß", "15フィート"),
            S("Delhi, India", "Delhi, Inde", "Delhi, Indien", "インド、デリー"),
            "murti", "—", "tall"),
        new("apsaras-mit-pune", "idols",
            S("Apsaras, MIT Pune", "Apsaras, MIT Pune", "Apsaras, MIT Pune", "プネーMITのアプサラス"),
            S("Guru Ramakanta with idols of Urvashi, Menaka, Rambha and other apsaras at the MIT campus, Pune. The dancers stand in a long row under the colonnade.",
              "Guru Ramakanta avec les idoles d’Urvashi, Menaka, Rambha et d’autres apsaras sur le campus du MIT, à Pune. Les danseuses se tiennent en longue file sous la colonnade.",
              "Guru Ramakanta mit Idolen von Urvashi, Menaka, Rambha und anderen Apsaras auf dem MIT-Campus in Pune. Die Tänzerinnen stehen in langer Reihe unter der Kolonnade.",
              "プネーのMITキャンパスで、ウルヴァシー、メーナカー、ランバーほかアプサラスの像と並ぶグル・ラマカンタ。踊り手たちは列柱の下に長く並びます。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("A row of dancers", "Une file de danseuses", "Eine Reihe Tänzerinnen", "踊り手の列"),
            S("MIT campus, Pune, India", "Campus du MIT, Pune, Inde", "MIT-Campus, Pune, Indien", "インド、プネー、MITキャンパス"),
            "murti", "—", "wide"),
        new("sos-village-faridabad", "idols",
            S("Pink serpentine, SOS Village", "Serpentine rose, SOS Village", "Rosa Serpentin, SOS Village", "SOSヴィレッジのピンクのサーペンティン"),
            S("Pink serpentine stone carving by Ramakanta, installed at SOS Village, Faridabad. One photograph shows the finished goddess in her circle; the other shows the same image still in the pale stone of the block.",
              "Une taille en serpentine rose de Ramakanta, installée au SOS Village, à Faridabad. Une photographie montre la déesse achevée dans son cercle ; l’autre, la même image encore dans la pierre pâle du bloc.",
              "Eine Arbeit in rosa Serpentin von Ramakanta, im SOS Village in Faridabad aufgestellt. Eine Aufnahme zeigt die vollendete Göttin in ihrem Kreis, die andere dasselbe Bild noch im hellen Stein des Blocks.",
              "ファリダバードのSOSヴィレッジに設置した、ラマカンタのピンクのサーペンティン。一枚は円光のなかの完成した女神、もう一枚はまだ淡い石塊のままの同じ像です。"),
            S("Pink serpentine", "Serpentine rose", "Rosa Serpentin", "ピンクのサーペンティン"),
            "Pink serpentine",
            S("Installed figure", "Figure installée", "Aufgestellte Figur", "設置された像"),
            S("SOS Village, Faridabad, India", "SOS Village, Faridabad, Inde", "SOS Village, Faridabad, Indien", "インド、ファリダバード、SOSヴィレッジ"),
            "murti", "—", "tall"),
        new("ancient-text-stone", "idols",
            S("Ancient text in stone", "Le texte ancien dans la pierre", "Alter Text im Stein", "石に訳された古の文"),
            S("Ramakanta translating the concept of an ancient text into stone: a green Ganesh in a niche, a pale dancing Ganesh, a standing Ganesh with the modak, and a paired image under a tree.",
              "Ramakanta traduisant en pierre le concept d’un texte ancien : un Ganesh vert dans une niche, un Ganesh dansant pâle, un Ganesh debout avec le modak, et une image double sous un arbre.",
              "Ramakanta überträgt den Begriff eines alten Textes in Stein: ein grüner Ganesh in einer Nische, ein heller tanzender Ganesh, ein stehender Ganesh mit dem Modak und ein Doppelbild unter einem Baum.",
              "ラマカンタが古の文の概念を石に訳します。龕のなかの緑のガネーシャ、淡い踊るガネーシャ、モダカを持つ立像、木の下の対の像。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Four studies", "Quatre études", "Vier Studien", "四つの習作"),
            S("Carved by Ramakanta", "Taillé par Ramakanta", "Von Ramakanta gehauen", "ラマカンタの作"),
            "murti", "—", "tall"),
        new("kandarpa-hasti", "rare",
            S("Kandarpa Hasti", "Kandarpa Hasti", "Kandarpa Hasti", "カンダルパ・ハスティ"),
            S("Five feet high. Kandarpa Hasti, a blending of red onyx and green onyx, an innovation by Ramakanta. A green figure sits on the elephant, whose body is carved as a crowd of forms in the red stone.",
              "Cinq pieds. Kandarpa Hasti, un mélange d’onyx rouge et d’onyx vert, une innovation de Ramakanta. Une figure verte est assise sur l’éléphant, dont le corps est taillé comme une foule de formes dans la pierre rouge.",
              "Fünf Fuß. Kandarpa Hasti, eine Verbindung von rotem und grünem Onyx, eine Neuerung Ramakantas. Eine grüne Figur sitzt auf dem Elefanten, dessen Leib als eine Menge von Gestalten im roten Stein gehauen ist.",
              "高さ5フィート。赤オニキスと緑オニキスを合わせたカンダルパ・ハスティ。ラマカンタの工夫です。象の上に緑の像が坐し、象の体は赤の石のなかに多くの姿として刻まれています。"),
            S("Red onyx and green onyx", "Onyx rouge et onyx vert", "Roter und grüner Onyx", "赤と緑のオニキス"),
            "Onyx",
            S("5 ft", "5 pieds", "5 Fuß", "5フィート"),
            S("An innovation by Ramakanta", "Une innovation de Ramakanta", "Eine Neuerung Ramakantas", "ラマカンタの工夫"),
            "murti", "—", "tall"),
        new("vastu-siddhi-vinayaka", "rare",
            S("Vastu Siddhi Vinayaka", "Vastu Siddhi Vinayaka", "Vastu Siddhi Vinayaka", "ヴァーストゥ・シッディ・ヴィナーヤカ"),
            S("Sixteen feet high. Vastu Siddhi Vinayaka in multicoloured onyx patchwork, shown at an international fair, and photographed again while the piece was being installed.",
              "Seize pieds. Vastu Siddhi Vinayaka en patchwork d’onyx multicolore, présenté à une foire internationale, et photographié de nouveau pendant l’installation.",
              "Sechzehn Fuß. Vastu Siddhi Vinayaka in mehrfarbigem Onyx-Patchwork, auf einer internationalen Messe gezeigt und noch einmal während der Aufstellung fotografiert.",
              "高さ16フィート。多色オニキスのパッチワークによるヴァーストゥ・シッディ・ヴィナーヤカ。国際見本市に出品され、設置のときにも撮られています。"),
            S("Multicoloured onyx patchwork", "Patchwork d’onyx multicolore", "Mehrfarbiges Onyx-Patchwork", "多色オニキスのパッチワーク"),
            "Onyx",
            S("16 ft", "16 pieds", "16 Fuß", "16フィート"),
            S("International fair", "Foire internationale", "Internationale Messe", "国際見本市"),
            "peacock", "—", "tall"),
        new("radha-krishna-green-zed", "idols",
            S("Radha Krishna in Green Zed", "Radha Krishna en Green Zed", "Radha Krishna in Green Zed", "グリーン・ゼッドのラーダーとクリシュナ"),
            S("Ten feet high. A Radha Krishna statue carved in Green Zed by Ramakanta, with the flute, the deer, and the tree canopy cut from the same stone.",
              "Dix pieds. Une statue de Radha Krishna taillée en Green Zed par Ramakanta, avec la flûte, le cerf et le feuillage du même bloc.",
              "Zehn Fuß. Eine Radha-Krishna-Statue in Green Zed, von Ramakanta gehauen, mit Flöte, Hirsch und Laubdach aus demselben Stein.",
              "高さ10フィート。ラマカンタがグリーン・ゼッドに刻んだラーダーとクリシュナ。笛、鹿、木の葉が同じ石から出ています。"),
            S("Green Zed", "Green Zed", "Green Zed", "グリーン・ゼッド"),
            "Green Zed",
            S("10 ft", "10 pieds", "10 Fuß", "10フィート"),
            S("Carved by Ramakanta", "Taillée par Ramakanta", "Von Ramakanta gehauen", "ラマカンタの作"),
            "murti", "—", "wide"),
        new("ganesh-with-seat", "idols",
            S("Lord Ganesh with his seat", "Seigneur Ganesh et son siège", "Herr Ganesh mit seinem Sitz", "座を伴うガネーシャ"),
            S("Five and a half feet high. Lord Ganesh with his seat, carved by Ramakanta. The green figure sits in an open arch, above a dark stone pedestal.",
              "Cinq pieds et demi. Seigneur Ganesh et son siège, taillés par Ramakanta. La figure verte est dans une arche ouverte, au-dessus d’un piédestal de pierre sombre.",
              "Fünfeinhalb Fuß. Herr Ganesh mit seinem Sitz, von Ramakanta gehauen. Die grüne Figur steht in einem offenen Bogen über einem dunklen Steinsockel.",
              "高さ5.5フィート。ラマカンタが刻んだ、座を伴うガネーシャ。緑の像は開いたアーチのなかにあり、暗い石の台座の上に据わります。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("5.5 ft", "5,5 pieds", "5,5 Fuß", "5.5フィート"),
            S("Carved by Ramakanta", "Taillé par Ramakanta", "Von Ramakanta gehauen", "ラマカンタの作"),
            "murti", "—", "tall"),
        new("red-onyx-singapore", "idols",
            S("Red Onyx, Singapore", "Onyx rouge, Singapour", "Roter Onyx, Singapur", "シンガポールの赤オニキス"),
            S("Six feet high. A Red Onyx creation by Ramakanta, installed at Singapore: a seated Ganesha under a bell canopy, with the mouse at the base.",
              "Six pieds. Une création en onyx rouge de Ramakanta, installée à Singapour : un Ganesh assis sous un dais en cloche, la souris au socle.",
              "Sechs Fuß. Eine Arbeit in rotem Onyx von Ramakanta, in Singapur aufgestellt: ein sitzender Ganesha unter einem Glockendach, die Maus am Sockel.",
              "高さ6フィート。ラマカンタの赤オニキスの作をシンガポールに設置。鐘の天蓋の下に坐すガネーシャと、台座の鼠。"),
            S("Red onyx", "Onyx rouge", "Roter Onyx", "赤オニキス"),
            "Red onyx",
            S("6 ft", "6 pieds", "6 Fuß", "6フィート"),
            S("Singapore", "Singapour", "Singapur", "シンガポール"),
            "murti", "—", "tall"),
        new("shirdi-saibaba-mumbai", "idols",
            S("Shirdi Saibaba, Mumbai", "Shirdi Saibaba, Mumbai", "Shirdi Saibaba, Mumbai", "ムンバイのシールディ・サーイ・バーバー"),
            S("Eight feet high. Shirdi Saibaba, installed at Mumbai. The figure sits on rock, one hand raised, the cloth and the seat cut from the same red stone.",
              "Huit pieds. Shirdi Saibaba, installé à Mumbai. La figure est assise sur le roc, une main levée, le drapé et le siège taillés dans la même pierre rouge.",
              "Acht Fuß. Shirdi Saibaba, in Mumbai aufgestellt. Die Figur sitzt auf Fels, eine Hand erhoben, Gewand und Sitz aus demselben roten Stein.",
              "高さ8フィート。ムンバイに設置したシールディ・サーイ・バーバー。岩の上に坐し、片手を上げ、衣と座は同じ赤の石から刻まれています。"),
            S("Red stone", "Pierre rouge", "Roter Stein", "赤の石"),
            "Red stone",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Mumbai, India", "Mumbai, Inde", "Mumbai, Indien", "インド、ムンバイ"),
            "murti", "—", "tall"),
        new("parvati-nine-foot", "idols",
            S("Nine-foot Parvati", "Parvati de neuf pieds", "Neun Fuß hohe Parvati", "9フィートのパールヴァティー"),
            S("Ramakanta giving the final touch to a 9-foot Parvati idol. The unfinished aureole is still on the wall behind the figure.",
              "Ramakanta donnant la dernière main à une idole de Parvati de 9 pieds. L’auréole inachevée est encore au mur, derrière la figure.",
              "Ramakanta gibt einer 9 Fuß hohen Parvati-Figur den letzten Schliff. Der unfertige Nimbus steht noch an der Wand hinter der Figur.",
              "ラマカンタが9フィートのパールヴァティー像に仕上げを入れています。未完の光背が、像の背後の壁に残っています。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("9 ft", "9 pieds", "9 Fuß", "9フィート"),
            S("In the workshop", "Dans l’atelier", "In der Werkstatt", "工房にて"),
            "murti", "—", "tall"),
        new("veer-ganapati-fair", "idols",
            S("Veer Ganapati, trade fair", "Veer Ganapati, foire", "Veer Ganapati, Messe", "交易会のヴィーラ・ガナパティ"),
            S("Guru Ramakanta with an 8-foot Veer Ganapati at the 10th International Trade Fair. The pale stone figure stands on its own base, outdoors.",
              "Guru Ramakanta avec un Veer Ganapati de 8 pieds à la 10e foire internationale. La figure de pierre claire est sur son socle, en plein air.",
              "Guru Ramakanta mit einem 8 Fuß hohen Veer Ganapati auf der 10. Internationalen Messe. Die helle Steinfigur steht im Freien auf eigenem Sockel.",
              "第10回国際交易会で、高さ8フィートのヴィーラ・ガナパティと並ぶグル・ラマカンタ。淡い石の像は屋外の台座に立っています。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("10th International Trade Fair", "10e foire internationale", "10. Internationale Messe", "第10回国際交易会"),
            "murti", "—", "tall"),
        new("jaypee-green-resort", "temples",
            S("Jaypee Green Resort, Greater Noida", "Jaypee Green Resort, Greater Noida", "Jaypee Green Resort, Greater Noida", "グレーター・ノイダのジャイピー・グリーン・リゾート"),
            S("Ten feet high. Pink serpentine stone work installed at Jaypee Green Resort & Spa, Greater Noida: Ganesha in a tall niche, with attendants and a stepped base.",
              "Dix pieds. Un travail en serpentine rose installé au Jaypee Green Resort & Spa, Greater Noida : Ganesh dans une haute niche, avec des suivants et un socle à degrés.",
              "Zehn Fuß. Arbeit in rosa Serpentin, aufgestellt im Jaypee Green Resort & Spa, Greater Noida: Ganesha in einer hohen Nische, mit Begleitfiguren und Stufensockel.",
              "高さ10フィート。グレーター・ノイダのジャイピー・グリーン・リゾート＆スパに設置したピンクのサーペンティン。高い龕のなかのガネーシャ、侍者、段のある基壇。"),
            S("Pink serpentine", "Serpentine rose", "Rosa Serpentin", "ピンクのサーペンティン"),
            "Pink serpentine",
            S("10 ft", "10 pieds", "10 Fuß", "10フィート"),
            S("Jaypee Green Resort & Spa, Greater Noida, India", "Jaypee Green Resort & Spa, Greater Noida, Inde", "Jaypee Green Resort & Spa, Greater Noida, Indien", "インド、グレーター・ノイダ、ジャイピー・グリーン・リゾート＆スパ"),
            "murti", "—", "tall"),
        new("durga-mai-mumbai", "idols",
            S("Durga Mai, Mumbai", "Durga Mai, Mumbai", "Durga Mai, Mumbai", "ムンバイのドゥルガー・マーイ"),
            S("Nine feet high. Durga Mai was installed at FX Factory, Mumbai. The green stone holds the goddess in her circle of arms, and the later photographs show the image set outdoors.",
              "Neuf pieds. Durga Mai a été installée à la FX Factory, à Mumbai. La pierre verte tient la déesse dans son cercle de bras, et les photographies suivantes la montrent posée à l’extérieur.",
              "Neun Fuß. Durga Mai wurde in der FX Factory in Mumbai aufgestellt. Der grüne Stein hält die Göttin in ihrem Kreis von Armen, und die späteren Aufnahmen zeigen das Bild im Freien.",
              "高さ9フィート。ドゥルガー・マーイはムンバイのFXファクトリーに設置されました。緑の石が円環の腕のなかに女神を保ち、後の写真は屋外に据えられた像を示します。"),
            S("Green stone", "Pierre verte", "Grüner Stein", "緑の石"),
            "Stone",
            S("9 ft", "9 pieds", "9 Fuß", "9フィート"),
            S("FX Factory, Mumbai, India", "FX Factory, Mumbai, Inde", "FX Factory, Mumbai, Indien", "インド、ムンバイ、FXファクトリー"),
            "murti", "—", "tall"),
        new("shiva-nandi-dharmasthala", "idols",
            S("Shiva and Nandi, Dharmasthala", "Shiva et Nandi, Dharmasthala", "Shiva und Nandi, Dharmasthala", "ダルマスターラのシヴァとナンディ"),
            S("Fifteen feet high. Lord Shiva stands with Nandi, carved in Khandolite by Guru Ramakanta and installed at Dharmasthala.",
              "Quinze pieds. Le Seigneur Shiva se tient avec Nandi, taillé en khandolite par Guru Ramakanta et installé à Dharmasthala.",
              "Fünfzehn Fuß. Herr Shiva steht mit Nandi, von Guru Ramakanta in Khandolit gehauen und in Dharmasthala aufgestellt.",
              "高さ15フィート。シヴァがナンディと共に立ちます。グル・ラマカンタがカンドライトに刻み、ダルマスターラに設置しました。"),
            S("Khandolite", "Khandolite", "Khandolit", "カンドライト"),
            "Khandolite",
            S("15 ft", "15 pieds", "15 Fuß", "15フィート"),
            S("Dharmasthala, India", "Dharmasthala, Inde", "Dharmasthala, Indien", "インド、ダルマスターラ"),
            "pillar", "—", "tall"),
        new("shiva-nandi-unique", "idols",
            S("Shiva and Nandi", "Shiva et Nandi", "Shiva und Nandi", "シヴァとナンディ"),
            S("A unique creation by Guru Ramakanta: Shiva standing beside Nandi, the bull turned outward, the figure kept at a scale a person can measure against.",
              "Une création unique de Guru Ramakanta : Shiva debout près de Nandi, le taureau tourné vers l’extérieur, la figure à une échelle qu’une personne peut mesurer.",
              "Eine einzigartige Schöpfung Guru Ramakantas: Shiva steht neben Nandi, der Stier nach außen gewandt, die Figur in einem Maß, an dem ein Mensch sie messen kann.",
              "グル・ラマカンタの独自の作。シヴァがナンディの傍らに立ち、牛は外を向き、人が大きさを測れる規模です。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Monumental figure", "Figure monumentale", "Monumentale Figur", "記念碑的な像"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "pillar", "—", "tall"),
        new("tirupati-balaji", "idols",
            S("Tirupati Balaji, Chhattisgarh", "Tirupati Balaji, Chhattisgarh", "Tirupati Balaji, Chhattisgarh", "チャッティースガルのティルパティ・バーラージー"),
            S("Ten feet high, in granite. The standing Balaji was installed by Ramakanta at Chhattisgarh, within a carved arch and on an octagonal base.",
              "Dix pieds, en granit. Le Balaji debout a été installé par Ramakanta au Chhattisgarh, dans un arc sculpté et sur un socle octogonal.",
              "Zehn Fuß, in Granit. Der stehende Balaji wurde von Ramakanta in Chhattisgarh aufgestellt, in einem geschnitzten Bogen und auf einem achteckigen Sockel.",
              "高さ10フィート、花崗岩。立つバーラージーを、ラマカンタがチャッティースガルに設置しました。刻まれたアーチと八角の基壇。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("10 ft", "10 pieds", "10 Fuß", "10フィート"),
            S("Chhattisgarh, India", "Chhattisgarh, Inde", "Chhattisgarh, Indien", "インド、チャッティースガル"),
            "pillar", "—", "tall"),
        new("ganapati-granite", "idols",
            S("Ganapati in granite", "Ganapati en granit", "Ganapati in Granit", "花崗岩のガナパティ"),
            S("Eleven feet high. A granite Ganapati by Guru Ramakanta, photographed standing and again as the image was raised into place.",
              "Onze pieds. Un Ganapati de granit de Guru Ramakanta, photographié debout, puis au moment où l’image a été mise en place.",
              "Elf Fuß. Ein Granit-Ganapati von Guru Ramakanta, stehend fotografiert und noch einmal, als das Bild aufgerichtet wurde.",
              "高さ11フィート。グル・ラマカンタによる花崗岩のガナパティ。立像と、据え付けるときの写真。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("11 ft", "11 pieds", "11 Fuß", "11フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("dancing-ganesh-serpentine", "idols",
            S("Dancing Ganesha in pink serpentine", "Ganesha dansant en serpentine rose", "Tanzender Ganesha in rosa Serpentin", "ピンクのサーペンティンの舞うガネーシャ"),
            S("Six feet high. A dancing Ganesha in pink serpentine, the red stone worked into the arch, the mouse and the stepped base.",
              "Six pieds. Un Ganesha dansant en serpentine rose : la pierre rouge est travaillée dans l’arc, la souris et le socle en gradins.",
              "Sechs Fuß. Ein tanzender Ganesha in rosa Serpentin. Der rote Stein ist in den Bogen, die Maus und den gestuften Sockel gearbeitet.",
              "高さ6フィート。ピンクのサーペンティンで舞うガネーシャ。赤い石がアーチ、鼠、段のある基壇まで彫られています。"),
            S("Pink serpentine", "Serpentine rose", "Rosa Serpentin", "ピンクのサーペンティン"),
            "Serpentine",
            S("6 ft", "6 pieds", "6 Fuß", "6フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("ganapati-greater-noida", "idols",
            S("Lord Ganapati, Greater Noida", "Seigneur Ganapati, Greater Noida", "Herr Ganapati, Greater Noida", "グレーター・ノイダのガナパティ"),
            S("Seven feet. A fine Ganapati in green stone, installed for Jaypee Associates at Greater Noida.",
              "Sept pieds. Un Ganapati fin en pierre verte, installé pour Jaypee Associates à Greater Noida.",
              "Sieben Fuß. Ein feiner Ganapati aus grünem Stein, für Jaypee Associates in Greater Noida aufgestellt.",
              "高さ7フィート。緑の石の精緻なガナパティ。グレーター・ノイダのジャイピー・アソシエーツに設置。"),
            S("Green stone", "Pierre verte", "Grüner Stein", "緑の石"),
            "Stone",
            S("7 ft", "7 pieds", "7 Fuß", "7フィート"),
            S("Jaypee Associates, Greater Noida, India", "Jaypee Associates, Greater Noida, Inde", "Jaypee Associates, Greater Noida, Indien", "インド、グレーター・ノイダ、ジャイピー・アソシエーツ"),
            "murti", "—", "tall"),
        new("dancing-ganesh-delhi", "idols",
            S("Dancing Ganesha, Delhi Exhibition", "Ganesha dansant, exposition de Delhi", "Tanzender Ganesha, Ausstellung Delhi", "デリー展の舞うガネーシャ"),
            S("Five feet. A dancing Ganesha with weapons, shown at the Delhi Exhibition.",
              "Cinq pieds. Un Ganesha dansant portant des armes, présenté à l’exposition de Delhi.",
              "Fünf Fuß. Ein tanzender Ganesha mit Waffen, auf der Ausstellung in Delhi gezeigt.",
              "高さ5フィート。武器を持つ舞うガネーシャ。デリーの展覧会に出品。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("5 ft", "5 pieds", "5 Fuß", "5フィート"),
            S("Delhi Exhibition, India", "Exposition de Delhi, Inde", "Ausstellung Delhi, Indien", "インド、デリー展"),
            "murti", "—", "tall"),
        new("saraswati-green-zed", "idols",
            S("Maa Saraswati in Green Zed", "Maa Saraswati en Green Zed", "Maa Saraswati in Green Zed", "グリーン・ゼッドのマー・サラスヴァティー"),
            S("Five feet. Maa Saraswati seated with the veena, carved in Green Zed. The atelier calls it a unique creation by Ramakanta.",
              "Cinq pieds. Maa Saraswati assise avec la vînâ, taillée en Green Zed. L’atelier la nomme une création unique de Ramakanta.",
              "Fünf Fuß. Maa Saraswati sitzt mit der Vina, gehauen in Green Zed. Das Atelier nennt es eine einzigartige Schöpfung Ramakantas.",
              "高さ5フィート。ヴィーナーを持つ坐像のマー・サラスヴァティー。石はグリーン・ゼッド。工房はラマカンタの独自の作と記します。"),
            S("Green Zed", "Green Zed", "Green Zed", "グリーン・ゼッド"),
            "Green Zed",
            S("5 ft", "5 pieds", "5 Fuß", "5フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("baivab-laxmi-vinayak", "idols",
            S("Baivab Laxmi Vinayak", "Baivab Laxmi Vinayak", "Baivab Laxmi Vinayak", "バイバブ・ラクシュミー・ヴィナーヤク"),
            S("Ten feet high. A Ganesha shrine made for an international trade fair, with Laxmi and the attendants set into the arch and the base.",
              "Dix pieds. Un sanctuaire de Ganesha réalisé pour une foire internationale, Laxmi et les assistants placés dans l’arc et le socle.",
              "Zehn Fuß. Ein Ganesha-Schrein für eine internationale Messe, mit Laxmi und den Begleitern im Bogen und im Sockel.",
              "高さ10フィート。国際見本市のためのガネーシャの祠。アーチと基壇にラクシュミーと脇侍。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("10 ft", "10 pieds", "10 Fuß", "10フィート"),
            S("International trade fair", "Foire internationale", "Internationale Messe", "国際見本市"),
            "gate", "—", "tall"),
        new("mormugao-port-goa", "architecture",
            S("Walls for Mormugao Port Trust", "Murs pour le Mormugao Port Trust", "Wände für den Mormugao Port Trust", "モルムガオ港湾公社の壁面"),
            S("Fifteen feet. A wall design carved in Khandolite for the Mormugao Port Trust, Goa. The panels set a minaret, a church, a temple festival and the Taj Mahal into one run of stone.",
              "Quinze pieds. Un dessin mural taillé en khandolite pour le Mormugao Port Trust, à Goa. Les panneaux réunissent un minaret, une église, une fête de temple et le Taj Mahal dans une même suite de pierre.",
              "Fünfzehn Fuß. Ein Wandentwurf in Khandolit für den Mormugao Port Trust in Goa. Die Tafeln setzen ein Minarett, eine Kirche, ein Tempelfest und das Taj Mahal in einen Zug aus Stein.",
              "15フィート。ゴアのモルムガオ港湾公社のための、カンドライトの壁面。ミナレット、教会、寺院の祭礼、タージ・マハルを一連の石に刻みます。"),
            S("Khandolite", "Khandolite", "Khandolit", "カンドライト"),
            "Khandolite",
            S("15 ft", "15 pieds", "15 Fuß", "15フィート"),
            S("Mormugao Port Trust, Goa, India", "Mormugao Port Trust, Goa, Inde", "Mormugao Port Trust, Goa, Indien", "インド、ゴア、モルムガオ港湾公社"),
            "frieze", "—", "wide"),
        new("nataraj-patchwork", "rare",
            S("Nataraja, multicoloured stone patchwork", "Nataraja, patchwork de pierres multicolores", "Nataraja, mehrfarbiges Steinpatchwork", "ナタラージャ、多色石のパッチワーク"),
            S("Six feet high. The atelier names this Nataraja as Ramakanta’s own innovation: multicoloured stone patchwork, with the body, the flame ring and the attendants each held in a different stone.",
              "Six pieds. L’atelier présente ce Nataraja comme l’innovation de Ramakanta : un patchwork de pierres multicolores, le corps, le cercle de flammes et les assistants tenus chacun dans une pierre différente.",
              "Sechs Fuß. Das Atelier nennt diesen Nataraja Ramakantas eigene Neuerung: mehrfarbiges Steinpatchwork, Körper, Flammenring und Begleitfiguren jeweils in einem anderen Stein.",
              "高さ6フィート。工房はこのナタラージャを、ラマカンタ自身の工夫と記します。多色石のパッチワークで、身体、炎の円光、脇侍をそれぞれ別の石で保ちます。"),
            S("Multicoloured stone patchwork", "Patchwork de pierres multicolores", "Mehrfarbiges Steinpatchwork", "多色石のパッチワーク"),
            "Patchwork stone",
            S("6 ft", "6 pieds", "6 Fuß", "6フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "peacock", "—", "tall"),
        new("ganapati-multicolour", "idols",
            S("Lord Ganapati", "Seigneur Ganapati", "Herr Ganapati", "ガナパティ"),
            S("Seven feet high, in multicoloured stone. Ganapati sits in a shrine-like surround, the yellow and russet stones set together as one image.",
              "Sept pieds, en pierre multicolore. Ganapati siège dans un entourage de sanctuaire, les pierres jaunes et rousses assemblées en une seule image.",
              "Sieben Fuß, in mehrfarbigem Stein. Ganapati sitzt in einer schreinartigen Rahmung, gelbe und rostrote Steine zu einem Bild gefügt.",
              "高さ7フィート、多色石。ガナパティは祠のような囲みに坐し、黄と赤褐の石が一つの像になります。"),
            S("Multicoloured stone", "Pierre multicolore", "Mehrfarbiger Stein", "多色石"),
            "Patchwork stone",
            S("7 ft", "7 pieds", "7 Fuß", "7フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("mixed-onyx-ganesha", "idols",
            S("Mixed onyx Ganesha", "Ganesha en onyx mêlé", "Ganesha aus gemischtem Onyx", "混成オニックスのガネーシャ"),
            S("Eight feet high. A mixed onyx Ganesha by Ramakanta, the green and red of the stone left visible in the leaves, the trunk and the crown.",
              "Huit pieds. Un Ganesha en onyx mêlé de Ramakanta : le vert et le rouge de la pierre restent lisibles dans les feuilles, la trompe et la couronne.",
              "Acht Fuß. Ein Ganesha aus gemischtem Onyx von Ramakanta. Grün und Rot des Steins bleiben in Blättern, Rüssel und Krone sichtbar.",
              "高さ8フィート。ラマカンタによる混成オニックスのガネーシャ。葉、鼻、冠に石の緑と赤が残ります。"),
            S("Mixed onyx", "Onyx mêlé", "Gemischter Onyx", "混成オニックス"),
            "Onyx",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "murti", "—", "tall"),
        new("saranath-buddha", "idols",
            S("Sarnath Buddha", "Bouddha de Sarnath", "Sarnath-Buddha", "サールナートの仏陀"),
            S("Nine feet high. A black granite Buddha in the Sarnath type, described by the atelier as a unique creation by Ramakanta: the wheel-turning hands, the lion throne and the flying figures above the halo.",
              "Neuf pieds. Un Bouddha de granit noir du type de Sarnath, que l’atelier décrit comme une création unique de Ramakanta : les mains qui tournent la roue, le trône aux lions et les figures volantes au-dessus du halo.",
              "Neun Fuß. Ein Buddha aus schwarzem Granit vom Sarnath-Typus, vom Atelier als einzigartige Schöpfung Ramakantas beschrieben: die raddrehenden Hände, der Löwenthron und die fliegenden Figuren über dem Nimbus.",
              "高さ9フィート。サールナート型の黒御影石の仏陀。工房はラマカンタの独自の作と記します。転法輪の印、獅子座、光背の上の飛天。"),
            S("Black granite", "Granit noir", "Schwarzer Granit", "黒御影石"),
            "Black granite",
            S("9 ft", "9 pieds", "9 Fuß", "9フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "kalasha", "—", "tall"),
        new("buddha-meditation", "idols",
            S("Buddha in meditation", "Bouddha en méditation", "Buddha in Meditation", "瞑想の仏陀"),
            S("Eight feet high. Lord Buddha seated in meditation, with smaller Buddhas set in the niches of the throne behind him.",
              "Huit pieds. Le Bouddha assis en méditation, de plus petits Bouddhas placés dans les niches du trône derrière lui.",
              "Acht Fuß. Der Buddha sitzt in Meditation, kleinere Buddhas in den Nischen des Throns hinter ihm.",
              "高さ8フィート。瞑想する仏陀。背後の座の龕に、小さな仏陀が並びます。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "temple", "—", "tall"),
        new("buddha-russian-museum", "international",
            S("Buddha for the Russian Museum", "Bouddha pour le musée russe", "Buddha für das Russische Museum", "ロシアの美術館のための仏陀"),
            S("A stele of the seated Buddha carved by Ramakanta for the Russian Museum, with attendants in the side niches and lions at the base.",
              "Une stèle du Bouddha assis, taillée par Ramakanta pour le musée russe, avec des assistants dans les niches latérales et des lions au socle.",
              "Eine Stele des sitzenden Buddha, von Ramakanta für das Russische Museum gehauen, mit Begleitern in den Seitennischen und Löwen am Sockel.",
              "ロシアの美術館のためにラマカンタが刻んだ坐仏の石碑。脇の龕に脇侍、基壇に獅子。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Stele", "Stèle", "Stele", "石碑"),
            S("Russian Museum", "Musée russe", "Russisches Museum", "ロシアの美術館"),
            "kalasha", "—", "tall"),
        new("buddha-heads", "idols",
            S("Buddha heads", "Têtes de Bouddha", "Buddhaköpfe", "仏頭"),
            S("Two stone heads of the Buddha carved by Ramakanta, one in grey stone and one in warm sandstone, the hair and the ushnisha built curl by curl.",
              "Deux têtes de Bouddha en pierre, taillées par Ramakanta, l’une en pierre grise, l’autre en grès chaud, les cheveux et l’ushnisha boucle par boucle.",
              "Zwei steinerne Buddhaköpfe von Ramakanta, einer in grauem Stein, einer in warmem Sandstein. Haar und Ushnisha Locke für Locke.",
              "ラマカンタが刻んだ二つの仏頭。一つは灰色の石、一つは温かい砂岩。髪と肉髻を巻ごとに造ります。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Heads", "Têtes", "Köpfe", "頭部"),
            S("Workshop", "Atelier", "Werkstatt", "工房"),
            "murti", "—", "regular"),
        new("mukteswar-gate-delhi", "architecture",
            S("Mukteswar pattern gate, Delhi", "Porte au modèle de Mukteswar, Delhi", "Tor im Mukteswar-Muster, Delhi", "ムクテーシュワル型の門、デリー"),
            S("Thirteen feet. A gate in the Mukteswar pattern, installed in Delhi by Ramakanta. The same record shows him passing the carving of pillars on to a younger generation.",
              "Treize pieds. Une porte au modèle de Mukteswar, installée à Delhi par Ramakanta. Le même dossier le montre transmettant la taille des piliers à une génération plus jeune.",
              "Dreizehn Fuß. Ein Tor im Mukteswar-Muster, von Ramakanta in Delhi aufgestellt. Dieselbe Aufzeichnung zeigt, wie er die Pfeilerarbeit an eine jüngere Generation weitergibt.",
              "13フィート。ムクテーシュワル型の門を、ラマカンタがデリーに設置しました。同じ記録に、柱の彫りを若い世代へ渡す姿があります。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("13 ft", "13 pieds", "13 Fuß", "13フィート"),
            S("Delhi, India", "Delhi, Inde", "Delhi, Indien", "インド、デリー"),
            "gate", "—", "wide"),
        new("jaypee-marble", "idols",
            S("White marble figures, Jaypee University", "Figures de marbre blanc, université Jaypee", "Figuren aus weißem Marmor, Jaypee-Universität", "白大理石の像、ジャイピー大学"),
            S("Seven feet high. A set of white marble figures installed at Jaypee University, Uttar Pradesh: Hanuman, Shiva, Durga, Lakshmi, and standing deities including a divine pair.",
              "Sept pieds. Un ensemble de figures en marbre blanc installé à l’université Jaypee, Uttar Pradesh : Hanuman, Shiva, Durga, Lakshmi, et des divinités debout, dont un couple divin.",
              "Sieben Fuß. Eine Folge von Figuren aus weißem Marmor an der Jaypee-Universität, Uttar Pradesh: Hanuman, Shiva, Durga, Lakshmi und stehende Gottheiten, darunter ein göttliches Paar.",
              "高さ7フィート。ウッタル・プラデーシュのジャイピー大学に設置した白大理石の像。ハヌマーン、シヴァ、ドゥルガー、ラクシュミー、そして神の対を含む立像。"),
            S("White marble", "Marbre blanc", "Weißer Marmor", "白大理石"),
            "White marble",
            S("7 ft", "7 pieds", "7 Fuß", "7フィート"),
            S("Jaypee University, Uttar Pradesh, India", "Université Jaypee, Uttar Pradesh, Inde", "Jaypee-Universität, Uttar Pradesh, Indien", "インド、ウッタル・プラデーシュ、ジャイピー大学"),
            "murti", "—", "tall"),
        new("prashanti-nilayam", "architecture",
            S("Work for Prashanti Nilayam", "Œuvre pour Prashanti Nilayam", "Arbeit für Prashanti Nilayam", "プラシャンティ・ニラヤムのための仕事"),
            S("Architectural stone for Shri Satya Sai Prashanti Nilayam in Andhra Pradesh: a chariot-wheel panel, a carved mandapam, and figures prepared for the site.",
              "Pierre d’architecture pour Shri Satya Sai Prashanti Nilayam, en Andhra Pradesh : un panneau à roue de char, un mandapam sculpté, et des figures préparées pour le lieu.",
              "Architekturstein für Shri Satya Sai Prashanti Nilayam in Andhra Pradesh: eine Wagenradtafel, ein geschnitztes Mandapam und Figuren für den Ort.",
              "アンドラ・プラデーシュのシュリー・サティヤ・サイ・プラシャンティ・ニラヤムのための建築の石。戦車の車輪のパネル、刻まれたマンダパム、その場のための像。"),
            S("Stone", "Pierre", "Stein", "石"),
            "Stone",
            S("Architectural ensemble", "Ensemble architectural", "Architektonisches Ensemble", "建築の一組"),
            S("Prashanti Nilayam, Andhra Pradesh, India", "Prashanti Nilayam, Andhra Pradesh, Inde", "Prashanti Nilayam, Andhra Pradesh, Indien", "インド、アンドラ・プラデーシュ、プラシャンティ・ニラヤム"),
            "wheel", "—", "wide"),
        new("temple-drawing", "architecture",
            S("Temple drawings", "Dessins de temple", "Tempelzeichnungen", "寺院の図面"),
            S("Measured drawings from the atelier. The sheets set out the elevation of a temple, bay by bay, before the stone is cut.",
              "Dessins cotés de l’atelier. Les feuilles établissent l’élévation d’un temple, travée par travée, avant que la pierre ne soit coupée.",
              "Bemaßte Zeichnungen des Ateliers. Die Blätter legen die Ansicht eines Tempels Feld für Feld fest, bevor der Stein geschnitten wird.",
              "工房の寸法図。石を切る前に、寺院の立面を間ごとに定めます。"),
            S("Drawing on paper", "Dessin sur papier", "Zeichnung auf Papier", "紙の図面"),
            "Paper",
            S("Sheets", "Feuilles", "Blätter", "図面"),
            S("Atelier", "Atelier", "Atelier", "工房"),
            "pillar", "—", "wide"),
        new("semiprecious-stone", "idols",
            S("Semi-precious stone", "Pierre semi-précieuse", "Halbedelstein", "半貴石"),
            S("Guru Ramakanta carving semi-precious stone at his workshop, with finished heads in gold-toned and green stone beside the bench.",
              "Guru Ramakanta taille la pierre semi-précieuse dans son atelier, des têtes achevées en pierre dorée et verte à côté de l’établi.",
              "Guru Ramakanta arbeitet in seiner Werkstatt an Halbedelstein. Fertige Köpfe in goldtonigem und grünem Stein stehen neben der Bank.",
              "グル・ラマカンタが工房で半貴石を刻みます。作業台の傍らに、金色と緑の石の頭部があります。"),
            S("Semi-precious stone", "Pierre semi-précieuse", "Halbedelstein", "半貴石"),
            "Semi-precious stone",
            S("Workshop pieces", "Pièces d’atelier", "Werkstattstücke", "工房の作"),
            S("Workshop", "Atelier", "Werkstatt", "工房"),
            "murti", "—", "tall"),
        new("viswaroop-darsan", "rare",
            S("Viswaroop Darsan", "Viswaroop Darsan", "Viswaroop Darsan", "ヴィシュワループ・ダルシャン"),
            S("Viswarupa, the awarded creation of National Awardee Guru Ramakanta Mahapatra. The cosmic form is a shrine of pale stone: many arms, a tiered crown, and a base crowded with figures. A later photograph shows him carving a small Viswarupa by hand.",
              "Viswarupa, la création primée du lauréat national Guru Ramakanta Mahapatra. La forme cosmique est un sanctuaire de pierre pâle : de nombreux bras, une couronne étagée, et un socle peuplé de figures. Une photographie plus tardive le montre taillant un petit Viswarupa à la main.",
              "Viswarupa, die ausgezeichnete Schöpfung des Nationalpreisträgers Guru Ramakanta Mahapatra. Die kosmische Form ist ein Schrein aus hellem Stein: viele Arme, eine gestufte Krone und ein Sockel voller Figuren. Eine spätere Aufnahme zeigt ihn beim Behauen eines kleinen Viswarupa.",
              "国家賞受賞者グル・ラマカンタ・マハパトラの受賞作、ヴィシュワルパ。宇宙の姿は淡い石の祠です。多くの腕、段になった冠、人物の並ぶ基壇。後の写真では、小さなヴィシュワルパを手で刻んでいます。"),
            S("Natural onyx", "Onyx naturel", "Natürlicher Onyx", "天然オニックス"),
            "Onyx",
            S("Shrine", "Sanctuaire", "Schrein", "祠"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "peacock", "—", "tall"),
        new("dasavatara", "temple",
            S("Dasavatara Sculpture", "Sculpture du Dasavatara", "Dasavatara-Skulptur", "ダシャーヴァターラ"),
            S("Eight feet, in a posture the atelier calls unique. The Dasa Avatar is carved as one standing image, with the face, the crown and the attributes held in pale stone.",
              "Huit pieds, dans une posture que l’atelier dit unique. Le Dasa Avatar est taillé comme une seule figure debout, le visage, la couronne et les attributs tenus dans une pierre pâle.",
              "Acht Fuß, in einer Haltung, die das Atelier einzigartig nennt. Der Dasa Avatar ist als eine stehende Figur gehauen, Gesicht, Krone und Attribute in hellem Stein.",
              "高さ8フィート。工房が独自の姿と記すダシャーヴァターラ。淡い石に、顔、冠、持物を一つの立像として刻みます。"),
            S("Pale stone", "Pierre pâle", "Heller Stein", "淡い石"),
            "Stone",
            S("8 ft", "8 pieds", "8 Fuß", "8フィート"),
            S("Atelier record", "Registre de l’atelier", "Nachweis des Ateliers", "工房の記録"),
            "wheel", "—", "tall"),
        new("seven-temple-shrines-singapore", "international",
            S("Seven Temple Shrines, Singapore", "Sept sanctuaires, Singapour", "Sieben Tempelschreine, Singapur", "シンガポールの七つの祠堂"),
            S("Temple work installed in Singapore. The shrines are dressed in the Odishan manner, with carved pillars, doorways and crowns. Guru Ramakanta and his disciples are recorded fine-tuning the stone on site, and the stone was laid for the Sri Krishna temple there.",
              "Travail de temple installé à Singapour. Les sanctuaires sont vêtus à la manière de l’Odisha, avec piliers, portes et couronnes sculptés. Guru Ramakanta et ses disciples sont photographiés en train d’ajuster la pierre sur place, et la pierre a été posée pour le temple de Sri Krishna.",
              "Tempelarbeit, in Singapur aufgestellt. Die Schreine sind in odishanischer Art gefasst, mit geschnitzten Pfeilern, Türen und Kronen. Guru Ramakanta und seine Schüler sind bei der Feinarbeit vor Ort festgehalten, und der Stein für den Sri-Krishna-Tempel wurde gelegt.",
              "シンガポールに設置した寺院の仕事。祠堂はオディシャの作法で、刻まれた柱、戸口、冠を持ちます。グル・ラマカンタと弟子たちが現地で石を整え、シュリー・クリシュナ寺院の定礎も記録されています。"),
            S("Granite and sandstone", "Granit et grès", "Granit und Sandstein", "花崗岩と砂岩"),
            "Granite",
            S("Seven-shrine ensemble", "Ensemble de sept sanctuaires", "Ensemble von sieben Schreinen", "七祠堂の一組"),
            S("Singapore", "Singapour", "Singapur", "シンガポール"),
            "temple", "—", "wide"),
        new("perumal-mandapam", "architecture",
            S("Perumal Mandapam", "Perumal Mandapam", "Perumal Mandapam", "ペルマル・マンダパム"),
            S("A mandapam is a pillared hall, not an ornament applied afterwards. Perumal Mandapam is approached as architecture: load, rhythm of columns, and the sculpture that the hall is strong enough to carry.",
              "Un mandapam est une salle à piliers, non un ornement ajouté ensuite. Perumal Mandapam est abordé comme architecture : la charge, le rythme des colonnes, et la sculpture que la salle est assez forte pour porter.",
              "Ein Mandapam ist eine Pfeilerhalle, kein nachträglich aufgesetzter Schmuck. Perumal Mandapam wird als Architektur behandelt: Last, Rhythmus der Stützen und die Skulptur, die die Halle zu tragen vermag.",
              "マンダパムは柱の間であり、後から足す装飾ではありません。ペルマル・マンダパムは建築として扱います。荷重、柱のリズム、そしてその間が担える彫刻。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Pillared hall, architectural", "Salle à piliers, architecture", "Pfeilerhalle, architektonisch", "柱間、建築"),
            S("India", "Inde", "Indien", "インド"),
            "pillar", "—", "wide"),
        new("ashokan-pillar-japan", "international",
            S("Ashokan Pillar, Japan", "Pilier d’Ashoka, Japon", "Ashoka-Säule, Japan", "日本のアショーカ石柱"),
            S("Installed in 1995. The Ashokan pillar is a memory of the Mauryan column — a shaft, a capital, an animal of state — translated by an Odishan hand for a site in Japan. It is the work that first made the atelier’s journey abroad a fact rather than an ambition.",
              "Installé en 1995. Le pilier d’Ashoka est une mémoire de la colonne maurya — un fût, un chapiteau, un animal d’État — traduit par une main d’Odisha pour un site au Japon. C’est l’œuvre qui fit du voyage de l’atelier un fait.",
              "Aufgestellt 1995. Die Ashoka-Säule ist eine Erinnerung an die mauryanische Säule — Schaft, Kapitell, ein Tier des Staates — von einer odishanischen Hand für einen Ort in Japan übertragen. Mit diesem Werk wurde die Reise des Ateliers Tatsache.",
              "1995年に設置。アショーカの石柱は、マウリヤの円柱の記憶です。軸、柱頭、国家の獣を、オディシャの手が日本の敷地のために訳しました。工房の海外への旅を、志ではなく事実にした仕事です。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Pillar and capital", "Pilier et chapiteau", "Säule und Kapitell", "石柱と柱頭"),
            S("Japan", "Japon", "Japan", "日本"),
            "pillar", "1995", "tall"),
        new("heritage-gate-odisha", "architecture",
            S("Largest Stone Heritage Gate, Odisha", "La plus grande porte patrimoniale en pierre, Odisha", "Größtes steinernes Erbe-Tor, Odisha", "オディシャ最大の石の遺産門"),
            S("Odisha’s largest stone heritage gate, made by Guru Ramakanta at Vedabyasa, Rourkela. The finished gate spans the road on carved pillars and a long roof of stone pots. The other photographs show the scaffolding, the courses going up, and the smaller shrine beside the work.",
              "La plus grande porte patrimoniale en pierre de l’Odisha, faite par Guru Ramakanta à Vedabyasa, Rourkela. La porte achevée enjambe la route sur des piliers sculptés et un long toit de pots de pierre. Les autres photographies montrent l’échafaudage, les assises qui montent, et le petit sanctuaire à côté du chantier.",
              "Odishas größtes steinernes Erbe-Tor, von Guru Ramakanta in Vedabyasa, Rourkela. Das fertige Tor überspannt die Straße auf geschnitzten Pfeilern und einem langen Dach aus Steintöpfen. Die weiteren Aufnahmen zeigen das Gerüst, die aufsteigenden Schichten und den kleineren Schrein neben der Arbeit.",
              "オディシャ最大の石の遺産門。ルールケラのヴェーダヴィヤーサでグル・ラマカンタが作りました。完成した門は彫られた柱と石の壺が並ぶ長い屋根で道をまたぎます。ほかの写真は足場、積み上がる段、仕事の傍らの小さな祠を示します。"),
            S("Dressed sandstone", "Grès appareillé", "Bearbeiteter Sandstein", "化粧砂岩"),
            "Khandolite",
            S("Monumental gateway", "Portail monumental", "Monumentales Tor", "記念碑的な門"),
            S("Vedabyasa, Rourkela, Odisha, India", "Vedabyasa, Rourkela, Odisha, Inde", "Vedabyasa, Rourkela, Odisha, Indien", "インド、オディシャ、ルールケラ、ヴェーダヴィヤーサ"),
            "gate", "—", "wide"),
        new("jagannath-panel", "idols",
            S("Jagannath Panel", "Panneau de Jagannath", "Jagannath-Tafel", "ジャガンナートのパネル"),
            S("A devotional panel of Jagannath, carved in the visual language of Puri rather than as a generic icon. The face is a discipline of a few essential marks.",
              "Un panneau de dévotion de Jagannath, taillé dans le langage visuel de Puri, non comme une icône générique. Le visage est une discipline de quelques signes essentiels.",
              "Eine Andachtstafel Jagannaths, gehauen in der Bildsprache Puris, nicht als allgemeine Ikone. Das Gesicht ist eine Disziplin weniger wesentlicher Zeichen.",
              "プリーの視覚言語で刻むジャガンナートの礼拝パネル。一般的な偶像ではありません。顔は、わずかな本質の印の修練です。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Devotional panel", "Panneau de dévotion", "Andachtstafel", "礼拝パネル"),
            S("Puri tradition, Odisha", "Tradition de Puri, Odisha", "Puri-Tradition, Odisha", "プリーの伝統、オディシャ"),
            "lotus", "—", "regular"),
        new("ganesha-murti", "idols",
            S("Ganesha Murti", "Murti de Ganesha", "Ganesha-Murti", "ガネーシャ像"),
            S("Ganesha carved to be circumambulated: trunk, bowl, and the calm of the remover of obstacles, readable from more than one side.",
              "Un Ganesha taillé pour être circumambulé : trompe, bol, et le calme de celui qui ôte les obstacles, lisible de plus d’un côté.",
              "Ein Ganesha zum Umwandeln gehauen: Rüssel, Schale und die Ruhe dessen, der Hindernisse nimmt, von mehr als einer Seite lesbar.",
              "右繞できるように刻むガネーシャ。鼻、鉢、障害を除く者の静けさが、一面からだけでは読めません。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Image in the round", "Image en ronde-bosse", "Rundbild", "丸彫り"),
            S("Atelier, Odisha", "Atelier, Odisha", "Atelier, Odisha", "工房、オディシャ"),
            "murti", "—", "regular"),
        new("ramayana-mural", "murals",
            S("Ramayana Mural", "Murale du Ramayana", "Ramayana-Wandbild", "ラーマーヤナの壁画"),
            S("A narrative wall: episodes set in a frieze so that a visitor reads the epic as a walk, not as a caption.",
              "Un mur narratif : des épisodes en frise, pour que le visiteur lise l’épopée en marchant, non dans une légende.",
              "Eine erzählende Wand: Episoden im Fries, sodass der Besucher das Epos im Gehen liest, nicht in einer Bildunterschrift.",
              "物語の壁。フリーズに場面を置き、訪れる人が叙事詩を歩きながら読みます。"),
            S("Sandstone relief", "Relief de grès", "Sandsteinrelief", "砂岩の浮彫"),
            "Sandstone",
            S("Narrative frieze", "Frise narrative", "Erzählfries", "物語のフリーズ"),
            S("Temple wall, India", "Mur de temple, Inde", "Tempelwand, Indien", "インドの寺院の壁"),
            "frieze", "—", "wide"),
        new("govardhana", "idols",
            S("Krishna Govardhana", "Krishna Govardhana", "Krishna Govardhana", "ゴーヴァルダナのクリシュナ"),
            S("Krishna lifting the mountain: a problem of weight made visible. The mountain has to feel held, and the body has to remain a dancer’s body.",
              "Krishna soulevant la montagne : un problème de poids rendu visible. La montagne doit sembler portée, et le corps rester celui d’un danseur.",
              "Krishna hebt den Berg: ein Problem des Gewichts, sichtbar gemacht. Der Berg muss gehalten wirken, der Körper der eines Tänzers bleiben.",
              "山を掲げるクリシュナ。重さを目に見える問題にします。山は支えられ、身体は踊る者の身体のままです。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Sandstone",
            S("Figural sculpture", "Sculpture figurée", "Figürliche Skulptur", "人物彫刻"),
            S("Atelier, Odisha", "Atelier, Odisha", "Atelier, Odisha", "工房、オディシャ"),
            "kalasha", "—", "tall"),
        new("konark-wheel-relief", "temple",
            S("Konark Wheel Relief", "Relief de roue de Konark", "Konark-Rad-Relief", "コナーラクの車輪"),
            S("A study in the Konark tradition: the wheel as cosmos and as architecture, carved with the patience of a spoke-by-spoke geometry.",
              "Une étude dans la tradition de Konark : la roue comme cosmos et comme architecture, taillée avec la patience d’une géométrie rayon par rayon.",
              "Eine Studie in der Konark-Tradition: das Rad als Kosmos und als Architektur, gehauen mit der Geduld einer Speiche-für-Speiche-Geometrie.",
              "コナーラクの伝統による習作。車輪は宇宙であり建築です。輻一本ずつの幾何を、忍耐で刻みます。"),
            S("Sandstone", "Grès", "Sandstein", "砂岩"),
            "Khandolite",
            S("Architectural relief", "Relief d’architecture", "Architekturrelief", "建築浮彫"),
            S("Odisha, India", "Odisha, Inde", "Odisha, Indien", "インド、オディシャ"),
            "wheel", "—", "regular"),
        new("narrative-capital", "architecture",
            S("Narrative Pillar Capital", "Chapiteau narratif", "Erzählendes Kapitell", "物語の柱頭"),
            S("A capital that carries a story as well as a load. The carving stops where the structure would be weakened.",
              "Un chapiteau qui porte un récit autant qu’une charge. La taille s’arrête là où la structure serait affaiblie.",
              "Ein Kapitell, das eine Geschichte trägt und eine Last. Die Arbeit endet, wo die Struktur geschwächt würde.",
              "物語と荷重を同時に担う柱頭。構造が弱るところでは、彫りを止めます。"),
            S("Granite", "Granit", "Granit", "花崗岩"),
            "Granite",
            S("Architectural member", "Élément d’architecture", "Architekturglied", "建築部材"),
            S("Temple project, India", "Projet de temple, Inde", "Tempelprojekt, Indien", "インドの寺院"),
            "pillar", "—", "regular")
    ];

    public static readonly IReadOnlyList<Award> Awards =
    [
        new("odisha-state-1990", "1990",
            S("Odisha State Award", "Prix de l’État d’Odisha", "Staatspreis Odisha", "オディシャ州賞"),
            S("State Best Designing Award, 1990. The first major public recognition of design as well as carving.",
              "State Best Designing Award, 1990. Première grande reconnaissance publique du dessin autant que de la taille.",
              "State Best Designing Award, 1990. Die erste große öffentliche Anerkennung von Entwurf und Steinarbeit.",
              "1990年、州最優秀デザイン賞。彫りとともに、設計が公に認められた最初の大きな顕彰。"),
            "lotus"),
        new("lalit-kala-1997", "1997",
            S("Lalit Kala Academy Award", "Prix de la Lalit Kala Academy", "Lalit-Kala-Academy-Preis", "ラリット・カラ・アカデミー賞"),
            S("Awarded in 1997, in association with the Lalit Kala Akademi.",
              "Décerné en 1997, en lien avec la Lalit Kala Akademi.",
              "Verliehen 1997, in Verbindung mit der Lalit Kala Akademi.",
              "1997年。ラリット・カラ・アカデミーに連なる賞。"),
            "kalasha"),
        new("national-award-2005", "2005",
            S("National Award for Master Craftsperson", "Prix national du maître artisan", "Nationalpreis für Meisterhandwerk", "マスター・クラフツパーソン国家賞"),
            S("Conferred in 2005 by the Government of India. This is the honour named when the atelier says National Awardee.",
              "Conféré en 2005 par le gouvernement de l’Inde. C’est l’honneur nommé lorsque l’atelier dit lauréat national.",
              "2005 von der Regierung Indiens verliehen. Diese Ehrung ist gemeint, wenn das Atelier Nationalpreisträger sagt.",
              "2005年、インド政府が授与。工房がナショナル・アワーディーと言うとき、この栄誉を指します。"),
            "temple"),
        new("stona", "—",
            S("STONA Awards", "Prix STONA", "STONA Awards", "ストーナ賞"),
            S("Recognition within the stone industry’s own gathering, STONA.",
              "Reconnaissance dans le rassemblement de l’industrie de la pierre, STONA.",
              "Anerkennung im eigenen Treffen der Steinindustrie, STONA.",
              "石材産業の集い、ストーナにおける顕彰。"),
            "pillar"),
        new("guru-samrat", "—",
            S("Guru Samrat Award", "Prix Guru Samrat", "Guru-Samrat-Preis", "グル・サムラート賞"),
            S("An honour that names the teacher, not only the carver.",
              "Un honneur qui nomme le professeur, non seulement le tailleur.",
              "Eine Ehrung, die den Lehrer nennt, nicht nur den Steinmetz.",
              "彫り手だけでなく、師を名指す栄誉。"),
            "conch"),
        new("nitya-nutan", "—",
            S("Nitya Nutan Samman", "Nitya Nutan Samman", "Nitya Nutan Samman", "ニティヤ・ヌタン・サンマン"),
            S("A samman recognising a practice that stays both rooted and renewed.",
              "Un samman pour une pratique à la fois enracinée et renouvelée.",
              "Ein Samman für eine Praxis, die verwurzelt und erneuert zugleich bleibt.",
              "根を保ちながら新たにあり続ける実践へのサンマン。"),
            "peacock"),
        new("singapore", "—",
            S("International recognition, Singapore", "Reconnaissance internationale, Singapour", "Internationale Anerkennung, Singapur", "シンガポールでの国際的評価"),
            S("Recognition connected with the atelier’s work for temple shrines in Singapore.",
              "Reconnaissance liée au travail de l’atelier pour les sanctuaires de Singapour.",
              "Anerkennung im Zusammenhang mit der Arbeit des Ateliers für Tempelschreine in Singapur.",
              "シンガポールの寺院祠堂に関わる仕事への評価。"),
            "gate"),
        new("certificates", "—",
            S("Certificates of appreciation", "Certificats d’appréciation", "Anerkennungsurkunden", "感謝状"),
            S("A body of appreciation certificates from institutions and patrons, held in the emporium archive.",
              "Un ensemble de certificats d’appréciation d’institutions et de commanditaires, conservé aux archives de l’emporium.",
              "Eine Reihe von Anerkennungsurkunden von Institutionen und Auftraggebern, im Archiv des Emporiums.",
              "機関とパトロンからの感謝状。エンポリアムのアーカイブに保管。"),
            "frieze")
    ];
}
