namespace MahapatraArts.Services;

public static class ContentWorld
{
    private static LStr S(string en, string fr, string de, string ja) => new(en, fr, de, ja);

    public static readonly IReadOnlyList<Destination> Destinations =
    [
        new("india", S("India", "Inde", "Indien", "インド"), 68, 46,
        [
            new("mukteswar-gate-delhi",
                S("Mukteswar pattern gate, Delhi", "Porte au modèle de Mukteswar, Delhi", "Tor im Mukteswar-Muster, Delhi", "ムクテーシュワル型の門、デリー"),
                S("A 13-foot gate in the Mukteswar pattern, installed in Delhi. The record also shows the carving of pillars being taught to a younger generation.",
                  "Une porte de 13 pieds au modèle de Mukteswar, installée à Delhi. Le dossier montre aussi la taille des piliers enseignée à une génération plus jeune.",
                  "Ein 13 Fuß hohes Tor im Mukteswar-Muster, in Delhi aufgestellt. Die Aufzeichnung zeigt auch die Weitergabe der Pfeilerarbeit an eine jüngere Generation.",
                  "ムクテーシュワル型の13フィートの門をデリーに設置。柱の彫りを若い世代に渡す記録も残ります。"),
                "gate", "—"),
            new("jaypee-university",
                S("White marble, Jaypee University", "Marbre blanc, université Jaypee", "Weißer Marmor, Jaypee-Universität", "白大理石、ジャイピー大学"),
                S("Seven-foot figures in white marble, installed at Jaypee University, Uttar Pradesh.",
                  "Des figures de sept pieds en marbre blanc, installées à l’université Jaypee, Uttar Pradesh.",
                  "Sieben Fuß hohe Figuren aus weißem Marmor, aufgestellt an der Jaypee-Universität, Uttar Pradesh.",
                  "ウッタル・プラデーシュのジャイピー大学に設置した、高さ7フィートの白大理石の像。"),
                "murti", "—"),
            new("prashanti-nilayam",
                S("Prashanti Nilayam, Andhra Pradesh", "Prashanti Nilayam, Andhra Pradesh", "Prashanti Nilayam, Andhra Pradesh", "プラシャンティ・ニラヤム、アンドラ・プラデーシュ"),
                S("Stone for Shri Satya Sai Prashanti Nilayam: a wheel panel, a mandapam, and figures for the site.",
                  "Pierre pour Shri Satya Sai Prashanti Nilayam : un panneau à roue, un mandapam et des figures pour le lieu.",
                  "Stein für Shri Satya Sai Prashanti Nilayam: eine Radtafel, ein Mandapam und Figuren für den Ort.",
                  "シュリー・サティヤ・サイ・プラシャンティ・ニラヤムのための石。車輪のパネル、マンダパム、その場の像。"),
                "wheel", "—"),
            new("jagannath-gurgaon",
                S("Jagannath Temple, Gurgaon", "Temple de Jagannath, Gurgaon", "Jagannath-Tempel, Gurgaon", "ジャガンナート寺院、グルガオン"),
                S("An ongoing temple. The record shows the day the memorandum was signed, and the model of the temple at Gurgaon.",
                  "Un temple en cours. Le dossier montre le jour de la signature du protocole, et la maquette du temple à Gurgaon.",
                  "Ein Tempel im Bau. Die Aufzeichnung zeigt den Tag der Absichtserklärung und das Modell des Tempels in Gurgaon.",
                  "進行中の寺院。グルガオンでの覚書の日と、寺院の模型が記録にあります。"),
                "temple", "Ongoing"),
            new("jagannath-gurgaon-stone",
                S("Laying the stone, Gurgaon", "Pose de la pierre, Gurgaon", "Grundstein, Gurgaon", "定礎、グルガオン"),
                S("The stone-laying day of the Jagannath temple at Gurgaon.",
                  "Le jour de la pose de la pierre du temple de Jagannath à Gurgaon.",
                  "Der Tag der Grundsteinlegung des Jagannath-Tempels in Gurgaon.",
                  "グルガオンのジャガンナート寺院の定礎の日。"),
                "kalasha", "Ongoing"),
            new("shiva-jatni",
                S("Shiva at Somnath Temple, Jatni", "Shiva au temple de Somnath, Jatni", "Shiva am Somnath-Tempel, Jatni", "ジャトニのソムナート寺院のシヴァ"),
                S("Ongoing work on what the atelier calls Odisha’s highest Shiva statue, at Somnath Temple, Jatni.",
                  "Travail en cours de ce que l’atelier appelle la plus haute statue de Shiva de l’Odisha, au temple de Somnath, à Jatni.",
                  "Laufende Arbeit an dem, was das Atelier die höchste Shiva-Statue Odishas nennt, am Somnath-Tempel in Jatni.",
                  "工房がオディシャで最も高いシヴァ像と記す、ジャトニのソムナート寺院での進行中の仕事。"),
                "pillar", "Ongoing"),
            new("odisha-temple-works",
                S("Temples across Odisha", "Temples à travers l’Odisha", "Tempel in Odisha", "オディシャ各地の寺院"),
                S("Ongoing temple work in several places across Odisha: foundations, sanctums and stone raised on site.",
                  "Travail de temple en cours en plusieurs lieux de l’Odisha : fondations, sanctuaires et pierre élevée sur place.",
                  "Laufende Tempelarbeit an mehreren Orten in Odisha: Fundamente, Sanktuare und Stein, der vor Ort aufgerichtet wird.",
                  "オディシャ各地で進行中の寺院の仕事。基礎、聖所、現地で積み上げる石。"),
                "temple", "Ongoing"),
            new("shiva-nandi-dharmasthala",
                S("Shiva and Nandi, Dharmasthala", "Shiva et Nandi, Dharmasthala", "Shiva und Nandi, Dharmasthala", "ダルマスターラのシヴァとナンディ"),
                S("A 15-foot Shiva with Nandi in Khandolite, by Guru Ramakanta, at Dharmasthala.",
                  "Un Shiva de 15 pieds avec Nandi, en khandolite, par Guru Ramakanta, à Dharmasthala.",
                  "Ein 15 Fuß hoher Shiva mit Nandi in Khandolit, von Guru Ramakanta, in Dharmasthala.",
                  "ダルマスターラに設置した、カンドライトの高さ15フィートのシヴァとナンディ。"),
                "pillar", "—"),
            new("jaypee-green-resort",
                S("Jaypee Green Resort & Spa", "Jaypee Green Resort & Spa", "Jaypee Green Resort & Spa", "ジャイピー・グリーン・リゾート＆スパ"),
                S("A 10-foot work in pink serpentine, installed at Jaypee Green Resort & Spa, Greater Noida.",
                  "Un travail de 10 pieds en serpentine rose, installé au Jaypee Green Resort & Spa, Greater Noida.",
                  "Eine 10 Fuß hohe Arbeit in rosa Serpentin, im Jaypee Green Resort & Spa, Greater Noida.",
                  "グレーター・ノイダのジャイピー・グリーン・リゾート＆スパに設置した、高さ10フィートのピンクのサーペンティン。"),
                "murti", "—"),
            new("nityananda-janmastana",
                S("Nityananda Janmastana, West Bengal", "Nityananda Janmastana, Bengale-Occidental", "Nityananda Janmastana, Westbengalen", "西ベンガルのニトヤーナンダ・ジャンマスターナ"),
                S("Guru Ramakanta received an award for making the Nityananda Janmastana temple at West Bengal. The record shows the finished shrine, the stone under construction, and the interior pillars.",
                  "Guru Ramakanta a reçu un prix pour la réalisation du temple Nityananda Janmastana au Bengale-Occidental. Le dossier montre le sanctuaire achevé, la pierre en chantier et les piliers intérieurs.",
                  "Guru Ramakanta erhielt eine Auszeichnung für den Tempel Nityananda Janmastana in Westbengalen. Die Aufzeichnung zeigt den fertigen Schrein, den Stein im Bau und die inneren Pfeiler.",
                  "西ベンガルのニトヤーナンダ・ジャンマスターナ寺院の制作に対し、グル・ラマカンタが賞を受けました。完成した祠、工事中の石、内部の柱が記録にあります。"),
                "temple", "—"),
            new("shirdi-saibaba-mumbai",
                S("Shirdi Saibaba, Mumbai", "Shirdi Saibaba, Mumbai", "Shirdi Saibaba, Mumbai", "ムンバイのシールディ・サーイ・バーバー"),
                S("An 8-foot Shirdi Saibaba installed at Mumbai.",
                  "Un Shirdi Saibaba de 8 pieds installé à Mumbai.",
                  "Ein 8 Fuß hoher Shirdi Saibaba, in Mumbai aufgestellt.",
                  "ムンバイに設置した、高さ8フィートのシールディ・サーイ・バーバー。"),
                "murti", "—"),
            new("durga-mai-mumbai",
                S("Durga Mai, Mumbai", "Durga Mai, Mumbai", "Durga Mai, Mumbai", "ムンバイのドゥルガー・マーイ"),
                S("A 9-foot Durga Mai installed at FX Factory, Mumbai.",
                  "Une Durga Mai de 9 pieds installée à la FX Factory, à Mumbai.",
                  "Eine 9 Fuß hohe Durga Mai, in der FX Factory in Mumbai aufgestellt.",
                  "ムンバイのFXファクトリーに設置した、高さ9フィートのドゥルガー・マーイ。"),
                "murti", "—"),
            new("tirupati-balaji",
                S("Tirupati Balaji, Chhattisgarh", "Tirupati Balaji, Chhattisgarh", "Tirupati Balaji, Chhattisgarh", "チャッティースガルのティルパティ・バーラージー"),
                S("A 10-foot granite Tirupati Balaji installed by Ramakanta at Chhattisgarh.",
                  "Un Tirupati Balaji de granit de 10 pieds, installé par Ramakanta au Chhattisgarh.",
                  "Ein 10 Fuß hoher Tirupati Balaji aus Granit, von Ramakanta in Chhattisgarh aufgestellt.",
                  "チャッティースガルにラマカンタが設置した、高さ10フィートの花崗岩のティルパティ・バーラージー。"),
                "pillar", "—"),
            new("mormugao-port-goa",
                S("Mormugao Port Trust, Goa", "Mormugao Port Trust, Goa", "Mormugao Port Trust, Goa", "モルムガオ港湾公社、ゴア"),
                S("A 15-foot wall design in Khandolite for the Mormugao Port Trust, Goa.",
                  "Un dessin mural de 15 pieds en khandolite pour le Mormugao Port Trust, à Goa.",
                  "Ein 15 Fuß hoher Wandentwurf in Khandolit für den Mormugao Port Trust in Goa.",
                  "ゴアのモルムガオ港湾公社のための、カンドライトの15フィートの壁面。"),
                "frieze", "—"),
            new("ganapati-greater-noida",
                S("Ganapati, Greater Noida", "Ganapati, Greater Noida", "Ganapati, Greater Noida", "グレーター・ノイダのガナパティ"),
                S("A 7-foot Ganapati installed for Jaypee Associates at Greater Noida.",
                  "Un Ganapati de 7 pieds installé pour Jaypee Associates à Greater Noida.",
                  "Ein 7 Fuß hoher Ganapati für Jaypee Associates in Greater Noida.",
                  "グレーター・ノイダのジャイピー・アソシエーツに設置した、高さ7フィートのガナパティ。"),
                "murti", "—"),
            new("dancing-ganesh-delhi",
                S("Delhi Exhibition", "Exposition de Delhi", "Ausstellung Delhi", "デリー展"),
                S("A 5-foot dancing Ganesha with weapons, shown at the Delhi Exhibition.",
                  "Un Ganesha dansant de 5 pieds, avec des armes, présenté à l’exposition de Delhi.",
                  "Ein 5 Fuß hoher tanzender Ganesha mit Waffen, auf der Ausstellung in Delhi.",
                  "デリー展に出品した、武器を持つ高さ5フィートの舞うガネーシャ。"),
                "murti", "—"),
            new("salem-karnataka",
                S("Salem, Karnataka", "Salem, Karnataka", "Salem, Karnataka", "カルナータカ、サーレム"),
                S("Guru Ramakanta with Dr Muthu Kumar at Salem, Karnataka, beside a green and red Ganesha.",
                  "Guru Ramakanta avec le Dr Muthu Kumar à Salem, au Karnataka, auprès d’un Ganesha vert et rouge.",
                  "Guru Ramakanta mit Dr. Muthu Kumar in Salem, Karnataka, neben einem grün-roten Ganesha.",
                  "カルナータカ州サーレムで、緑と赤のガネーシャの傍らに立つグル・ラマカンタとムトゥ・クマール博士。"),
                "murti", "—"),
            new("temple-construction",
                S("Temple under construction", "Temple en construction", "Tempel im Bau", "建設中の寺院"),
                S("Guru Ramakanta at work during temple construction, on the dome, the finial and the courses of stone.",
                  "Guru Ramakanta au travail pendant la construction d’un temple, sur le dôme, l’épi et les assises de pierre.",
                  "Guru Ramakanta bei der Tempelbauarbeit, an Kuppel, Bekrönung und Steinschichten.",
                  "寺院の建設中、ドーム、頂華、石の段に向かうグル・ラマカンタ。"),
                "temple", "—"),
            new("heritage-gate-odisha",
                S("Largest stone heritage gate, Rourkela", "La plus grande porte patrimoniale, Rourkela", "Größtes steinernes Erbe-Tor, Rourkela", "ルールケラの最大の石の遺産門"),
                S("Odisha’s largest stone heritage gate, made by Guru Ramakanta at Vedabyasa, Rourkela.",
                  "La plus grande porte patrimoniale en pierre de l’Odisha, faite par Guru Ramakanta à Vedabyasa, Rourkela.",
                  "Odishas größtes steinernes Erbe-Tor, von Guru Ramakanta in Vedabyasa, Rourkela.",
                  "オディシャ最大の石の遺産門。ルールケラのヴェーダヴィヤーサでグル・ラマカンタが作りました。"),
                "gate", "—"),
            new("vedabyasa-rourkela",
                S("Vedabyasa and Ganesh, Rourkela", "Vedabyasa et Ganesh, Rourkela", "Vedabyasa und Ganesh, Rourkela", "ルールケラのヴェーダヴィヤーサとガネーシャ"),
                S("A 10-foot Rishi Vedabyasa and a 7-foot-6-inch Ganesh at Vedabyasa Park, Rourkela.",
                  "Un Rishi Vedabyasa de 10 pieds et un Ganesh de 7 pieds 6 pouces au parc Vedabyasa, Rourkela.",
                  "Ein 10 Fuß hoher Rishi Vedabyasa und ein 7 Fuß 6 Zoll hoher Ganesh im Vedabyasa-Park, Rourkela.",
                  "ルールケラのヴェーダヴィヤーサ公園の、高さ10フィートのリシと7フィート6インチのガネーシャ。"),
                "murti", "—"),
            new("saraswati-sastra",
                S("Saraswati, Sastra University", "Saraswati, université Sastra", "Saraswati, Sastra-Universität", "サストラ大学のサラスヴァティー"),
                S("A 10-foot Saraswati installed at Sastra University, Tamil Nadu.",
                  "Une Saraswati de 10 pieds installée à l’université Sastra, au Tamil Nadu.",
                  "Eine 10 Fuß hohe Saraswati an der Sastra-Universität in Tamil Nadu.",
                  "タミル・ナードゥのサストラ大学に設置した、高さ10フィートのサラスヴァティー。"),
                "murti", "—"),
            new("konark-wheel-station",
                S("Konark wheel, Bhubaneswar station", "Roue de Konark, gare de Bhubaneswar", "Konark-Rad, Bahnhof Bhubaneswar", "ブバネーシュワル駅のコナーラクの車輪"),
                S("A Konark wheel installed at Bhubaneswar Railway Station.",
                  "Une roue de Konark installée à la gare de Bhubaneswar.",
                  "Ein Konark-Rad am Bahnhof Bhubaneswar.",
                  "ブバネーシュワル駅に設置したコナーラクの車輪。"),
                "wheel", "—"),
            new("canara-bank-bhubaneswar",
                S("Canara Bank, Bhubaneswar", "Canara Bank, Bhubaneswar", "Canara Bank, Bhubaneswar", "ブバネーシュワルのカナラ銀行"),
                S("Statues installed at the Canara Bank Regional Office, Bhubaneswar.",
                  "Des statues installées au bureau régional de la Canara Bank, à Bhubaneswar.",
                  "Statuen im Regionalbüro der Canara Bank in Bhubaneswar.",
                  "ブバネーシュワルのカナラ銀行地域事務所に設置した像。"),
                "murti", "—"),
            new("siddhi-vinayak-delhi",
                S("Siddhi Vinayak, Delhi", "Siddhi Vinayak, Delhi", "Siddhi Vinayak, Delhi", "デリーのシッディ・ヴィナーヤカ"),
                S("A 15-foot Siddhi Vinayak carved at Delhi by Ramakanta and his students.",
                  "Un Siddhi Vinayak de 15 pieds taillé à Delhi par Ramakanta et ses élèves.",
                  "Ein 15 Fuß hoher Siddhi Vinayak, in Delhi von Ramakanta und seinen Schülern gehauen.",
                  "デリーでラマカンタと弟子たちが刻んだ、高さ15フィートのシッディ・ヴィナーヤカ。"),
                "murti", "—"),
            new("apsaras-mit-pune",
                S("Apsaras, MIT Pune", "Apsaras, MIT Pune", "Apsaras, MIT Pune", "プネーMITのアプサラス"),
                S("Idols of Urvashi, Menaka, Rambha and other apsaras at the MIT campus, Pune.",
                  "Idoles d’Urvashi, Menaka, Rambha et d’autres apsaras sur le campus du MIT, à Pune.",
                  "Idole von Urvashi, Menaka, Rambha und anderen Apsaras auf dem MIT-Campus in Pune.",
                  "プネーのMITキャンパスの、ウルヴァシー、メーナカー、ランバーほかアプサラスの像。"),
                "murti", "—"),
            new("sos-village-faridabad",
                S("SOS Village, Faridabad", "SOS Village, Faridabad", "SOS Village, Faridabad", "ファリダバードのSOSヴィレッジ"),
                S("Pink serpentine carving by Ramakanta, installed at SOS Village, Faridabad.",
                  "Une taille en serpentine rose de Ramakanta, installée au SOS Village, à Faridabad.",
                  "Eine Arbeit in rosa Serpentin von Ramakanta, im SOS Village in Faridabad.",
                  "ファリダバードのSOSヴィレッジに設置した、ラマカンタのピンクのサーペンティン。"),
                "murti", "—"),
            new("viswaroop-darsan",
                S("Viswaroop Darsan", "Viswaroop Darsan", "Viswaroop Darsan", "ヴィシュワループ・ダルシャン"),
                S("Viswa Rupa in natural onyx, carved by Ramakanta and recorded from several angles.",
                  "Viswa Rupa en onyx naturel, taillé par Ramakanta et consigné sous plusieurs angles.",
                  "Viswa Rupa in natürlichem Onyx, von Ramakanta gehauen und aus mehreren Blickwinkeln festgehalten.",
                  "天然オニックスのヴィシュワ・ルーパ。ラマカンタが刻み、いくつかの角度から記録。"),
                "peacock", "—"),
            new("dasavatara",
                S("Dasavatara", "Dasavatara", "Dasavatara", "ダシャーヴァターラ"),
                S("An eight-foot Dasa Avatar in a posture the atelier calls unique.",
                  "Un Dasa Avatar de huit pieds, dans une posture que l’atelier dit unique.",
                  "Ein acht Fuß hoher Dasa Avatar in einer Haltung, die das Atelier einzigartig nennt.",
                  "工房が独自の姿と記す、高さ8フィートのダシャーヴァターラ。"),
                "wheel", "—"),
            new("perumal-mandapam",
                S("Perumal Mandapam", "Perumal Mandapam", "Perumal Mandapam", "ペルマル・マンダパム"),
                S("A pillared hall treated as architecture, not as applied ornament.",
                  "Une salle à piliers traitée comme architecture, non comme ornement appliqué.",
                  "Eine Pfeilerhalle als Architektur, nicht als aufgesetzter Schmuck.",
                  "装飾ではなく建築として扱う柱の間。"),
                "pillar", "—")
        ]),
        new("japan", S("Japan", "Japon", "Japan", "日本"), 86, 38,
        [
            new("ashokan-pillar-japan",
                S("Ashokan pillar", "Pilier d’Ashoka", "Ashoka-Säule", "アショーカ石柱"),
                S("Installed in 1995. A Mauryan memory — shaft, capital, and emblem — carved in Odisha and set in Japan. This is the journey that opened the atelier’s international record.",
                  "Installé en 1995. Une mémoire maurya — fût, chapiteau, emblème — taillée en Odisha et posée au Japon. C’est le voyage qui ouvrit le registre international de l’atelier.",
                  "Aufgestellt 1995. Eine mauryanische Erinnerung — Schaft, Kapitell, Zeichen — in Odisha gehauen und in Japan gesetzt. Diese Reise öffnete den internationalen Nachweis des Ateliers.",
                  "1995年に設置。軸、柱頭、標章というマウリヤの記憶をオディシャで刻み、日本に据えました。工房の国際的な記録を開いた旅です。"),
                "pillar", "1995")
        ]),
        new("singapore", S("Singapore", "Singapour", "Singapur", "シンガポール"), 76, 58,
        [
            new("red-onyx-singapore",
                S("Red Onyx Ganesha, Singapore", "Ganesh en onyx rouge, Singapour", "Ganesha in rotem Onyx, Singapur", "シンガポールの赤オニキスのガネーシャ"),
                S("A 6-foot Red Onyx creation by Ramakanta, installed at Singapore.",
                  "Une création de 6 pieds en onyx rouge de Ramakanta, installée à Singapour.",
                  "Eine 6 Fuß hohe Arbeit in rotem Onyx von Ramakanta, in Singapur aufgestellt.",
                  "シンガポールに設置した、ラマカンタの高さ6フィートの赤オニキス。"),
                "murti", "—"),
            new("seven-temple-shrines-singapore",
                S("Temple work, Singapore", "Travail de temple, Singapour", "Tempelarbeit, Singapur", "シンガポールの寺院"),
                S("Shrines installed in Singapore, with Guru Ramakanta and his disciples fine-tuning the stone on site.",
                  "Des sanctuaires installés à Singapour, Guru Ramakanta et ses disciples ajustant la pierre sur place.",
                  "In Singapur aufgestellte Schreine. Guru Ramakanta und seine Schüler arbeiten den Stein vor Ort nach.",
                  "シンガポールに設置した祠堂。グル・ラマカンタと弟子たちが現地で石を整えます。"),
                "temple", "—"),
            new("sri-krishna-singapore",
                S("Sri Krishna temple, Singapore", "Temple de Sri Krishna, Singapour", "Sri-Krishna-Tempel, Singapur", "シュリー・クリシュナ寺院、シンガポール"),
                S("The stone-laying ceremony at the Sri Krishna temple, and the construction drawing shared with the temple trustee.",
                  "La cérémonie de pose de la pierre au temple de Sri Krishna, et le dessin de construction partagé avec le trustee du temple.",
                  "Die Grundsteinlegung am Sri-Krishna-Tempel und die Bauzeichnung, die dem Trustee des Tempels vorgelegt wurde.",
                  "シュリー・クリシュナ寺院の定礎と、寺院のトラスティに示した施工図。"),
                "temple", "—"),
            new("singapore-disciples",
                S("Disciples at the Singapore temple", "Disciples au temple de Singapour", "Schüler am Tempel in Singapur", "シンガポールの寺院の弟子たち"),
                S("Guru Ramakanta with his disciples, fine-tuning the temple work in Singapore.",
                  "Guru Ramakanta avec ses disciples, ajustant le travail de temple à Singapour.",
                  "Guru Ramakanta mit seinen Schülern bei der Feinarbeit am Tempel in Singapur.",
                  "シンガポールの寺院で、弟子たちと細部を整えるグル・ラマカンタ。"),
                "pillar", "—"),
            new("singapore-felicitation",
                S("Felicitation in Singapore", "Hommage à Singapour", "Ehrung in Singapur", "シンガポールでの顕彰"),
                S("A felicitation to Guru Ramakanta and his wife in Singapore.",
                  "Un hommage à Guru Ramakanta et à son épouse à Singapour.",
                  "Eine Ehrung für Guru Ramakanta und seine Frau in Singapur.",
                  "シンガポールで、グル・ラマカンタと妻への顕彰。"),
                "kalasha", "—")
        ]),
        new("italy", S("Italy", "Italie", "Italien", "イタリア"), 49, 40,
        [
            new("italy-commissions",
                S("European commissions", "Commandes européennes", "Europäische Aufträge", "欧州の注文"),
                S("Stone from the atelier has been prepared for patrons and sacred or private settings in Italy. This site does not attach a monument’s name beyond the country’s place in the international record. Photographs join the dossier when the archive is filed.",
                  "De la pierre de l’atelier a été préparée pour des commanditaires et des lieux sacrés ou privés en Italie. Ce site n’ajoute pas le nom d’un monument au-delà de la place du pays dans le registre. Les photographies rejoindront le dossier avec l’archive.",
                  "Stein des Ateliers wurde für Auftraggeber und sakrale oder private Orte in Italien vorbereitet. Diese Site setzt keinen Denkmalsnamen über den Platz des Landes im Register hinaus. Fotografien folgen mit dem Archiv.",
                  "工房の石が、イタリアのパトロンと、聖なる、または私的な場所のために準備されています。このサイトは、国際記録における国の位置を超えて、記念碑の名を付けません。写真はアーカイブとともに加わります。"),
                "frieze", "—")
        ]),
        new("thailand", S("Thailand", "Thaïlande", "Thailand", "タイ"), 75, 52,
        [
            new("thailand-installations",
                S("Southeast Asian installations", "Installations en Asie du Sud-Est", "Installationen in Südostasien", "東南アジアの設置"),
                S("Installations in Thailand sit within the atelier’s wider Asian practice, beside the named works in Japan and Singapore. Project photographs are reserved for the archive.",
                  "Les installations en Thaïlande prennent place dans la pratique asiatique de l’atelier, à côté des œuvres nommées au Japon et à Singapour.",
                  "Installationen in Thailand stehen in der weiteren asiatischen Praxis des Ateliers, neben den benannten Werken in Japan und Singapur.",
                  "タイの設置は、日本とシンガポールの名のある仕事と並ぶ、工房のアジアでの実践のなかにあります。"),
                "lotus", "—")
        ]),
        new("russia", S("Russia", "Russie", "Russland", "ロシア"), 62, 28,
        [
            new("russia-installations",
                S("Buddha for the Russian Museum", "Bouddha pour le musée russe", "Buddha für das Russische Museum", "ロシアの美術館のための仏陀"),
                S("A stele of Lord Buddha carved by Ramakanta for the Russian Museum.",
                  "Une stèle du Bouddha taillée par Ramakanta pour le musée russe.",
                  "Eine Stele des Buddha, von Ramakanta für das Russische Museum gehauen.",
                  "ロシアの美術館のためにラマカンタが刻んだ仏陀の石碑。"),
                "kalasha", "—")
        ]),
        new("usa", S("United States", "États-Unis", "Vereinigte Staaten", "米国"), 20, 40,
        [
            new("usa-collectors",
                S("Collectors and cultural spaces", "Collectionneurs et lieux culturels", "Sammler und kulturelle Räume", "蒐集家と文化の場"),
                S("Pieces for collectors and cultural spaces in the United States. The store and the quotation desk continue this line for museums and private rooms.",
                  "Des pièces pour des collectionneurs et des lieux culturels aux États-Unis. La boutique et le bureau des devis prolongent cette ligne.",
                  "Stücke für Sammler und kulturelle Räume in den Vereinigten Staaten. Kollektion und Angebotsstelle setzen diese Linie fort.",
                  "米国の蒐集家と文化の場のための作品。受注と見積は、美術館と私的な部屋に向けてこの線を続けます。"),
                "murti", "—")
        ]),
        new("israel", S("Israel", "Israël", "Israel", "イスラエル"), 56, 44,
        [
            new("israel-commissions",
                S("Sacred and private commissions", "Commandes sacrées et privées", "Sakrale und private Aufträge", "聖なる注文と私的な注文"),
                S("Commissions for sacred and private settings in Israel are part of the atelier’s international map. Names of rooms are added only from the archive.",
                  "Des commandes pour des lieux sacrés et privés en Israël font partie de la carte internationale. Les noms de salles ne viennent que de l’archive.",
                  "Aufträge für sakrale und private Orte in Israel gehören zur internationalen Karte. Namen von Räumen kommen nur aus dem Archiv.",
                  "イスラエルの聖なる場所と私的な場所への注文は、工房の国際地図の一部です。部屋の名はアーカイブからのみ加えます。"),
                "kalasha", "—")
        ])
    ];

    public static readonly IReadOnlyList<Course> Courses =
    [
        new("week",
            S("One-week cultural workshop", "Atelier culturel d’une semaine", "Einwöchige kulturelle Werkstatt", "一週間の文化講習"),
            S("7 days", "7 jours", "7 Tage", "7日"),
            S("An introduction to stone, tool and icon, for travellers and professionals with a short stay.",
              "Une introduction à la pierre, à l’outil et à l’icône, pour un court séjour.",
              "Eine Einführung in Stein, Werkzeug und Ikone für einen kurzen Aufenthalt.",
              "短い滞在の旅人と専門家のための、石、道具、図像への導入。")),
        new("month",
            S("One-month foundation", "Fondation d’un mois", "Einmonatige Grundlage", "一か月の基礎"),
            S("1 month", "1 mois", "1 Monat", "1か月"),
            S("Drawing, roughing and the first finished devotional study.",
              "Dessin, dégrossi, et une première étude de dévotion finie.",
              "Zeichnung, Schroten und eine erste vollendete Andachtsstudie.",
              "下絵、荒彫り、そして最初の仕上げた礼拝習作。")),
        new("quarter",
            S("Three-month traditional sculpting", "Sculpture traditionnelle, trois mois", "Drei Monate traditionelle Bildhauerei", "三か月の伝統彫刻"),
            S("3 months", "3 mois", "3 Monate", "3か月"),
            S("A sustained carving of one image, with temple drawing beside the bench.",
              "La taille soutenue d’une image, avec le dessin de temple près de l’établi.",
              "Eine anhaltende Arbeit an einem Bild, mit Tempelzeichnung neben der Bank.",
              "一つの像を継続して刻み、作業台の傍らで寺院図面を描きます。")),
        new("half",
            S("Six-month professional training", "Formation professionnelle de six mois", "Sechsmonatige professionelle Ausbildung", "六か月の専門訓練"),
            S("6 months", "6 mois", "6 Monate", "6か月"),
            S("For makers who intend to practise. Tool discipline, iconography and a completed work.",
              "Pour celles et ceux qui veulent pratiquer. Discipline de l’outil, iconographie, œuvre achevée.",
              "Für Menschen, die praktizieren wollen. Werkzeug, Ikonografie und ein vollendetes Werk.",
              "実践しようとする人のために。道具の規律、図像、完成した仕事。")),
        new("year",
            S("One-year master artisan fellowship", "Résidence de maître artisan, un an", "Einjähriges Meisterstipendium", "一年の名匠フェローシップ"),
            S("1 year", "1 an", "1 Jahr", "1年"),
            S("A year inside the atelier’s standard, ending with a fellowship piece and the academy certificate.",
              "Une année dans l’exigence de l’atelier, close par une pièce de résidence et le certificat.",
              "Ein Jahr im Maß des Ateliers, abgeschlossen mit einem Stipendienstück und dem Zertifikat.",
              "工房の基準のなかで一年。フェローシップの作品と学院の修了証で結びます。"))
    ];

    public static readonly IReadOnlyList<PressItem> Press =
    [
        new("cambridge-certificate",
            S("Certificate", "Certificat", "Urkunde", "証明書"),
            S("Bangalore Cambridge School", "Bangalore Cambridge School", "Bangalore Cambridge School", "バンガロール・ケンブリッジ・スクール"),
            S("Guru Ramakanta receiving a certificate from the trustee of Bangalore Cambridge School, beside a stone figure of the goddess.",
              "Guru Ramakanta recevant un certificat du trustee de la Bangalore Cambridge School, auprès d’une figure de pierre de la déesse.",
              "Guru Ramakanta erhält eine Urkunde vom Trustee der Bangalore Cambridge School, neben einer Steinfigur der Göttin.",
              "バンガロール・ケンブリッジ・スクールのトラスティから証明書を受け取るグル・ラマカンタ。傍らに女神の石像。"),
            "—"),
        new("buyer-seller-meet",
            S("Fair", "Foire", "Messe", "見本市"),
            S("Odisha Buyer Seller Meet", "Rencontre acheteurs-vendeurs de l’Odisha", "Odisha Buyer-Seller-Meet", "オディシャのバイヤー・セラー会合"),
            S("Guru Ramakanta at Odisha’s Buyer Seller Meet, with small stone figures set out on the tables.",
              "Guru Ramakanta à la rencontre acheteurs-vendeurs de l’Odisha, de petites figures de pierre disposées sur les tables.",
              "Guru Ramakanta beim Buyer-Seller-Meet von Odisha, mit kleinen Steinfiguren auf den Tischen.",
              "オディシャのバイヤー・セラー会合でのグル・ラマカンタ。卓上に小さな石の像が並びます。"),
            "—"),
        new("bengaluru-fair",
            S("Fair", "Foire", "Messe", "見本市"),
            S("International Fair, Bengaluru", "Foire internationale, Bengaluru", "Internationale Messe, Bengaluru", "ベンガルール国際見本市"),
            S("Guru Ramakanta with his creations at the International Fair of Bengaluru: a green and red Ganesha, a gilded shrine, a jewelled image, and a group of standing figures.",
              "Guru Ramakanta avec ses créations à la foire internationale de Bengaluru : un Ganesh vert et rouge, un sanctuaire doré, une image ornée, et un groupe de figures debout.",
              "Guru Ramakanta mit seinen Schöpfungen auf der Internationalen Messe in Bengaluru: ein grün-roter Ganesh, ein vergoldeter Schrein, ein geschmücktes Bild und eine Gruppe stehender Figuren.",
              "ベンガルール国際見本市で、自作と並ぶグル・ラマカンタ。緑と赤のガネーシャ、金の祠、宝飾の像、立つ群像。"),
            "—"),
        new("bengaluru-trade-fair",
            S("Fair", "Foire", "Messe", "見本市"),
            S("International Trade Fair, Bengaluru", "Foire commerciale internationale, Bengaluru", "Internationale Handelsmesse, Bengaluru", "ベンガルール国際交易会"),
            S("Ramakanta at the International Trade Fair, Bengaluru, with a green Ganesh, a pale shrine, a coloured pedestal, and a dark standing portrait in stone.",
              "Ramakanta à la foire commerciale internationale de Bengaluru, avec un Ganesh vert, un sanctuaire pâle, un piédestal coloré et un portrait debout en pierre sombre.",
              "Ramakanta auf der Internationalen Handelsmesse in Bengaluru, mit einem grünen Ganesh, einem hellen Schrein, einem farbigen Sockel und einem dunklen stehenden Bildnis aus Stein.",
              "ベンガルール国際交易会のラマカンタ。緑のガネーシャ、淡い祠、色石の台座、暗い石の立像。"),
            "—"),
        new("devotion-to-stone",
            S("Workshop", "Atelier", "Werkstatt", "工房"),
            S("Devotion to the sculptural work", "Dévotion au travail sculptural", "Hingabe an die bildhauerische Arbeit", "彫刻の仕事への献身"),
            S("The devotion to sculptural work by Ramakanta: carving a lion head before a standing image, and roughing a white figure on the workshop floor.",
              "La dévotion de Ramakanta au travail sculptural : la taille d’une tête de lion devant une figure debout, et le dégrossi d’une figure blanche sur le sol de l’atelier.",
              "Ramakantas Hingabe an die bildhauerische Arbeit: das Behauen eines Löwenkopfs vor einer stehenden Figur und das Schroten einer weißen Figur auf dem Werkstattboden.",
              "ラマカンタの彫刻への献身。立像の前で獅子の頭を刻み、工房の床で白い像を荒彫りします。"),
            "—"),
        new("kamalnath-visit",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Mr. Kamalnath, former minister", "M. Kamalnath, ancien ministre", "Herr Kamalnath, ehemaliger Minister", "元大臣カマルナート氏"),
            S("Mr. Kamalnath, former minister, appreciating the idol of Ganesh carved by Guru Ramakanta.",
              "M. Kamalnath, ancien ministre, appréciant l’idole de Ganesh taillée par Guru Ramakanta.",
              "Herr Kamalnath, ehemaliger Minister, vor dem von Guru Ramakanta gehauenen Ganesh.",
              "元大臣カマルナート氏が、グル・ラマカンタの刻んだガネーシャの像を見ておられます。"),
            "—"),
        new("baijayanti-mehta",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Smt. Baijayanti Ben Mehta at the workshop", "Smt. Baijayanti Ben Mehta à l’atelier", "Smt. Baijayanti Ben Mehta in der Werkstatt", "工房のバイジャヤンティ・ベン・メータ女史"),
            S("Guru Ramakanta with Smt. Baijayanti Ben Mehta, former Energy Minister, Government of India, at his workshop in Bhubaneswar.",
              "Guru Ramakanta avec Smt. Baijayanti Ben Mehta, ancienne ministre de l’Énergie du gouvernement de l’Inde, à son atelier de Bhubaneswar.",
              "Guru Ramakanta mit Smt. Baijayanti Ben Mehta, ehemalige Energieministerin der indischen Regierung, in seiner Werkstatt in Bhubaneswar.",
              "インド政府の元エネルギー大臣、バイジャヤンティ・ベン・メータ女史と、ブバネーシュワルの工房でのグル・ラマカンタ。"),
            "—"),
        new("shantmanu-visit",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Sri Shantmanu, IAS", "Sri Shantmanu, IAS", "Sri Shantmanu, IAS", "シュリー・シャントマヌ、IAS"),
            S("Sri Shantmanu, IAS, Development Commissioner for Handicrafts, Government of India, visited the workshop-cum-showroom of Guru Ramakanta.",
              "Sri Shantmanu, IAS, commissaire au développement de l’artisanat, gouvernement de l’Inde, a visité l’atelier-galerie de Guru Ramakanta.",
              "Sri Shantmanu, IAS, Development Commissioner for Handicrafts der indischen Regierung, besuchte Werkstatt und Schauraum von Guru Ramakanta.",
              "インド政府手工芸開発長官のIAS、シュリー・シャントマヌ氏が、グル・ラマカンタの工房兼展示室を訪れました。"),
            "—"),
        new("chaturvedi-visit",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Shri T. N. Chaturvedi", "Shri T. N. Chaturvedi", "Shri T. N. Chaturvedi", "シュリー・T・N・チャトゥルヴェーディー"),
            S("Guru Ramakanta with Shri T. N. Chaturvedi, former Governor of Karnataka.",
              "Guru Ramakanta avec Shri T. N. Chaturvedi, ancien gouverneur du Karnataka.",
              "Guru Ramakanta mit Shri T. N. Chaturvedi, ehemaliger Gouverneur von Karnataka.",
              "カルナータカ州の元知事、シュリー・T・N・チャトゥルヴェーディー氏とグル・ラマカンタ。"),
            "—"),
        new("surya-narayan-patra",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Sj. Surya Narayan Patra at Pragati Maidan", "Sj. Surya Narayan Patra à Pragati Maidan", "Sj. Surya Narayan Patra in Pragati Maidan", "プラガティ・マイダンのスルヤ・ナラヤン・パトラ氏"),
            S("Former minister Sj. Surya Narayan Patra visiting the stall of Guru Ramakanta at Pragati Maidan, New Delhi.",
              "L’ancien ministre Sj. Surya Narayan Patra visitant le stand de Guru Ramakanta à Pragati Maidan, New Delhi.",
              "Der ehemalige Minister Sj. Surya Narayan Patra am Stand von Guru Ramakanta in Pragati Maidan, Neu-Delhi.",
              "元大臣スルヤ・ナラヤン・パトラ氏が、ニューデリーのプラガティ・マイダンでグル・ラマカンタのブースを訪れています。"),
            "—"),
        new("kb-singh",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Shri K. B. Singh", "Shri K. B. Singh", "Shri K. B. Singh", "シュリー・K・B・シン"),
            S("Guru Ramakanta with Shri K. B. Singh, former Director General of Odisha.",
              "Guru Ramakanta avec Shri K. B. Singh, ancien directeur général de l’Odisha.",
              "Guru Ramakanta mit Shri K. B. Singh, ehemaliger Generaldirektor von Odisha.",
              "オディシャの元長官、シュリー・K・B・シン氏とグル・ラマカンタ。"),
            "—"),
        new("dg-police-visit",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Former Director General of Police", "Ancien directeur général de la police", "Ehemaliger Generaldirektor der Polizei", "元警察長官"),
            S("Guru Ramakanta with a former Director General of Police, in the showroom among the stone figures.",
              "Guru Ramakanta avec un ancien directeur général de la police, dans la galerie, parmi les figures de pierre.",
              "Guru Ramakanta mit einem ehemaligen Generaldirektor der Polizei, im Schauraum zwischen den Steinfiguren.",
              "元警察長官と、石の像が並ぶ展示室でのグル・ラマカンタ。"),
            "—"),
        new("au-singh-deo",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Mr. A. U. Singh Deo and Mr. Damodar Rout", "M. A. U. Singh Deo et M. Damodar Rout", "Herr A. U. Singh Deo und Herr Damodar Rout", "A・U・シン・デオ氏とダモダル・ラウト氏"),
            S("Mr. A. U. Singh Deo, former MP and former minister, and Mr. Damodar Rout, visiting the stall at Pragati Maidan, New Delhi.",
              "M. A. U. Singh Deo, ancien député et ancien ministre, et M. Damodar Rout, visitant le stand à Pragati Maidan, New Delhi.",
              "Herr A. U. Singh Deo, ehemaliger Abgeordneter und Minister, und Herr Damodar Rout am Stand in Pragati Maidan, Neu-Delhi.",
              "元下院議員・元大臣のA・U・シン・デオ氏とダモダル・ラウト氏が、ニューデリーのプラガティ・マイダンのブースを訪れています。"),
            "—"),
        new("ajay-kumar-devlok",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Mr. K. Ajay Kumar, Devlok", "M. K. Ajay Kumar, Devlok", "Herr K. Ajay Kumar, Devlok", "デヴロークのK・アジャイ・クマール氏"),
            S("Ramakanta with Mr. K. Ajay Kumar, Managing Director of Devlok, in Andhra Pradesh.",
              "Ramakanta avec M. K. Ajay Kumar, directeur général de Devlok, en Andhra Pradesh.",
              "Ramakanta mit Herrn K. Ajay Kumar, Geschäftsführer von Devlok, in Andhra Pradesh.",
              "アンドラ・プラデーシュで、デヴロークの専務K・アジャイ・クマール氏とラマカンタ。"),
            "—"),
        new("ashutosh-muni",
            S("Visit", "Visite", "Besuch", "来訪"),
            S("Shri Ashutosh Muni", "Shri Ashutosh Muni", "Shri Ashutosh Muni", "シュリー・アシュトーシュ・ムニ"),
            S("Shri Ashutosh Muni, founder of the Ashutosh Muni Foundation, Vergina, USA, with Guru Ramakanta at the Bhubaneswar workshop.",
              "Shri Ashutosh Muni, fondateur de l’Ashutosh Muni Foundation, Vergina, États-Unis, avec Guru Ramakanta à l’atelier de Bhubaneswar.",
              "Shri Ashutosh Muni, Gründer der Ashutosh Muni Foundation, Vergina, USA, mit Guru Ramakanta in der Werkstatt in Bhubaneswar.",
              "米国ヴァージナのアシュトーシュ・ムニ財団の創設者、シュリー・アシュトーシュ・ムニ師と、ブバネーシュワルの工房でのグル・ラマカンタ。"),
            "—"),
        new("guru-purnima",
            S("Academy", "Académie", "Akademie", "学院"),
            S("Guru Purnima", "Guru Purnima", "Guru Purnima", "グル・プールニマー"),
            S("The students offer puja to their Guru Ramakanta on Guru Purnima.",
              "Les élèves offrent la puja à leur Guru Ramakanta à Guru Purnima.",
              "Die Schüler bringen ihrem Guru Ramakanta an Guru Purnima die Puja dar.",
              "グル・プールニマーに、弟子たちが師ラマカンタへプージャを捧げます。"),
            "—"),
        new("nityananda-award",
            S("Temple", "Temple", "Tempel", "寺院"),
            S("Nityananda Janmastana, West Bengal", "Nityananda Janmastana, Bengale-Occidental", "Nityananda Janmastana, Westbengalen", "西ベンガルのニトヤーナンダ・ジャンマスターナ"),
            S("Guru Ramakanta receiving an award for making the Nityananda Janmastana temple at West Bengal. The photographs show the shrine, the stone under construction, and the finished towers.",
              "Guru Ramakanta recevant un prix pour la réalisation du temple Nityananda Janmastana au Bengale-Occidental. Les photographies montrent le sanctuaire, la pierre en chantier et les tours achevées.",
              "Guru Ramakanta erhält eine Auszeichnung für den Tempel Nityananda Janmastana in Westbengalen. Die Aufnahmen zeigen den Schrein, den Stein im Bau und die fertigen Türme.",
              "西ベンガルのニトヤーナンダ・ジャンマスターナ寺院の制作に対する受賞。祠、工事中の石、完成した塔が写真に残ります。"),
            "—"),
        new("nityananda-interior",
            S("Temple", "Temple", "Tempel", "寺院"),
            S("Interior stone, Nityananda Janmastana", "Pierre intérieure, Nityananda Janmastana", "Innenstein, Nityananda Janmastana", "ニトヤーナンダ・ジャンマスターナの内部の石"),
            S("Interior stone works of Guru Ramakanta at Nityananda Janmastana, West Bengal: carved pillars, arches, and the hall they hold.",
              "Travaux de pierre intérieure de Guru Ramakanta à Nityananda Janmastana, Bengale-Occidental : piliers sculptés, arcs et la salle qu’ils portent.",
              "Innere Steinausstattung von Guru Ramakanta in Nityananda Janmastana, Westbengalen: geschnitzte Pfeiler, Bögen und die Halle, die sie tragen.",
              "西ベンガル、ニトヤーナンダ・ジャンマスターナにおけるグル・ラマカンタの内部石造。彫られた柱、アーチ、それらが支える広間。"),
            "—"),
        new("interviews",
            S("Interviews", "Entretiens", "Interviews", "インタビュー"),
            S("Conversations with the master", "Conversations avec le maître", "Gespräche mit dem Meister", "名匠との対話"),
            S("Interviews are listed as the archive receives them. The public facts they rest on are the biography: Puri, the cooperative, Japan, the National Award, the emporium, and the teaching of more than a thousand artisans.",
              "Les entretiens seront listés à mesure de l’archive. Les faits publics sur lesquels ils reposent sont la biographie.",
              "Interviews werden gelistet, sobald das Archiv sie aufnimmt. Die öffentlichen Tatsachen sind die Biografie.",
              "インタビューはアーカイブが受け取るたびに掲げます。その土台となる公の事実は経歴にあります。"),
            "—"),
        new("news",
            S("News coverage", "Couverture de presse", "Berichterstattung", "報道"),
            S("Notices of awards and installations", "Échos des prix et des installations", "Notizen zu Preisen und Installationen", "賞と設置の知らせ"),
            S("The coverage this site can vouch for is the sequence of honours and installations already dated: 1990, 1995, 1997, 2005, 2006, 2016 and the 2024 nomination.",
              "La couverture que ce site peut garantir est la suite des honneurs et installations déjà datée.",
              "Was diese Site verbürgen kann, ist die bereits datierte Folge der Ehrungen und Installationen.",
              "このサイトが請け合える報道は、すでに年を付した栄誉と設置の列です。"),
            "—"),
        new("documentaries",
            S("Documentaries", "Documentaires", "Dokumentarfilme", "記録映画"),
            S("Film of the workshop", "Film de l’atelier", "Film der Werkstatt", "工房の映像"),
            S("A documentary chapter will hold the atelier film when it is released. Until then the 360° workshop is the spatial account of a working day.",
              "Un chapitre documentaire accueillera le film de l’atelier lorsqu’il sera publié. D’ici là, l’atelier à 360° est le récit spatial d’une journée.",
              "Ein Dokumentarkapitel nimmt den Film des Ateliers auf, sobald er vorliegt. Bis dahin ist die 360°-Werkstatt der räumliche Bericht eines Arbeitstags.",
              "記録映画の章は、工房の映像が公開されたときにそれを収めます。それまでは、360°の工房が一日の空間的な記録です。"),
            "—"),
        new("padma-story",
            S("Padma Shri nomination", "Nomination Padma Shri", "Padma-Shri-Nominierung", "パドマ・シュリー推薦"),
            S("The 2024 nomination story", "Le récit de la nomination de 2024", "Die Geschichte der Nominierung 2024", "2024年の推薦の物語"),
            S("In 2024 the atelier gathered its record — temple work, international installation, and the training of artisans — for a Padma Shri nomination. The nomination profile on this site is that gathering. It is a proposal for honour, not the honour itself.",
              "En 2024 l’atelier a réuni son registre pour une nomination Padma Shri. Le profil sur ce site est ce rassemblement. C’est une proposition d’honneur, non l’honneur lui-même.",
              "2024 stellte das Atelier seinen Nachweis für eine Padma-Shri-Nominierung zusammen. Das Profil auf dieser Site ist diese Sammlung. Es ist ein Vorschlag der Ehre, nicht die Ehre selbst.",
              "2024年、工房は寺院の仕事、国外設置、職人育成の記録をパドマ・シュリー推薦のために集めました。このサイトのプロフィールがその集成です。栄誉への提案であり、栄誉そのものではありません。"),
            "2024"),
        new("exhibitions",
            S("Exhibitions", "Expositions", "Ausstellungen", "展覧会"),
            S("Invitations and rooms", "Invitations et salles", "Einladungen und Räume", "招聘と会場"),
            S("Museums and cultural rooms wishing to exhibit the work write through the contact desk, under “Invite an exhibition”. Past rooms are added by name only when the archive confirms them.",
              "Musées et salles culturelles écrivent par le bureau de contact, sous « Inviter une exposition ». Les salles passées ne sont nommées que si l’archive le confirme.",
              "Museen und kulturelle Räume schreiben über den Kontakt, unter „Eine Ausstellung einladen“. Vergangene Räume werden nur genannt, wenn das Archiv sie bestätigt.",
              "作品を展覧したい美術館と文化の部屋は、連絡の「展覧会を招く」から書いてください。過去の会場は、アーカイブが確かめたときにのみ名を置きます。"),
            "—")
    ];

    public static readonly IReadOnlyList<TourRoom> Rooms =
    [
        new("threshold",
            S("Threshold", "Seuil", "Schwelle", "閾"),
            S("You enter as a visitor enters a temple compound: slowly, and by a gate. The atelier’s gate work, including the large heritage gateway in Odisha, is the idea of this room.",
              "On entre comme dans l’enceinte d’un temple : lentement, et par une porte.",
              "Man tritt ein, wie man einen Tempelbezirk betritt: langsam, und durch ein Tor.",
              "寺院の境内に入るように、ゆっくりと、門から入ります。"),
            "gate", "/masterpieces/heritage-gate-odisha"),
        new("image",
            S("Sacred image", "Image sacrée", "Heiliges Bild", "聖像"),
            S("Ganesha, Krishna, Jagannath, the Dasavatara and Viswaroop. The image is not decoration of a religion. It is the religion’s proportion, cut in stone.",
              "Ganesha, Krishna, Jagannath, le Dasavatara et le Viswaroop. L’image n’est pas un décor : elle est la proportion, taillée.",
              "Ganesha, Krishna, Jagannath, das Dasavatara und Viswaroop. Das Bild ist nicht Dekor. Es ist die Proportion, in Stein geschnitten.",
              "ガネーシャ、クリシュナ、ジャガンナート、ダシャーヴァターラ、ヴィシュワループ。像は装飾ではなく、石に刻んだ比例です。"),
            "murti", "/masterpieces"),
        new("temple",
            S("Temple", "Temple", "Tempel", "寺院"),
            S("Pillars, mandapams, wheels and shrines. Architectural stone is judged by whether a building can trust it.",
              "Piliers, mandapams, roues et sanctuaires. La pierre d’architecture se juge à la confiance qu’un bâtiment peut lui donner.",
              "Pfeiler, Mandapams, Räder und Schreine. Architekturstein wird daran gemessen, ob ein Bau ihm trauen kann.",
              "柱、マンダパム、車輪、祠堂。建築石材は、建物がそれを信頼できるかで判断します。"),
            "temple", "/masterpieces?kind=architecture"),
        new("world",
            S("The world", "Le monde", "Die Welt", "世界"),
            S("Japan in 1995, Singapore’s seven shrines, and the wider map of eight countries.",
              "Le Japon en 1995, les sept sanctuaires de Singapour, et la carte de huit pays.",
              "Japan 1995, die sieben Schreine Singapurs und die Karte von acht Ländern.",
              "1995年の日本、シンガポールの七祠堂、そして八つの国の地図。"),
            "pillar", "/global-projects"),
        new("teaching",
            S("Teaching floor", "Salle d’enseignement", "Unterricht", "教える床"),
            S("More than a thousand artisans. The academy keeps that duty open to students from outside India.",
              "Plus de mille artisans. L’académie tient ce devoir ouvert aux étudiants venus d’ailleurs.",
              "Mehr als tausend Handwerker. Die Akademie hält diese Pflicht offen für Studierende von außerhalb.",
              "千人を超える職人。学院は、インドの外から来る学生にもその義務を開いています。"),
            "conch", "/academy"),
        new("honour",
            S("Honour wall", "Mur des honneurs", "Ehrenwand", "栄誉の壁"),
            S("1990, 1997, 2005, and the 2024 nomination, which remains a nomination.",
              "1990, 1997, 2005, et la nomination de 2024, qui reste une nomination.",
              "1990, 1997, 2005 und die Nominierung von 2024, die eine Nominierung bleibt.",
              "1990年、1997年、2005年、そして推薦のままである2024年の推薦。"),
            "kalasha", "/awards")
    ];

    public static readonly IReadOnlyList<Station> Stations =
    [
        new("yard",
            S("Stone yard", "Cour des blocs", "Steinhof", "石置き場"),
            S("Blocks wait to be read. Colour, grain and sound under the hammer decide whether a stone may become an image.",
              "Les blocs attendent d’être lus. Couleur, fil et son sous le marteau décident.",
              "Blöcke warten darauf, gelesen zu werden. Farbe, Lager und Klang unter dem Hammer entscheiden.",
              "石は読まれるのを待っています。色、石目、槌の下の音が、像になり得るかを決めます。"),
            "pillar"),
        new("drawing",
            S("Drawing floor", "Salle de dessin", "Zeichensaal", "下絵の床"),
            S("Proportion is drawn before pride enters the chisel. Temple plans sit beside icon drawings.",
              "La proportion est dessinée avant que l’orgueil n’entre dans le ciseau.",
              "Die Proportion wird gezeichnet, bevor Stolz in den Meißel fährt.",
              "誇りが鑿に入る前に、比例を描きます。寺院の図面は図像の傍らにあります。"),
            "frieze"),
        new("bay",
            S("Carving bay", "Baie de taille", "Hauhalle", "彫りの間"),
            S("The working day is the sound of many chisels. Roughing opens the block; the face comes last.",
              "La journée est le son de nombreux ciseaux. Le dégrossi ouvre le bloc ; le visage vient en dernier.",
              "Der Tag ist der Klang vieler Meißel. Schroten öffnet den Block; das Gesicht kommt zuletzt.",
              "一日は、多くの鑿の音です。荒彫りが石を開き、顔は最後に来ます。"),
            "murti"),
        new("colour",
            S("Patchwork table", "Table de patchwork", "Patchwork-Tisch", "パッチワークの台"),
            S("Stones of different colour are fitted so the joint is structure, not a crack.",
              "Des pierres de couleurs différentes sont ajustées pour que le joint soit structure, non une fissure.",
              "Steine verschiedener Farbe werden so gefügt, dass die Fuge Struktur ist, kein Riss.",
              "異なる色の石を、継ぎ目が亀裂ではなく構造になるように嵌めます。"),
            "peacock"),
        new("finish",
            S("Finishing", "Finition", "Vollendung", "仕上げ"),
            S("Light is the last tool. A surface is finished when it describes the form without shouting.",
              "La lumière est le dernier outil. Une surface est finie lorsqu’elle décrit la forme sans crier.",
              "Licht ist das letzte Werkzeug. Eine Oberfläche ist vollendet, wenn sie die Form beschreibt, ohne zu schreien.",
              "光が最後の道具です。叫ばずに形を語るとき、表面は仕上がっています。"),
            "lotus"),
        new("desk",
            S("Temple desk", "Table de temple", "Tempeltisch", "寺院の机"),
            S("Plans, elevations and letters from patrons. A shrine is agreed on paper before it is agreed in stone.",
              "Plans, élévations et lettres. Un sanctuaire est convenu sur le papier avant de l’être dans la pierre.",
              "Pläne, Aufrisse und Briefe. Ein Schrein wird auf Papier verabredet, bevor er im Stein verabredet wird.",
              "図面、立面、パトロンの書簡。祠堂は、石で決まる前に紙の上で決まります。"),
            "temple")
    ];
}
