namespace MahapatraArts.Services;

public static class ContentStore
{
    private static LStr S(string en, string fr, string de, string ja) => new(en, fr, de, ja);
    private static LStr Scale(string en, string fr, string de, string ja) => S(en, fr, de, ja);

    public static readonly IReadOnlyList<Product> Products =
    [
        new("seated-ganesha", "ganesha",
            S("Seated Ganesha", "Ganesha assis", "Sitzender Ganesha", "坐像のガネーシャ"),
            S("A seated Ganesha for a domestic shrine or a museum vitrine, carved to be read in the round.",
              "Un Ganesha assis pour un sanctuaire domestique ou une vitrine, taillé pour être lu en ronde-bosse.",
              "Ein sitzender Ganesha für einen Hausschrein oder eine Vitrine, rundansichtig gearbeitet.",
              "家庭の祭壇や陳列のための坐像。周囲から読める丸彫り。"),
            "Granite", Scale("From 45 cm", "Dès 45 cm", "Ab 45 cm", "45cmから"), 85000m, "murti", false),
        new("dancing-ganesha", "ganesha",
            S("Dancing Ganesha", "Ganesha dansant", "Tanzender Ganesha", "踊るガネーシャ"),
            S("Nritya Ganesha, the weight of the body kept light, for a hall that can take a larger presence.",
              "Nritya Ganesha, le poids du corps gardé léger, pour une salle qui peut recevoir une présence plus grande.",
              "Nritya Ganesha, das Gewicht des Körpers leicht gehalten, für einen Saal, der eine größere Gegenwart tragen kann.",
              "踊るガネーシャ。身体の重さを軽く保ち、より大きな存在を受けられる間のために。"),
            "Sandstone", Scale("From 60 cm", "Dès 60 cm", "Ab 60 cm", "60cmから"), 120000m, "peacock", false),
        new("venugopala", "krishna",
            S("Venugopala", "Venugopala", "Venugopala", "ヴェーヌゴーパーラ"),
            S("Krishna with the flute. The silence around the instrument is part of the carving.",
              "Krishna à la flûte. Le silence autour de l’instrument fait partie de la taille.",
              "Krishna mit der Flöte. Die Stille um das Instrument gehört zur Arbeit.",
              "笛を持つクリシュナ。楽器の周りの静けさも彫りの一部です。"),
            "Sandstone", Scale("From 50 cm", "Dès 50 cm", "Ab 50 cm", "50cmから"), 95000m, "conch", false),
        new("govardhana-krishna", "krishna",
            S("Govardhana Krishna", "Krishna Govardhana", "Govardhana Krishna", "ゴーヴァルダナのクリシュナ"),
            S("The mountain lifted. A study in weight, for patrons who want the narrative rather than the portrait alone.",
              "La montagne soulevée. Une étude de poids, pour qui veut le récit et non le seul portrait.",
              "Der gehobene Berg. Eine Studie des Gewichts, für Auftraggeber, die die Erzählung wollen.",
              "掲げられた山。肖像だけではなく物語を求める人のための、重さの習作。"),
            "Sandstone", Scale("From 75 cm", "Dès 75 cm", "Ab 75 cm", "75cmから"), 140000m, "kalasha", false),
        new("lotus-ceiling", "decor",
            S("Lotus ceiling", "Plafond de lotus", "Lotosdecke", "蓮の天井"),
            S("A lotus coffer for a mandapam or a private shrine room. Quoted with the architecture it has to fit.",
              "Un caisson de lotus pour un mandapam ou une salle de sanctuaire. Devisé avec l’architecture qu’il doit épouser.",
              "Eine Lotoskassette für ein Mandapam oder einen Schreinraum. Angeboten mit der Architektur, in die sie passen muss.",
              "マンダパムや私的な祠の間のための蓮の格天井。収まる建築とともに見積もります。"),
            "Sandstone", Scale("Architectural, on application", "Architecture, sur demande", "Architektonisch, auf Anfrage", "建築、照会"), null, "lotus", true),
        new("torana-panel", "decor",
            S("Torana panel", "Panneau de torana", "Torana-Tafel", "トーラナのパネル"),
            S("A ceremonial arch panel: guardians, floral meander, and a threshold you can pass in the mind if not yet in the building.",
              "Un panneau d’arc cérémoniel : gardiens, méandre floral, et un seuil.",
              "Eine Tafel des zeremoniellen Bogens: Wächter, floraler Mäander und eine Schwelle.",
              "儀式のアーチのパネル。守護、花の文様、そして閾。"),
            "Sandstone", Scale("Architectural, on application", "Architecture, sur demande", "Architektonisch, auf Anfrage", "建築、照会"), null, "gate", true),
        new("commission-sacred", "custom",
            S("Sacred commission", "Commande sacrée", "Sakraler Auftrag", "聖なる注文"),
            S("A deity, a donor portrait in the traditional sense, or a shrine element drawn for a site. The quotation begins with a letter, not a basket.",
              "Une divinité, ou un élément de sanctuaire dessiné pour un site. Le devis commence par une lettre.",
              "Eine Gottheit oder ein Schreinglied, für einen Ort gezeichnet. Das Angebot beginnt mit einem Brief.",
              "神、または敷地のために描く祠の部材。見積は書簡から始まります。"),
            "Sandstone or granite", Scale("To the site", "Selon le site", "Nach dem Ort", "敷地に合わせて"), null, "temple", true),
        new("lion-guardian", "garden",
            S("Lion guardian", "Gardien lion", "Löwenwächter", "獅子の守護"),
            S("A lion for a gate or a garden axis. The body is architectural: it has to sit in weather.",
              "Un lion pour un portail ou l’axe d’un jardin. Le corps est architectural : il doit tenir au temps.",
              "Ein Löwe für ein Tor oder eine Gartenachse. Der Körper ist architektonisch: er muss im Wetter sitzen.",
              "門や庭の軸のための獅子。身体は建築です。風雨のなかに座らなければなりません。"),
            "Granite", Scale("From 90 cm", "Dès 90 cm", "Ab 90 cm", "90cmから"), 160000m, "gate", false),
        new("elephant-guardian", "garden",
            S("Elephant guardian", "Gardien éléphant", "Elefantenwächter", "象の守護"),
            S("An elephant in the round for a garden or a museum court, with the patience of a large block.",
              "Un éléphant en ronde-bosse pour un jardin ou une cour de musée.",
              "Ein Elefant im Rund für einen Garten oder einen Museumshof.",
              "庭や美術館の中庭のための、丸彫りの象。大きな石の忍耐とともに。"),
            "Granite", Scale("From 110 cm", "Dès 110 cm", "Ab 110 cm", "110cmから"), 180000m, "pillar", false),
        new("ashokan-capital-study", "museum",
            S("Ashokan capital study", "Étude de chapiteau d’Ashoka", "Studie eines Ashoka-Kapitells", "アショーカ柱頭の習作"),
            S("A museum-scale study of the lion capital, related to the 1995 pillar in Japan. It is a study from the atelier, not a state replica presented as antique.",
              "Une étude à l’échelle de musée du chapiteau aux lions, liée au pilier de 1995 au Japon. C’est une étude de l’atelier, non une antiquité.",
              "Eine Studie im Museumsmaß des Löwenkapitells, verwandt mit der Säule von 1995 in Japan. Eine Atelierstudie, kein Altertum.",
              "獅子柱頭の、美術館規模の習作。1995年の日本の石柱に連なります。工房の習作であり、古物として出す国家の複製ではありません。"),
            "Sandstone", Scale("Study, from 40 cm", "Étude, dès 40 cm", "Studie, ab 40 cm", "習作、40cmから"), 110000m, "pillar", false),
        new("konark-wheel-study", "museum",
            S("Konark wheel study", "Étude de roue de Konark", "Konark-Rad-Studie", "コナーラクの車輪の習作"),
            S("A wheel carved as a study for a gallery or a teaching collection. The geometry is the subject.",
              "Une roue taillée comme étude pour une galerie ou une collection d’enseignement. La géométrie est le sujet.",
              "Ein Rad als Studie für eine Galerie oder eine Lehrsammlung. Die Geometrie ist das Thema.",
              "ギャラリーや教育収蔵のための車輪の習作。主題は幾何です。"),
            "Khandolite", Scale("Study, from 40 cm", "Étude, dès 40 cm", "Studie, ab 40 cm", "習作、40cmから"), 90000m, "wheel", false),
        new("viswaroop-study", "premium",
            S("Viswaroop study", "Étude du Viswaroop", "Viswaroop-Studie", "ヴィシュワループの習作"),
            S("A reduced vision of the cosmic form for a collector or a museum, using patchwork where the full work does. Price follows the number of stones.",
              "Une vision réduite de la forme cosmique. Le prix suit le nombre de pierres.",
              "Eine reduzierte Vision der kosmischen Form. Der Preis folgt der Zahl der Steine.",
              "宇宙の姿の縮小された顕現。価格は石の数に従います。"),
            "Multi-coloured stone", Scale("Collector’s scale, on application", "Échelle de collection, sur demande", "Im Sammlermaß, auf Anfrage", "蒐集の規模、照会"), null, "peacock", true),
        new("dasavatara-panel", "premium",
            S("Dasavatara panel", "Panneau du Dasavatara", "Dasavatara-Tafel", "ダシャーヴァターラのパネル"),
            S("The ten avatars in one panel for a long wall. Commissioned to the length of the room.",
              "Les dix avatars en un panneau pour un long mur. Commandé à la longueur de la salle.",
              "Die zehn Avatare in einer Tafel für eine lange Wand. In der Länge des Raums beauftragt.",
              "長い壁のための、十の化身を一つのパネルに。部屋の長さに合わせて受注します。"),
            "Sandstone", Scale("To the wall", "Selon le mur", "Nach der Wand", "壁に合わせて"), null, "wheel", true),
        new("narrative-frieze", "panels",
            S("Narrative frieze", "Frise narrative", "Erzählfries", "物語のフリーズ"),
            S("A Ramayana or regional narrative cut as architectural panels, crated in sequence.",
              "Un récit du Ramayana ou régional, taillé en panneaux d’architecture, mis en caisse dans l’ordre.",
              "Eine Ramayana- oder regionale Erzählung als Architekturplatten, der Reihe nach verpackt.",
              "ラーマーヤナまたは土地の物語を、建築パネルとして順に梱包します。"),
            "Sandstone", Scale("By the bay", "À la travée", "Nach dem Feld", "スパンごと"), null, "frieze", true),
        new("pillar-set", "panels",
            S("Pillar set", "Jeu de piliers", "Pfeilersatz", "柱の一組"),
            S("A pair or a hall of pillars with capitals, designed with the architect. Structural advice is part of the quotation.",
              "Une paire ou une salle de piliers à chapiteaux, conçue avec l’architecte. L’avis structurel fait partie du devis.",
              "Ein Paar oder eine Halle von Pfeilern mit Kapitellen, mit dem Architekten entworfen. Der strukturelle Rat ist Teil des Angebots.",
              "柱頭のある柱を、対または間として、建築家とともに設計します。構造の助言は見積の一部です。"),
            "Granite", Scale("Architectural, on application", "Architecture, sur demande", "Architektonisch, auf Anfrage", "建築、照会"), null, "pillar", true)
    ];
}
