namespace MahapatraArts.Services;

public static class ContentWorld
{
    private static LStr S(string en, string fr, string de, string ja) => new(en, fr, de, ja);

    public static readonly IReadOnlyList<Destination> Destinations =
    [
        new("india", S("India", "Inde", "Indien", "インド"), 68, 46,
        [
            new("heritage-gate-odisha",
                S("Largest stone heritage gate", "La plus grande porte patrimoniale", "Größtes steinernes Erbe-Tor", "最大の石の遺産門"),
                S("A monumental gateway in the Odishan practice of the atelier, kept in the record as the largest stone heritage gate of that body of work.",
                  "Un portail monumental de la pratique odishan, consigné comme la plus grande porte patrimoniale en pierre de cet ensemble.",
                  "Ein monumentales Tor der odishanischen Praxis, verzeichnet als das größte steinerne Erbe-Tor dieses Werkzusammenhangs.",
                  "工房のオディシャでの実践における記念碑的な門。この一連の仕事のなかで最大の石の遺産門として記録します。"),
                "gate", "—"),
            new("viswaroop-darsan",
                S("Viswaroop Darsan", "Viswaroop Darsan", "Viswaroop Darsan", "ヴィシュワループ・ダルシャン"),
                S("The cosmic form, carved as a single ordered vision, with multi-coloured stone where the image requires it.",
                  "La forme cosmique, taillée comme une vision ordonnée, avec la pierre multicolore lorsque l’image l’exige.",
                  "Die kosmische Form, als eine geordnete Vision gehauen, mit mehrfarbigem Stein, wo das Bild es verlangt.",
                  "宇宙の姿を、一つの秩序ある顕現として刻む。像が求めるところに多色石。"),
                "peacock", "—"),
            new("dasavatara",
                S("Dasavatara", "Dasavatara", "Dasavatara", "ダシャーヴァターラ"),
                S("The ten avatars as one narrative sculpture for a temple setting.",
                  "Les dix avatars comme une seule sculpture narrative pour un temple.",
                  "Die zehn Avatare als eine erzählende Skulptur für einen Tempel.",
                  "十の化身を、寺院のための一つの物語彫刻として。"),
                "wheel", "—"),
            new("perumal-mandapam",
                S("Perumal Mandapam", "Perumal Mandapam", "Perumal Mandapam", "ペルマル・マンダパム"),
                S("A pillared hall treated as architecture, not as applied ornament.",
                  "Une salle à piliers traitée comme architecture, non comme ornement appliqué.",
                  "Eine Pfeilerhalle als Architektur, nicht als aufgesetzter Schmuck.",
                  "装飾ではなく建築として扱う柱の間。"),
                "pillar", "—")
        ]),
        new("japan", S("Japan", "Japon", "Japan", "日本"), 86, 38,
        [
            new("ashokan-pillar-japan",
                S("Ashokan pillar", "Pilier d’Ashoka", "Ashoka-Säule", "アショーカ石柱"),
                S("Installed in 1995. A Mauryan memory — shaft, capital, and emblem — carved in Odisha and set in Japan. This is the journey that opened the atelier’s international record.",
                  "Installé en 1995. Une mémoire maurya — fût, chapiteau, emblème — taillée en Odisha et posée au Japon. C’est le voyage qui ouvrit le registre international de l’atelier.",
                  "Aufgestellt 1995. Eine mauryanische Erinnerung — Schaft, Kapitell, Zeichen — in Odisha gehauen und in Japan gesetzt. Diese Reise öffnete den internationalen Nachweis des Ateliers.",
                  "1995年に設置。軸、柱頭、標章というマウリヤの記憶をオディシャで刻み、日本に据えました。工房の国際的な記録を開いた旅です。"),
                "pillar", "1995")
        ]),
        new("singapore", S("Singapore", "Singapour", "Singapur", "シンガポール"), 76, 58,
        [
            new("seven-temple-shrines-singapore",
                S("Seven temple shrines", "Sept sanctuaires", "Sieben Tempelschreine", "七つの祠堂"),
                S("Seven shrines of the Odishan temple tradition, prepared to travel and installed in Singapore as one ritual family. International recognition attached to this body of work is recorded on the honour wall.",
                  "Sept sanctuaires de la tradition odishan, préparés pour le voyage et installés à Singapour comme une seule famille rituelle.",
                  "Sieben Schreine der odishanischen Tradition, für die Reise vorbereitet und in Singapur als eine rituelle Familie aufgestellt.",
                  "オディシャの寺院伝統による七つの祠堂。旅するように準備し、シンガポールで一つの祭祀の家族として設置しました。"),
                "temple", "—")
        ]),
        new("italy", S("Italy", "Italie", "Italien", "イタリア"), 49, 40,
        [
            new("italy-commissions",
                S("European commissions", "Commandes européennes", "Europäische Aufträge", "欧州の注文"),
                S("Stone from the atelier has been prepared for patrons and sacred or private settings in Italy. This site does not attach a monument’s name beyond the country’s place in the international record. Photographs join the dossier when the archive is filed.",
                  "De la pierre de l’atelier a été préparée pour des commanditaires et des lieux sacrés ou privés en Italie. Ce site n’ajoute pas le nom d’un monument au-delà de la place du pays dans le registre. Les photographies rejoindront le dossier avec l’archive.",
                  "Stein des Ateliers wurde für Auftraggeber und sakrale oder private Orte in Italien vorbereitet. Diese Site setzt keinen Denkmalsnamen über den Platz des Landes im Register hinaus. Fotografien folgen mit dem Archiv.",
                  "工房の石が、イタリアのパトロンと、聖なる、または私的な場所のために準備されています。このサイトは、国際記録における国の位置を超えて、記念碑の名を付けません。写真はアーカイブとともに加わります。"),
                "frieze", "—")
        ]),
        new("thailand", S("Thailand", "Thaïlande", "Thailand", "タイ"), 75, 52,
        [
            new("thailand-installations",
                S("Southeast Asian installations", "Installations en Asie du Sud-Est", "Installationen in Südostasien", "東南アジアの設置"),
                S("Installations in Thailand sit within the atelier’s wider Asian practice, beside the named works in Japan and Singapore. Project photographs are reserved for the archive.",
                  "Les installations en Thaïlande prennent place dans la pratique asiatique de l’atelier, à côté des œuvres nommées au Japon et à Singapour.",
                  "Installationen in Thailand stehen in der weiteren asiatischen Praxis des Ateliers, neben den benannten Werken in Japan und Singapur.",
                  "タイの設置は、日本とシンガポールの名のある仕事と並ぶ、工房のアジアでの実践のなかにあります。"),
                "lotus", "—")
        ]),
        new("russia", S("Russia", "Russie", "Russland", "ロシア"), 62, 28,
        [
            new("russia-installations",
                S("Installations for patrons", "Installations pour des commanditaires", "Installationen für Auftraggeber", "パトロンのための設置"),
                S("Works associated with Russia are recorded as installations for patrons. No further building is named here until the atelier archive confirms it.",
                  "Les œuvres liées à la Russie sont consignées comme des installations pour des commanditaires. Aucun édifice supplémentaire n’est nommé tant que l’archive ne le confirme pas.",
                  "Werke in Verbindung mit Russland sind als Installationen für Auftraggeber verzeichnet. Kein weiteres Gebäude wird genannt, bis das Archiv es bestätigt.",
                  "ロシアに関わる仕事は、パトロンのための設置として記録します。アーカイブが確かめるまで、建物の名はここに置きません。"),
                "conch", "—")
        ]),
        new("usa", S("United States", "États-Unis", "Vereinigte Staaten", "米国"), 20, 40,
        [
            new("usa-collectors",
                S("Collectors and cultural spaces", "Collectionneurs et lieux culturels", "Sammler und kulturelle Räume", "蒐集家と文化の場"),
                S("Pieces for collectors and cultural spaces in the United States. The store and the quotation desk continue this line for museums and private rooms.",
                  "Des pièces pour des collectionneurs et des lieux culturels aux États-Unis. La boutique et le bureau des devis prolongent cette ligne.",
                  "Stücke für Sammler und kulturelle Räume in den Vereinigten Staaten. Kollektion und Angebotsstelle setzen diese Linie fort.",
                  "米国の蒐集家と文化の場のための作品。受注と見積は、美術館と私的な部屋に向けてこの線を続けます。"),
                "murti", "—")
        ]),
        new("israel", S("Israel", "Israël", "Israel", "イスラエル"), 56, 44,
        [
            new("israel-commissions",
                S("Sacred and private commissions", "Commandes sacrées et privées", "Sakrale und private Aufträge", "聖なる注文と私的な注文"),
                S("Commissions for sacred and private settings in Israel are part of the atelier’s international map. Names of rooms are added only from the archive.",
                  "Des commandes pour des lieux sacrés et privés en Israël font partie de la carte internationale. Les noms de salles ne viennent que de l’archive.",
                  "Aufträge für sakrale und private Orte in Israel gehören zur internationalen Karte. Namen von Räumen kommen nur aus dem Archiv.",
                  "イスラエルの聖なる場所と私的な場所への注文は、工房の国際地図の一部です。部屋の名はアーカイブからのみ加えます。"),
                "kalasha", "—")
        ])
    ];

    public static readonly IReadOnlyList<Course> Courses =
    [
        new("week",
            S("One-week cultural workshop", "Atelier culturel d’une semaine", "Einwöchige kulturelle Werkstatt", "一週間の文化講習"),
            S("7 days", "7 jours", "7 Tage", "7日"),
            S("An introduction to stone, tool and icon, for travellers and professionals with a short stay.",
              "Une introduction à la pierre, à l’outil et à l’icône, pour un court séjour.",
              "Eine Einführung in Stein, Werkzeug und Ikone für einen kurzen Aufenthalt.",
              "短い滞在の旅人と専門家のための、石、道具、図像への導入。")),
        new("month",
            S("One-month foundation", "Fondation d’un mois", "Einmonatige Grundlage", "一か月の基礎"),
            S("1 month", "1 mois", "1 Monat", "1か月"),
            S("Drawing, roughing and the first finished devotional study.",
              "Dessin, dégrossi, et une première étude de dévotion finie.",
              "Zeichnung, Schroten und eine erste vollendete Andachtsstudie.",
              "下絵、荒彫り、そして最初の仕上げた礼拝習作。")),
        new("quarter",
            S("Three-month traditional sculpting", "Sculpture traditionnelle, trois mois", "Drei Monate traditionelle Bildhauerei", "三か月の伝統彫刻"),
            S("3 months", "3 mois", "3 Monate", "3か月"),
            S("A sustained carving of one image, with temple drawing beside the bench.",
              "La taille soutenue d’une image, avec le dessin de temple près de l’établi.",
              "Eine anhaltende Arbeit an einem Bild, mit Tempelzeichnung neben der Bank.",
              "一つの像を継続して刻み、作業台の傍らで寺院図面を描きます。")),
        new("half",
            S("Six-month professional training", "Formation professionnelle de six mois", "Sechsmonatige professionelle Ausbildung", "六か月の専門訓練"),
            S("6 months", "6 mois", "6 Monate", "6か月"),
            S("For makers who intend to practise. Tool discipline, iconography and a completed work.",
              "Pour celles et ceux qui veulent pratiquer. Discipline de l’outil, iconographie, œuvre achevée.",
              "Für Menschen, die praktizieren wollen. Werkzeug, Ikonografie und ein vollendetes Werk.",
              "実践しようとする人のために。道具の規律、図像、完成した仕事。")),
        new("year",
            S("One-year master artisan fellowship", "Résidence de maître artisan, un an", "Einjähriges Meisterstipendium", "一年の名匠フェローシップ"),
            S("1 year", "1 an", "1 Jahr", "1年"),
            S("A year inside the atelier’s standard, ending with a fellowship piece and the academy certificate.",
              "Une année dans l’exigence de l’atelier, close par une pièce de résidence et le certificat.",
              "Ein Jahr im Maß des Ateliers, abgeschlossen mit einem Stipendienstück und dem Zertifikat.",
              "工房の基準のなかで一年。フェローシップの作品と学院の修了証で結びます。"))
    ];

    public static readonly IReadOnlyList<PressItem> Press =
    [
        new("interviews",
            S("Interviews", "Entretiens", "Interviews", "インタビュー"),
            S("Conversations with the master", "Conversations avec le maître", "Gespräche mit dem Meister", "名匠との対話"),
            S("Interviews are listed as the archive receives them. The public facts they rest on are the biography: Puri, the cooperative, Japan, the National Award, the emporium, and the teaching of more than a thousand artisans.",
              "Les entretiens seront listés à mesure de l’archive. Les faits publics sur lesquels ils reposent sont la biographie.",
              "Interviews werden gelistet, sobald das Archiv sie aufnimmt. Die öffentlichen Tatsachen sind die Biografie.",
              "インタビューはアーカイブが受け取るたびに掲げます。その土台となる公の事実は経歴にあります。"),
            "—"),
        new("news",
            S("News coverage", "Couverture de presse", "Berichterstattung", "報道"),
            S("Notices of awards and installations", "Échos des prix et des installations", "Notizen zu Preisen und Installationen", "賞と設置の知らせ"),
            S("The coverage this site can vouch for is the sequence of honours and installations already dated: 1990, 1995, 1997, 2005, 2006, 2016 and the 2024 nomination.",
              "La couverture que ce site peut garantir est la suite des honneurs et installations déjà datée.",
              "Was diese Site verbürgen kann, ist die bereits datierte Folge der Ehrungen und Installationen.",
              "このサイトが請け合える報道は、すでに年を付した栄誉と設置の列です。"),
            "—"),
        new("documentaries",
            S("Documentaries", "Documentaires", "Dokumentarfilme", "記録映画"),
            S("Film of the workshop", "Film de l’atelier", "Film der Werkstatt", "工房の映像"),
            S("A documentary chapter will hold the atelier film when it is released. Until then the 360° workshop is the spatial account of a working day.",
              "Un chapitre documentaire accueillera le film de l’atelier lorsqu’il sera publié. D’ici là, l’atelier à 360° est le récit spatial d’une journée.",
              "Ein Dokumentarkapitel nimmt den Film des Ateliers auf, sobald er vorliegt. Bis dahin ist die 360°-Werkstatt der räumliche Bericht eines Arbeitstags.",
              "記録映画の章は、工房の映像が公開されたときにそれを収めます。それまでは、360°の工房が一日の空間的な記録です。"),
            "—"),
        new("padma-story",
            S("Padma Shri nomination", "Nomination Padma Shri", "Padma-Shri-Nominierung", "パドマ・シュリー推薦"),
            S("The 2024 nomination story", "Le récit de la nomination de 2024", "Die Geschichte der Nominierung 2024", "2024年の推薦の物語"),
            S("In 2024 the atelier gathered its record — temple work, international installation, and the training of artisans — for a Padma Shri nomination. The nomination profile on this site is that gathering. It is a proposal for honour, not the honour itself.",
              "En 2024 l’atelier a réuni son registre pour une nomination Padma Shri. Le profil sur ce site est ce rassemblement. C’est une proposition d’honneur, non l’honneur lui-même.",
              "2024 stellte das Atelier seinen Nachweis für eine Padma-Shri-Nominierung zusammen. Das Profil auf dieser Site ist diese Sammlung. Es ist ein Vorschlag der Ehre, nicht die Ehre selbst.",
              "2024年、工房は寺院の仕事、国外設置、職人育成の記録をパドマ・シュリー推薦のために集めました。このサイトのプロフィールがその集成です。栄誉への提案であり、栄誉そのものではありません。"),
            "2024"),
        new("exhibitions",
            S("Exhibitions", "Expositions", "Ausstellungen", "展覧会"),
            S("Invitations and rooms", "Invitations et salles", "Einladungen und Räume", "招聘と会場"),
            S("Museums and cultural rooms wishing to exhibit the work write through the contact desk, under “Invite an exhibition”. Past rooms are added by name only when the archive confirms them.",
              "Musées et salles culturelles écrivent par le bureau de contact, sous « Inviter une exposition ». Les salles passées ne sont nommées que si l’archive le confirme.",
              "Museen und kulturelle Räume schreiben über den Kontakt, unter „Eine Ausstellung einladen“. Vergangene Räume werden nur genannt, wenn das Archiv sie bestätigt.",
              "作品を展覧したい美術館と文化の部屋は、連絡の「展覧会を招く」から書いてください。過去の会場は、アーカイブが確かめたときにのみ名を置きます。"),
            "—")
    ];

    public static readonly IReadOnlyList<TourRoom> Rooms =
    [
        new("threshold",
            S("Threshold", "Seuil", "Schwelle", "閾"),
            S("You enter as a visitor enters a temple compound: slowly, and by a gate. The atelier’s gate work, including the large heritage gateway in Odisha, is the idea of this room.",
              "On entre comme dans l’enceinte d’un temple : lentement, et par une porte.",
              "Man tritt ein, wie man einen Tempelbezirk betritt: langsam, und durch ein Tor.",
              "寺院の境内に入るように、ゆっくりと、門から入ります。"),
            "gate", "/masterpieces/heritage-gate-odisha"),
        new("image",
            S("Sacred image", "Image sacrée", "Heiliges Bild", "聖像"),
            S("Ganesha, Krishna, Jagannath, the Dasavatara and Viswaroop. The image is not decoration of a religion. It is the religion’s proportion, cut in stone.",
              "Ganesha, Krishna, Jagannath, le Dasavatara et le Viswaroop. L’image n’est pas un décor : elle est la proportion, taillée.",
              "Ganesha, Krishna, Jagannath, das Dasavatara und Viswaroop. Das Bild ist nicht Dekor. Es ist die Proportion, in Stein geschnitten.",
              "ガネーシャ、クリシュナ、ジャガンナート、ダシャーヴァターラ、ヴィシュワループ。像は装飾ではなく、石に刻んだ比例です。"),
            "murti", "/masterpieces"),
        new("temple",
            S("Temple", "Temple", "Tempel", "寺院"),
            S("Pillars, mandapams, wheels and shrines. Architectural stone is judged by whether a building can trust it.",
              "Piliers, mandapams, roues et sanctuaires. La pierre d’architecture se juge à la confiance qu’un bâtiment peut lui donner.",
              "Pfeiler, Mandapams, Räder und Schreine. Architekturstein wird daran gemessen, ob ein Bau ihm trauen kann.",
              "柱、マンダパム、車輪、祠堂。建築石材は、建物がそれを信頼できるかで判断します。"),
            "temple", "/masterpieces?kind=architecture"),
        new("world",
            S("The world", "Le monde", "Die Welt", "世界"),
            S("Japan in 1995, Singapore’s seven shrines, and the wider map of eight countries.",
              "Le Japon en 1995, les sept sanctuaires de Singapour, et la carte de huit pays.",
              "Japan 1995, die sieben Schreine Singapurs und die Karte von acht Ländern.",
              "1995年の日本、シンガポールの七祠堂、そして八つの国の地図。"),
            "pillar", "/global-projects"),
        new("teaching",
            S("Teaching floor", "Salle d’enseignement", "Unterricht", "教える床"),
            S("More than a thousand artisans. The academy keeps that duty open to students from outside India.",
              "Plus de mille artisans. L’académie tient ce devoir ouvert aux étudiants venus d’ailleurs.",
              "Mehr als tausend Handwerker. Die Akademie hält diese Pflicht offen für Studierende von außerhalb.",
              "千人を超える職人。学院は、インドの外から来る学生にもその義務を開いています。"),
            "conch", "/academy"),
        new("honour",
            S("Honour wall", "Mur des honneurs", "Ehrenwand", "栄誉の壁"),
            S("1990, 1997, 2005, and the 2024 nomination, which remains a nomination.",
              "1990, 1997, 2005, et la nomination de 2024, qui reste une nomination.",
              "1990, 1997, 2005 und die Nominierung von 2024, die eine Nominierung bleibt.",
              "1990年、1997年、2005年、そして推薦のままである2024年の推薦。"),
            "kalasha", "/awards")
    ];

    public static readonly IReadOnlyList<Station> Stations =
    [
        new("yard",
            S("Stone yard", "Cour des blocs", "Steinhof", "石置き場"),
            S("Blocks wait to be read. Colour, grain and sound under the hammer decide whether a stone may become an image.",
              "Les blocs attendent d’être lus. Couleur, fil et son sous le marteau décident.",
              "Blöcke warten darauf, gelesen zu werden. Farbe, Lager und Klang unter dem Hammer entscheiden.",
              "石は読まれるのを待っています。色、石目、槌の下の音が、像になり得るかを決めます。"),
            "pillar"),
        new("drawing",
            S("Drawing floor", "Salle de dessin", "Zeichensaal", "下絵の床"),
            S("Proportion is drawn before pride enters the chisel. Temple plans sit beside icon drawings.",
              "La proportion est dessinée avant que l’orgueil n’entre dans le ciseau.",
              "Die Proportion wird gezeichnet, bevor Stolz in den Meißel fährt.",
              "誇りが鑿に入る前に、比例を描きます。寺院の図面は図像の傍らにあります。"),
            "frieze"),
        new("bay",
            S("Carving bay", "Baie de taille", "Hauhalle", "彫りの間"),
            S("The working day is the sound of many chisels. Roughing opens the block; the face comes last.",
              "La journée est le son de nombreux ciseaux. Le dégrossi ouvre le bloc ; le visage vient en dernier.",
              "Der Tag ist der Klang vieler Meißel. Schroten öffnet den Block; das Gesicht kommt zuletzt.",
              "一日は、多くの鑿の音です。荒彫りが石を開き、顔は最後に来ます。"),
            "murti"),
        new("colour",
            S("Patchwork table", "Table de patchwork", "Patchwork-Tisch", "パッチワークの台"),
            S("Stones of different colour are fitted so the joint is structure, not a crack.",
              "Des pierres de couleurs différentes sont ajustées pour que le joint soit structure, non une fissure.",
              "Steine verschiedener Farbe werden so gefügt, dass die Fuge Struktur ist, kein Riss.",
              "異なる色の石を、継ぎ目が亀裂ではなく構造になるように嵌めます。"),
            "peacock"),
        new("finish",
            S("Finishing", "Finition", "Vollendung", "仕上げ"),
            S("Light is the last tool. A surface is finished when it describes the form without shouting.",
              "La lumière est le dernier outil. Une surface est finie lorsqu’elle décrit la forme sans crier.",
              "Licht ist das letzte Werkzeug. Eine Oberfläche ist vollendet, wenn sie die Form beschreibt, ohne zu schreien.",
              "光が最後の道具です。叫ばずに形を語るとき、表面は仕上がっています。"),
            "lotus"),
        new("desk",
            S("Temple desk", "Table de temple", "Tempeltisch", "寺院の机"),
            S("Plans, elevations and letters from patrons. A shrine is agreed on paper before it is agreed in stone.",
              "Plans, élévations et lettres. Un sanctuaire est convenu sur le papier avant de l’être dans la pierre.",
              "Pläne, Aufrisse und Briefe. Ein Schrein wird auf Papier verabredet, bevor er im Stein verabredet wird.",
              "図面、立面、パトロンの書簡。祠堂は、石で決まる前に紙の上で決まります。"),
            "temple")
    ];
}
